### ISSUE TITLE
DSCForLinux extension installs outdated packages for both OMI and DSC (blocking onboarding in Azure Automation DSC)

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-linux-extensions#102]
The DSC For Linux extension installs outdated versions of OMI and DSC.
Versions installed are packaged with the extension so a new version of the extension is needed to deliver the updated packages.
Current version OMI: 1.0.8 New version available: 1.0.8-4
Current version DSC: 1.0.0-320 New version available 1.1.1-70
The current versions are not supported for Azure Automation DSC onboarding. When tried, an unhandled exception is thrown.

**Comment by lizzha** [comment]
@bgelens we're working on DSC For Linux extension 1.1 that installs the latest version of packages, and it's expected to be published this week

**Comment by lizzha** [comment]
@bgelens DSCForLinux 2.0 was released, the issue is resolved

**Comment by JustinBacaAIS** [comment]
Similar issue on RHEL 7.4 image in Azure Government.  When installing the DSC extension via ARM template we receive an error that it failed to install omi version 1.0.8-4, when we review the currently installed version it's 1.0.8-6, which if removed using sudo yum remove omi.x86_64, will return again after stopping and starting the waagent service.  This is odd behavior but ok...Analyzing the /var/lib/waagent/Microsoft.OSTCExtensions.DSCForLinux-2.0.0.0/dsc.py script we can see that 1.0.8-4 is hard-coded into a variable (omi_version_rpm = '1.0.8-4').  The work around that we have come up with so far which is not really a solution is to run the DSC extension deployment via ARM template, while it's deploying it will continue to deploy not showing any errors until you logon to the RHEL server and look at the /var/log/azure/Microsoft.OSTCExtensions.DSCForLinux/2.0.0.0/extension.log, at this time, while extension still shows it's being deployed via Powershell ARM template, run sudo yum remove omi.x86_64  and then sudo reboot.  Upon reboot the extension will install successful.  We have tried running sudo yum remove omi.x86_64 and restarting the waagent service, this brings the rpm package back as installed and another error as seen below...Not sure why or how, haven't dug that far into it. 

Linux DSC Extension error: 

2018/03/01 18:26:57 [Microsoft.OSTCExtensions.DSCForLinux-1.0]Config decoded correctly.
2018/03/01 18:26:57 [Microsoft.OSTCExtensions.DSCForLinux-1.0]Package dsc is removed successfully
2018/03/01 18:26:58 ERROR:[Microsoft.OSTCExtensions.DSCForLinux-1.0]Failed to install the extension with error: Failed to install package omi-1.0.8-4: , stack trace: Traceback (most recent call last):
2018/03/01 18:26:58 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.DSCForLinux-2.0.0.0/dsc.py", line 125, in install
2018/03/01 18:26:58 ERROR:    install_dsc_packages()
2018/03/01 18:26:58 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.DSCForLinux-2.0.0.0/dsc.py", line 268, in install_dsc_packages
2018/03/01 18:26:58 ERROR:    rpm_install_pkg(omi_package_path + '.x64.rpm', 'omi-' + omi_version_rpm)
2018/03/01 18:26:58 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.DSCForLinux-2.0.0.0/dsc.py", line 282, in rpm_install_pkg
2018/03/01 18:26:58 ERROR:    raise Exception('Failed to install package {0}: {1}'.format(package_name, output))
2018/03/01 18:26:58 ERROR:Exception: Failed to install package omi-1.0.8-4:
2018/03/01 18:26:58 ERROR:
2018/03/01 18:26:58 [Microsoft.OSTCExtensions.DSCForLinux-1.0]Install,error,1,Install Failed.
2018/03/01 18:45:33 [Microsoft.OSTCExtensions.DSCForLinux-1.0]sequence number is 0
2018/03/01 18:45:33 [Microsoft.OSTCExtensions.DSCForLinux-1.0]setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.DSCForLinux-2.0.0.0/config/0.sett
ings

**Comment by sscchh2001** [comment]
Same issue for Azure Mooncake.

2018/04/12 06:05:15 [Microsoft.OSTCExtensions.DSCforLinux-1.0]Config decoded correctly.
2018/04/12 06:05:16 [Microsoft.OSTCExtensions.DSCforLinux-1.0]Package dsc is removed successfully
2018/04/12 06:05:16 ERROR:[Microsoft.OSTCExtensions.DSCforLinux-1.0]Failed to install the extension with error: Failed to install package omi-1.0.8-4: , stack trace: Traceback (most recent call last):
2018/04/12 06:05:16 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.DSCforLinux-2.0.0.0/dsc.py", line 125, in install
2018/04/12 06:05:16 ERROR:    install_dsc_packages()
2018/04/12 06:05:16 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.DSCforLinux-2.0.0.0/dsc.py", line 268, in install_dsc_packages
2018/04/12 06:05:16 ERROR:    rpm_install_pkg(omi_package_path + '.x64.rpm', 'omi-' + omi_version_rpm)
2018/04/12 06:05:16 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.DSCforLinux-2.0.0.0/dsc.py", line 282, in rpm_install_pkg
2018/04/12 06:05:16 ERROR:    raise Exception('Failed to install package {0}: {1}'.format(package_name, output))
2018/04/12 06:05:16 ERROR:Exception: Failed to install package omi-1.0.8-4:
