### ISSUE TITLE
azure-linux-extensions / VMAccess /  does not work

### ISSUE THREAD

**Issue by Vijayaraghavanl** [Azure/azure-linux-extensions#104]
I am trying to follow section 2.2.2 @ https://github.com/Azure/azure-linux-extensions/tree/master/VMAccess

However, I keep encountering the below error:

2016/03/08 10:31:03 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0/./vmaccess.py", line 96, in enable
2016/03/08 10:31:03 ERROR:    _set_user_account_pub_key(protect_settings, hutil)
2016/03/08 10:31:03 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0/./vmaccess.py", line 174, in _set_user_account_pub_key
2016/03/08 10:31:03 ERROR:    if cert_txt and cert_txt.strip().lower().startswith("ssh-rsa"):
2016/03/08 10:31:03 ERROR:AttributeError: 'list' object has no attribute 'strip'
2016/03/08 10:31:03 ERROR:

My PEM file contents look like below.

---- BEGIN SSH2 PUBLIC KEY ----
Comment: "rsa-key-20160308"
AAAAB3NzaC1yc2EAAAABJQAAAQEAtHsEdGFL+CrgYH7ADFZMf262Vpnu8v4VUBZ1
qShdgD0cj1aAoNA/mqZ9aYMta8attiEiqnqDQ9FodYYs9QnySD7ik90NKj5Hoa2Q+l5Ra
wPq3+zzgyp6nQJkMPgI9JxzXdQYaIoW9jWm9x0ofEZiNhA8hpAYDlh0vYWzmPiHi
JilaZ7OHTyhVvWARelN5zkQAQ0eH5WJtEx6v2XZglXcdGBvT8Q==
---- END SSH2 PUBLIC KEY ----

Please advise.

**Comment by bingosummer** [comment]
@Vijayaraghavanl 

The format of your PEM file is not supported.
Please use either of the following two formats.
1. starts with `ssh-rsa`
2. starts with `-----BEGIN CERTIFICATE-----`

More informations:
https://github.com/Azure/azure-linux-extensions/tree/master/VMAccess#12-protected-configuration

**Comment by Vijayaraghavanl** [comment]
I tried this again and failed. Here is how my PEM file looks like:

-----BEGIN CERTIFICATE-----
MIIDozCCAougAwIBAgIJAOPkTSlOEW0DMA0GCSqGSIb3DQEBCwUAMGgxCzAJBgNV
BAYTAklOMRIwEAYDVQQIDAlLYXJuYXRha2ExEjAQBgNVBAcMCUJhbmdhbG9yZTEN
MAsGA1UECgwESG9tZTELMAkGA1UECwwCSVQxFTATBgNVBAMMDHVzZXJhY2NvdW50
MTAeFw0xNTExMDQxMzEwMjFaFw0xNjExMDMxMzEwMjFaMGgxCzAJBgNVBAYTAklO
MRIwEAYDVQQIDAlLYXJuYXRha2ExEjAQBgNVBAcMCUJhbmdhbG9yZTENMAsGA1UE
CgwESG9tZTELMAkGA1UECwwCSVQxFTATBgNVBAMMDHVzZXJhY2NvdW50MTCCASIw
DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPD8L5E1cfTjKMAuoxsM+fFIjF0K
HU98GuWsxRkOjuPQthv4JulupJnLwn/DiIZQR7r/by0P4qbP8jRholbhlWqImxGL
cvM60RrkTJKTHh6EsqRhedrZaMaSWBknWV2RHQyHmD6GGMibP9ZjJRfmp7qhAUT5
xeCEF+T/scgzG+oxvywBdJU/KN/Hzw413c6LhwiA5jHhHjjyyIbgoQjPT7XUSulg
XP0W2mYlvFg48fFijOp7KHz4A5KzxEvuXokRw+ex4zOTDRacuCCujAonqGYfGvDa
UQenfeqHSpSpOWL+1DNyuCyy0i31BQMzg7G1DiaVr8gfaC01ghOQHAzKIpkCAwEA
AaNQME4wHQYDVR0OBBYEFOkp1+h8ucO+79jaTbV/N/z6eIuvMB8GA1UdIwQYMBaA
FOkp1+h8ucO+79jaTbV/N/z6eIuvMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEL
BQADggEBADeujyJnUwNdONyk6uJlWE28YS3J6lIhgx9tfoyecjg4gt5bEDk9RQuy
7nPOatJ/u8bIT8v8U3QVzZtMvnDUXT7wR2noolKZlB575eSr5Wlxe/nLuehp1jpc
IG9pFUEe2gGr+RibQ3erkOcC6uuyyWbp9zuqpVcAHFLf0EeWvm0ElUv4zMlaIRCm
/QY44N9KSH0H35v1dVVZaOm2wbCs82pQzafjO7W/Cob4=
-----END CERTIFICATE-----

I also tried this and no luck.

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDw/C+RNXH04yjALqMbDPnxSIxdCh1PfBrlrMUZDo7j0LYb+CbpbqSZy8J/w4iGUEe6/28tD+Kmz/+11ErpYFz9FtpmJbxYOPHxYozqeyh8+AOSs8RL7l6JEcPnseMzkw0WnLggrowKJ6hmHxrw2lEHp33qh0qUqTli/tQzcrgsstIt9QUDM4OxtQ4mla/IH2gtNYITkBwMyiKZ

I would like to point out that when I use the 'ssh-rsa' type on the portal it is verified as to be correct and same is the case with the one that starts like '---- BEGIN SSH2 PUBLIC KEY ----' type. But somehow can't get anything working through powershell.

What am I missing?

**Comment by bingosummer** [comment]
Could you please share your powershell command when using `ssh-rsa` and the output? Does powershell throw an error?

**Comment by Vijayaraghavanl** [comment]
Leave a commentSet-AzureRmVMExtension : Long running operation failed with status 'Failed'.
StartTime: 3/9/2016 11:11:17 AM
EndTime: 3/9/2016 11:12:43 AM
OperationID: e061da72-05a7-498a-96c1-5c0703c1f4e4
Status: Failed
ErrorCode: VMExtensionProvisioningError
ErrorMessage: VM has reported a failure when processing extension 'VMAccessForLinux'. Error message: "Enable failed.".
At C:\Users\Vijay\Desktop\Scripts\Windows VM ARM\Deploy-MultipleAzureVM v3.0 ARM.ps1:394 char:9
+         Set-AzureRmVMExtension -ResourceGroupName $VMResourceGroup -V ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmVMExtension], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.SetAzureVMExtensionCommand

**Comment by bingosummer** [comment]
@Vijayaraghavanl 

Sorry, I can't reproduce this issue.

Could you please share the IP/username/password of the VM? If yes, please send them to binxi@microsoft.com.
If no, please do the following things to narrow down this issue:
1. Run `service walinuxagent status` to check whether the linux agent is alive.
2. Collect /var/log/waagent.log
3. Collect /var/log/azure/.
4. Send the logs in 2 and 3 to binxi@microsoft.com.

**Comment by bingosummer** [comment]
This issue is resolved after @Vijayaraghavanl and I discussed offline.
The root cause is wrong format of the public key is used.
1. For the `ssh-rsa` public key, it worked.
2. For the PEM format key, the contents of the key file should be wrapped into one line.

https://github.com/Azure/azure-linux-extensions/tree/master/VMAccess#12-protected-configuration

**Comment by Vijayaraghavanl** [comment]
Thanks Bin for your help. The issues is now resolved.

**Comment by squillace** [comment]
@Vijayaraghavanl @bingosummer Hey, can we be a bit specific about which formats for which deployment system? SSH-RSA .pub file contents typically work for ARM, whereas openssl-style SSH-RSA formats in a .pem file typically work for ASM. 

is this still true for vm access?

**Comment by Vijayaraghavanl** [comment]
@squillace: Yes it is true. Whatever you have mentioned above is correct. Thanks!
