### ISSUE TITLE
Microsoft.OSTCExtensions LinuxDiagnostic 2.3.5

### ISSUE THREAD

**Issue by clintonm9** [Azure/azure-linux-extensions#107]
Using the Azure Portal and setting the Diagnostics status to On gives two options for Linux VM (Basic Matric and boot diagnostics). 

When the Azure Portal turns this setting on it sends a long Base64 string to the VM that has all kinds of settings. For example:

`<WadCfg>
   <DiagnosticMonitorConfiguration overallQuotaInMB="4096">
      <DiagnosticInfrastructureLogs scheduledTransferPeriod="PT1M" scheduledTransferLogLevelFilter="1h, 1m" />
      <PerformanceCounters scheduledTransferPeriod="PT1M">
         <PerformanceCounterConfiguration counterSpecifier="\Memory\AvailableMemory" sampleRate="PT15S" unit="Bytes">
            <annotation displayName="Memory available" locale="en-us" />
         </PerformanceCounterConfiguration>`
..................

Looking at the Resource Manager Powershell code it shows a perfCfg with an SQL query. 

Is there a way from Powershell to turn all the same settings on that Azure Portal is setting?

Thanks

**Comment by hosungsmsft** [comment]
I believe the same base64 string can be passed as the value of the "xmlCfg" JSON field in either of the .json config files you provide when using Powershell for the purpose, and that'll achieve the same thing as with the portal. I suppose the "perfCfg" field may need to go away, though. @karataliu might comment better. Thanks.

**Comment by karataliu** [comment]
Yes, for powershell configuration, you'll need to set the following base64 string to 'xmlCfg' to archive same effect.

- Base64 string:
```
base64 -w0 <<EOF
<WadCfg><DiagnosticMonitorConfiguration><Metrics resourceId="{id}"></Metrics></DiagnosticMonitorConfiguration></WadCfg>
EOF
```
Remember to replace '{id}' with your VM name.

- Configuration example:
```
$PublicConf = '{
  "xmlCfg":"PFdhZENmZz48RGlhZ25vc3RpY01vbml0b3JDb25maWd1cmF0aW9uPjxNZXRyaWNzIHJlc291cmNlSWQ9IntpZH0iPjwvTWV0cmljcz48L0RpYWdub3N0aWNNb25pdG9yQ29uZmlndXJhdGlvbj48L1dhZENmZz4K",
  "EnableSyslog":"true"
}'
```
- Enable diagnostic extension using powershell:

Please refer to '2.2. Using Azure Powershell'
https://github.com/Azure/azure-linux-extensions/tree/master/Diagnostic
