### ISSUE TITLE
Issuing reboot from CustomScript hangs resource group deployment

### ISSUE THREAD

**Issue by anweiss** [Azure/azure-linux-extensions#110]
I noticed that when I initiate a reboot from a script, the resource group deployment hangs. I'm trying to reboot a machine from the CustomScript extension and then continue execution of a different script after the reboot; all as part of the same resource group template deployment.

**Comment by bingosummer** [comment]
Yes. You are right.
Because of a reboot, CustomScript Extension has no chance to update the status. So, if you have a look at /var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0/status/0.status, you will see the status is still "transitioning". Then the deployment will fail.
