### ISSUE TITLE
OmsAgent: Enable failed with exit code 52 Couldn't create marker file

### ISSUE THREAD

**Issue by ITRON-kpalmberg** [Azure/azure-linux-extensions#1116]
When provisioning the OMS agent for Linux (v1.12) I'm receiving an error during the on-boarding/enabling process.

`Enable failed with exit code 52 Couldn't create marker file`

There isn't any info on this error in the [Microsoft error docs](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/agent-linux-troubleshoot#installation-error-codes) for this extension. However, I tracked the error down to a Python file in this repository. The section of code in question is [here after line 629](https://github.com/Azure/azure-linux-extensions/blob/2fbd44a87c59fb71a716fc00799843348e1a41e7/OmsAgent/omsagent.py#L629). This section shows that it's creating a "marker file" to support multi-homing and to show it was onboarding via the extension. Other comments show that there is a permissions issue when trying to access the marker file:

`# we are having some kind of permissions issue creating the marker file`

I noticed there seems to be an issue with this file even though all of the other files in the workspace directory seem to be appropriately owned by the `omsagent` user and `omiusers` group.

```
ls -al

drwxr-x--- 3 omsagent omiusers 4096 May 29 02:10 .
drwxr-x--- 4 omsagent omiusers 4096 May 28 23:50 ..
-rw-r--r-- 1 root     root        0 May 28 23:50 .azure_extension_marker
-rw-r----- 1 omsagent omiusers  968 May 29 02:10 omsadmin.conf
-rw-r----- 1 omsagent omiusers 3083 May 28 23:50 omsagent.conf
drwxr-x--- 2 omsagent omiusers 4096 May 29 00:01 omsagent.d
-rw-r----- 1 omsagent omiusers    0 May 28 23:50 .service_registered
```

The `.azure_extension_marker` marker file seems to be owned by `root` user even though the code at [line 609](https://github.com/Azure/azure-linux-extensions/blob/2fbd44a87c59fb71a716fc00799843348e1a41e7/OmsAgent/omsagent.py#L609) is supposed to recursively set permissions for all files in the workspace directory.

An important note is that the onboarding process seems to complete just fine (VM shows up as datasource in workspace) but this extension failure fails all deployments that use this extension in ARM templates. 

How can this issue be resolved so that the agent can be provisioned through extension? This issue is occurring on more than 1 VM/VMSS in Azure (not isolated issue). 

@simathih, do you possible have comment on this? I noticed your [pull request](https://github.com/Azure/azure-linux-extensions/pull/894) which added this code so I think you might have good context on this issue.

**Comment by aymond** [comment]
I received the same error. Logs included to support the above issue.

``` bash
Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux]# cat extension.log
2020/06/02 15:35:14 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] sequence number is 0
2020/06/02 15:35:14 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] setting file path is/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25/config/0.settings
2020/06/02 15:35:14 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "*** REDACTED ***", "publicSettings": {"stopOnMultipleConnections": "true", "workspaceId": "1-2-3-4-5", "azureResourceId": "/subscriptions/1-2-3-4-5/resourceGroups/rg/providers/Microsoft.Compute/virtualMachines/vm"}, "protectedSettingsCertThumbprint": "*** REDACTED ***"}}]}
2020/06/02 15:35:14 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Config decoded correctly.
2020/06/02 15:35:14 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Running command "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25/packages/omsagent-1.12.25-0.universal.x64.sh --upgrade"
2020/06/02 15:35:18 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Output of command "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25/packages/omsagent-1.12.25-0.universal.x64.sh --upgrade":
2020/06/02 15:35:18 Checking host architecture ...
2020/06/02 15:35:18 Extracting...
2020/06/02 15:35:18 ----- Upgrading package: omi (omi-1.6.3-0.ulinux.x64) -----
2020/06/02 15:35:18 Skipping package since existing version >= version available
2020/06/02 15:35:18 Trying to stop omi with systemctl
2020/06/02 15:35:18 omi is stopped.
2020/06/02 15:35:18 Trying to start omi with systemctl
2020/06/02 15:35:18 omi is started.
2020/06/02 15:35:18 ----- Upgrading package: omsagent (omsagent-1.12.25-0.universal.x64) -----
2020/06/02 15:35:18 Skipping package since existing version >= version available
2020/06/02 15:35:18 Applying Syslog conf hotfix...
2020/06/02 15:35:18 ----- Upgrading package: omsconfig (omsconfig-1.1.1-927.x64) -----
2020/06/02 15:35:18 Skipping package since existing version >= version available
2020/06/02 15:35:18 Applying DSC nxOMSSyslog hotfix...
2020/06/02 15:35:18 Trying to stop omi with systemctl
2020/06/02 15:35:18 omi is stopped.
2020/06/02 15:35:18 Trying to start omi with systemctl
2020/06/02 15:35:18 omi is started.
2020/06/02 15:35:18 ----- Updating bundled packages -----
2020/06/02 15:35:18 Checking if Apache is installed ...
2020/06/02 15:35:18   Apache not found, will not install
2020/06/02 15:35:18 Checking if Docker is installed...
2020/06/02 15:35:18   Docker not found. Docker agent will not be installed.
2020/06/02 15:35:18 Checking if MySQL is installed ...
2020/06/02 15:35:18   MySQL not found, will not install
2020/06/02 15:35:18 Extracting...
2020/06/02 15:35:18 Updating auoms ...
2020/06/02 15:35:18 ----- Updating package: auoms (auoms-2.0.1-19.universal.x64) -----
2020/06/02 15:35:18 Skipping package since existing version >= version available
2020/06/02 15:35:18 Shell bundle exiting with code 0
2020/06/02 15:35:18 Install succeeded
2020/06/02 15:35:18 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Install succeeded
2020/06/02 15:35:18 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Install,success,0,Install succeeded
2020/06/02 15:35:19 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] sequence number is 0
2020/06/02 15:35:19 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] setting file path is/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25/config/0.settings
2020/06/02 15:35:19 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "*** REDACTED ***", "publicSettings": {"stopOnMultipleConnections": "true", "workspaceId": "1-2-3-4-5", "azureResourceId": "/subscriptions/1-2-3-4-5/resourceGroups/rg/providers/Microsoft.Compute/virtualMachines/vm"}, "protectedSettingsCertThumbprint": "*** REDACTED ***"}}]}
2020/06/02 15:35:19 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Config decoded correctly.
2020/06/02 15:35:19 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] vmResourceId from Metadata API is /subscriptions/1-2-3-4-5/resourceGroups/rg/providers/Microsoft.Compute/virtualMachines/vm
2020/06/02 15:35:19 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Handler initiating onboarding.
2020/06/02 15:35:19 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Output:
2020/06/02 15:35:19 Azure Resource ID updated.
2020/06/02 15:35:19 Workspace 1-2-3-4-5 already onboarded and agent is running.
2020/06/02 15:35:19 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Error creating /etc/opt/microsoft/omsagent/1-2-3-4-5/conf/.azure_extension_marker with error: [Errno 2] No such file or directory: u'/etc/opt/microsoft/omsagent/1-2-3-4-5/conf/.azure_extension_marker'
2020/06/02 15:35:27 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Output of command "/opt/microsoft/omsagent/bin/service_control restart":
2020/06/02 15:35:27
2020/06/02 15:35:27 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] start watcher process ['python', '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25/omsagent.py', '-telemetry']
2020/06/02 15:35:27 ERROR:Enable failed with exit code 52 Couldn't create marker file
2020/06/02 15:35:27 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Enable failed with exit code 52 Couldn't create marker file
2020/06/02 15:35:27 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Enable,failed,52,Enable failed with exit code 52 Couldn't create marker file
[root@mn242-development Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux]#
```

**Comment by OnAzureCloud9** [comment]
@aymond just curious, are you using a custom image for the VM? Or are you using an image directly from the marketplace?

**Comment by aymond** [comment]
@OnAzureCloud9 Custom image. 

Running the OMS Agent deploy script with Purge option, and then using the portal to onboard the VM is working. 

Additionally, we have a policy that attempts to deploy the OMS Agent.

**Comment by OnAzureCloud9** [comment]
@aymond That's interesting. Same situation here where I am using a custom image and the policy that attempts to install OMS agent.

I haven't tested this out yet but I believe the issue I was running into may be because of the policy that automatically deployed the OMS Agent to applicable VMs in the subscription. I noticed that when looking at the VMSS instances not able to install extension due to error 52 (marker file) there was already an installation of the OMS agent on the machine and it was pointing to the default workspace. This I believe is because of the Azure policy. 

In my custom image VHD I removed all references to OMS agent so it would be configured post deployment. In this case, I still had the same results where it appeared there was an agent configuration pointing to the default workspace. I think maybe the Azure policy works very fast and is installing the OMS agent (per policy) to point to the default workspace before my deployment can run the extension to point to my (non-default) specified workspace. Then when my custom OMS Agent extension configuration is ran, a conflict arises because there is already an OMS agent installation on the machine.

This is interesting because from my understanding the entire point of the "marker file" is to support multi-homing, which should allow for a VM to point to multiple workspaces. However, all documentation I've seen states Linux OMS Agent does not support multi-homing yet like Windows does.

To resolved this issue on my custom image, I installed the OMS agents pointing to my desired workspace as part of the custom VHD image itself. This was not desired at all since it makes it difficult to use that same image if I want to deploy it multiple times and point to different workspaces. That's the whole point in using the extension post-deployment so the OMS config isn't included in the image definition. Anyways, after including the OMS agent installation as part of my VHD image I stopped receiving this error. However, that doesn't really solve the underlying issue here. I think it may be related to the Azure policy installation OMS agent and creating a conflict of some sorts.

**Comment by getvivekv** [comment]
We just got this error. I deployed this extension using terraform but then removed it using terraform. When trying to re-install it that is when the new installations are failing.

**Comment by sachinpanwar** [comment]
Can you please try and check free disk space for /var, /opt and /etc using below command? 

`df -h`

It should be more than 500 MB for each.

**Comment by awalford16** [comment]
Hi, is there any update on this issue? I am seeing the same issue after installing the extension with Terraform and attempting to run `az vmss update-instances`

**Comment by diego7marques** [comment]
Any news about it? 

I had the same issue here, but using Azure CLI to install the extension.

It seems to have the same scenario: VMSS with Custom VHD image. 

The CLI command:

`az vmss extension set \
--resource-group <resource_group> \
--vmss-name <vmss_name>\
--name OmsAgentForLinux \
--publisher Microsoft.EnterpriseCloud.Monitoring \
--protected-settings {\"workspaceKey\":\"<workspace_key>\"} \
--settings {\"workspaceId\":\"<workspace_id>\"} \
--subscription <subscription_id>`

**Comment by smm190** [comment]
Any news on this @simathih? I am also having this issue.

**Comment by mykolaichuk** [comment]
The workaround in my case was really weird. Initially, I tried to install the agent from the portal by enabling Change Tracking, but I've got the "To connect the VM to the workspace specified in the extension schema, set stopOnMultipleConnections to false in public settings or remove this property. This VM gets billed once for each workspace it is connected to." error. Then I tried to install it with PowerShell 


```
#replace 123 with your values
$sub = Set-AzContext "123"
$rg = "123"
$vm = Get-AzVM -ResourceGroupName $rg -Name "123"
$PublicSettings = @{"workspaceId" = "123";"stopOnMultipleConnections" = $false}
$ProtectedSettings = @{"workspaceKey" = "123"}

Set-AzVMExtension -ExtensionName "OmsAgentForLinux" `
    -ResourceGroupName $VM.ResourceGroupName `
    -VMName $VM.Name -Publisher "Microsoft.EnterpriseCloud.Monitoring" `
    -ExtensionType "OmsAgentForLinux" `
    -TypeHandlerVersion 1.7 `
    -Settings $PublicSettings `
    -ProtectedSettings $ProtectedSettings `
    -Location $VM.Location
```
    
  And from PowerShell I've got "Enable failed with exit code 52 Couldn't create marker file" eror.
  
 Then I went to the portal, removed OmsAgentForLinux Extension and then enabled Changed Tracking and OmsAgentForLinux was successfully installed.

**Comment by fengjhwa** [comment]
I got the same error by using terraform deploy omsagent, but my scenario not just install new agent.
My VMs already installed omsagent, but we need to send to another log analytics workspace.
After terraform plan, the action of omsagent is `update in-place`, but get the error
Any idea? Or what is the correct steps for changing log analytics workspace for omsagent? Thanks

**Comment by artur-carvalho** [comment]
Do we have any workaround or ideia when this will be resolved?

**Comment by LXBdev** [comment]
I can confirm that removing the extension before installing the current one worked for me. It seems to be an upgrade-issue.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of deprecation, open issues and pull requests will be closed.
