### ISSUE TITLE
Premature failure during execution

### ISSUE THREAD

**Issue by anweiss** [Azure/azure-linux-extensions#113]
As of the most recent merge a few hours ago, #112, I'm noticing that the extension now emits a failure even though the script itself doesn't fail and is simply logging stdout messages.

My output is as follows:

```sh
 "message": "VM has reported a failure when processing extension 'prepNodes'. Error message: \"Command is running...\n---stdout---\nLoaded plugins: langpacks, product-id, rhui-lb, search-disabled-repos\n\n---errout---\n\n\"."
```

**Comment by bingosummer** [comment]
Fixed with #119
