### ISSUE TITLE
Centos 6.3 VMSnapshotLinux 

### ISSUE THREAD

**Issue by aiolfic** [Azure/azure-linux-extensions#120]
Every installation of a new version of the extension causes an hang of waagent on some of my Linux boxes and then an abnormal termination of the backup process.
Alert in message.log:
```
abrt: detected unhandled Python exception in '/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.7.0/main/handle.py'
And after further analysis, reason of the exception:
DiskUtil.py:107:get_device_items:NameError: global name 'CommonVariables' is not defined
```

Diskutil.py at line 107:
```
    106             if(error_msg is not None and error_msg.strip() != ""):
    107                 self.logger.log(msg=str(err),level=CommonVariables.ErrorLevel)
```

ErrorLevel is not defined in CommonVariables.

Changing line 107 into:

```
    107                 self.logger.log(msg=str(err))
```

all seems to work fine and Recovery Service takes a regular backup of the VM (recovery verified).

**Comment by soumyanishan** [comment]
Hi,

We will fix it and publish it in the next release of extension.

Thanks
Soumya

**Comment by ahmetalpbalkan** [comment]
@soumyanishan is this ok to close now?

**Comment by aiolfic** [comment]
Yes, you can!

I apologize for missing a feedback.

Thanks you.

C.

 

Da: Ahmet Alp Balkan [mailto:notifications@github.com] 
Inviato: lunedì 25 luglio 2016 22:28
A: Azure/azure-linux-extensions <azure-linux-extensions@noreply.github.com>
Cc: aiolfic <camillo.aiolfi@newits.it>; Author <author@noreply.github.com>
Oggetto: Re: [Azure/azure-linux-extensions] Centos 6.3 VMSnapshotLinux (#120)

 

@soumyanishan <https://github.com/soumyanishan>  is this ok to close now?
