### ISSUE TITLE
DSCForLinux - version reported doesn't work when installing

### ISSUE THREAD

**Issue by sebastus** [Azure/azure-linux-extensions#122]
Maybe this should be listed at Azure CLI?

> azure vm extension-image list-versions westus Microsoft.OSTCExtensions DSCForLinux

reports version 2.0.0.0.  When you try to install it:

> azure vm extension set <parameters> -o 2.0.0.0, it says typeHandlerVersion is invalid.

You have to use 2.0 as the version.  How should the average user figure this out?

**Comment by boumenot** [comment]
Extensions can be published and managed with more detailed version numbers, e.g. 1.2.3 or 1.2.3.4. Consumers of extension are only allowed to use a major.minor version when specifying an extension.
