### ISSUE TITLE
OMS Agent may stop collecting data if logs contain Unicode chars

### ISSUE THREAD

**Issue by AaronRM** [Azure/azure-linux-extensions#1343]
The check_for_fatal_oms_logs function in watcherutil.py needs to properly handly Unicode chars that may end up in the log file(s) it checks. I think the fix involves opening the log file in binary mode ("rb") for the hash instead of text mode ("r").

2021/04/13 01:17:42 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.35] Caught an exception Traceback (most recent call last):
2021/04/13 01:17:42 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.35/watcherutil.py", line 455, in check_for_fatal_oms_logs
2021/04/13 01:17:42 ERROR:    crc = hashlib.sha256(text).hexdigest()
2021/04/13 01:17:42 ERROR:**TypeError: Unicode-objects must be encoded before hashing**

(See internal incident 236781960 for more details.)

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of deprecation, open issues and pull requests will be closed.
