### ISSUE TITLE
LAD should report proper extension version

### ISSUE THREAD

**Issue by LiweiPeng** [Azure/azure-linux-extensions#140]
In a VM I deployed on 5/23/2016 Ubuntu 14.04 (5/17/2016 release), with waagent 2.0.16 and LinuxDiagnostics (LAD) 2.3.9, I found misleading version information in the LAD extension.log file. see details below.

- What's in the log: the version is "1.0" in HandlerEnvironment.json, and HanderManifest.json.
- What's expected from a user point of view: as a user of LAD, when looking at extension.log, I am expecting to see something like "Microsoft.OSTCExtensions.LinuxDiagnostic-2.3" or "Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9" because that's the version I am using.

Log file:
 2016/05/23 17:31:28 [Microsoft.OSTCExtensions.LinuxDiagnostic-1.0]sequence number is 0
 2016/05/23 17:31:28 [Microsoft.OSTCExtensions.LinuxDiagnostic-1.0]setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnos
 tic-2.3.9/config/0.settings2

Related files:
  HandlerEnvironment.json
 [{ "name": "Microsoft.OSTCExtensions.LinuxDiagnostic", "seqNo": "0", "version": 1.0, …

 HandlerManifest.json
 [{
 "name": "LinuxAzureDiagnostic",
 "version": 1.0,

> azure vm extension list -n LinuxDiagnostic
...
Version : 2.3

**Comment by hosungsmsft** [comment]
Looked at this again, and confirmed that this is a waagent issue. The HandlerEnvironment.json is created by waagent, and the version number (1.0) is hard-coded there. LAD just reads HandlerEnvironment.json and use the retrieved version number in logging prefix.

HandlerManifest.json is read by waagent, but apparently, the version in HandlerManifest.json is not the version written to the HandlerEnvironment.json. Will still try to update in the future.

Closing this issue as such, and will reactivate the original issue on waagent repo. I also have a fix, and start a PR there as well. Thanks.

**Comment by hosungsmsft** [comment]
Same as #143. Will try a fix on LAD's Utils code first.

**Comment by hosungsmsft** [comment]
#148 fixes this, and it's merged, so closing this.
