### ISSUE TITLE
Custom Script Extension - Cannot transfer parameters to commandtoexecute

### ISSUE THREAD

**Issue by Yanivro** [Azure/azure-linux-extensions#141]
I'm trying to add a few variables to a script im running 

sh script.sh var1 var2 var3 

But when I try to do it in this manner:

```json
"resources" : [
  {
     "type" : "Microsoft.Compute/virtualMachines/extensions",
     "name" : "[concat(parameters('vmName'),'/CustomScriptExtension')]",
     "apiVersion" : "[variables('apiVersion')]",
     "location" : "[variables('location')]",
     "dependsOn" : [
        "[concat('Microsoft.Compute/virtualMachines/', parameters('vmName'))]"
     ],
     "properties" : {
        "publisher" : "Microsoft.OSTCExtensions",
        "type" : "CustomScriptForLinux",
        "typeHandlerVersion" : "1.4",
        "autoUpgradeMinorVersion" : true,
        "settings" : {
           "fileUris" : "[split(parameters('fileUris'), ' ')]",
           "commandToExecute" : "[concat('sh ',parameters('scriptName'),' ',parameters('var1 '),' ',parameters('var2'),' ',parameters('var3'))]"
        },
        "protectedSettings" : {
           "storageAccountName" : "[parameters('customScriptStorageAccountName')]",
           "storageAccountKey" : "[parameters('customScriptStorageAccountKey')]"
        }
```

I get the following error:

```text
2016/05/25 12:16:11 ERROR:[Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Failed to launch command with error: [Errno 36] File name too long,stacktrace: Traceback (most recent call last):
2016/05/25 12:16:11 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0/Utils/ScriptUtil.py", line 49, in run_command
2016/05/25 12:16:11 ERROR:    stderr=err_out)
2016/05/25 12:16:11 ERROR:  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
2016/05/25 12:16:11 ERROR:    errread, errwrite)
2016/05/25 12:16:11 ERROR:  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
2016/05/25 12:16:11 ERROR:    raise child_exception
2016/05/25 12:16:11 ERROR:OSError: [Errno 36] File name too long
2016/05/25 12:16:11 ERROR:
2016/05/25 12:16:11 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Daemon,failed,1,Lanch command failed: [Errno 36] File name too long
```

It seems that the script is being run as a subprocess and II cannot add variables to it.

Any thoughts?

**Comment by boumenot** [comment]
I reformatted your post because I had a hard time following it.

From the snippet you included there's nothing that I can see that's wrong with executing a command by passing parameters.

The biggest issue is the error **File name too long**.  Have you investigated this?

**Comment by Yanivro** [comment]
Thank you, and this what I'm trying to understand. When I write out the command without using parameters like "sh script.sh var1 var2 var3", it works fine.
That's the only thing that changes in my template.

The error seems to be related to this - http://stackoverflow.com/questions/29747108/subprocess-in-python-file-name-too-long

It seems that the custom script is being run as a subcommand in a python script and the shell=true flag is not mentioned?

**Comment by boumenot** [comment]
You are correct, the script is being executed using subcommand.  I have to look at the shell=True better to understand what the ramifications are.

There should be a log message with "Command to execute:" that will show the command being executed.  This isn't in your output - can you please include it?  I don't remember if it's in /var/log/waagent.log, or under /var/lib/azure in the custom script directory.

Would you please send a gist with your full ARM template?

**Comment by bingosummer** [comment]
The extension is in the directory `/var/log/azure/`.

**Comment by Yanivro** [comment]
<script src="https://gist.github.com/Yanivro/4ab8d76035eb9392ff01b0879b24c0d1.js"></script>

**Comment by Yanivro** [comment]
[Template Gist](https://gist.github.com/Yanivro/4ab8d76035eb9392ff01b0879b24c0d1)

**Comment by boumenot** [comment]
Thank you!

I think the issue is that you forgot **concat**.  The example you posted originally has concat, but your logs and actual template do not.

### Logs
```text
Command to execute:[('sh ',parameters('scriptName'),' ',parameters('scriptParamDataCenter'),' ',parameters('scriptParamSQLServer'),' ',parameters('scriptParamCustomerId'),' ',parameters('scriptParamCustomerDBSQLServer'),' ',parameters('scriptParamCustomerStorageName'),' ',parameters('scriptParamCustomerStorageKey'),' ',parameters('scriptParamCustomerSubDomain')]
```

### Template
> Why are you embedding "\r\n" in your variable?
```text
      "commandToExecute" : "[('sh ',parameters('scriptName'),' ',parameters('scriptParamDataCenter'),' ',parameters('scriptParamSQLServer'),' ',parameters('scriptParamCustomerId'),' ',parameters('scriptParamCustomerDBSQLServer'),' ',parameters('scriptParamCustomerStorageName'),' ',parameters('scriptParamCustomerStorageKey'),' ',parameters('scriptParamCustomerSubDomain')]\r\n" 
```

**Comment by Yanivro** [comment]
I didn't forget concat, I just tried it with and without it(this is the one without it) it made no difference.
And I did not embed \r\n, it probably does this automatically.

**Comment by boumenot** [comment]
This example does not have concat, which is needed.  The gist as "\r\n" inside the quotes, so I'm not sure how it got there.  I think the logs show a unnecessary new line, which makes me think it went all the way through.

Would you please share the logs for a concat example.

**Comment by Yanivro** [comment]
I will run it with again and get the new logs. Thank you.

**Comment by Yanivro** [comment]
Closing this  - It seems the JSON editor tool I was using was adding the "\r\n" for some reason and that caused the issue - thanks for the keen eye and help!

**Comment by boumenot** [comment]
w00t! Glad you are up and running!
