### ISSUE TITLE
OmsAgentForLinuxstill installing old vulnerable versions of scx/omi

### ISSUE THREAD

**Issue by Klaas-** [Azure/azure-linux-extensions#1419]
Hi,
it seems the OmsAgentForLinux extension still installs old scx/omi versions by default on rhel8:
scx-1.6.4-7.x86_64
omi-1.6.8-0.x86_64

you should fix this to use the current packages because of the critical security vulnerabilities in those packages.

Greetings
Klaas

**Comment by Poil** [comment]
Same on all distrib :/

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of deprecation, open issues and pull requests will be closed.
