### ISSUE TITLE
Add support for regex filtering to fileCfg in Diagnostics

### ISSUE THREAD

**Issue by wyldbill** [Azure/azure-linux-extensions#144]
As per SCX_Logfile as defined [here](https://scx.codeplex.com/wikipage?title=xplatproviders)
The implementation should allow multiple shippers from the same file w/ different regex/table destinations if possible.

**Comment by hosungsmsft** [comment]
Thanks @wyldbill for your feedback and sorry for our late response. We'll look into the feasibility of this after releasing our next LAD extension. Our preliminary understanding at this point is that this won't be straightforward, as our "fileCfg" feature currently depends on rsyslog's imfile module, and rsyslog versions prior 8.5 don't support even wild card in the file names. We'll look into this anyway and respond further later. Thanks.

**Comment by abhijeetgaiha** [comment]
LAD 2.3 is deprecated. Adding support for wildcards/folders in LAD 3.0 is tracked in #392
