### ISSUE TITLE
README latest versions go out of date easily

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-linux-extensions#145]
It's probably not a good idea to list a latest version in the README:

1. the information goes out-of-date very easily
2. a version number like `1.5.2.0` cannot be used in ARM templates or CLI. API allows only `major.minor` precision. so it's almost useless.

therefore I suggest listing versions  only in Changelog for information purposes.

> ![image](https://cloud.githubusercontent.com/assets/159209/15558340/283d0bce-228e-11e6-8056-04deabb721d7.png)

**Comment by boumenot** [comment]
This issue appears to override #147.  What would you like?

**Comment by ahmetalpbalkan** [comment]
@boumenot this is more broad (for extensions other than CSE)
