### ISSUE TITLE
OMS Possibly Reverts OMI package back from 1.6.8.1 to 1.6.4 on Azure VM

### ISSUE THREAD

**Issue by amrsharaf** [Azure/azure-linux-extensions#1450]
I've updated the OMI (Open Management Infrastructure) package on my azure VM from 1.6.4 to 1.6.8.1 to mitigate the reported security vulnerability with:

`sudo apt-get install omi`

However, few days after the install I notice that the OMI version gets reverted back to 1.6.4, I'm not sure why that happens and how to debug this issue, any idea what could be going on? 

I've been directed by the [OMI team](https://github.com/microsoft/omi/issues/711) to open a ticket here since this could be related to OMS.

Thanks!

**Comment by amrsharaf** [comment]
Any updates on this issue? Thanks for looking into this.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of deprecation, open issues and pull requests will be closed.
