### ISSUE TITLE
Default option for logs too broad

### ISSUE THREAD

**Issue by nizarq** [Azure/azure-linux-extensions#156]
I’ve recently been playing with the Azure containers service. I noticed that the linux machines that are provisioned as part of the cluster all have “LinuxDiagnostic” extension enabled. I also noticed that a diagnostics storage account is provisioned for each virtual machine. Sifting through what’s inside the storage account I realized, besides metrics, all sys log entries are being sent which can really pile up very quickly. 

From a customer’s perspective, given that they were not notified of the following at the time of provisioning the cluster, spending a bunch on storage might come as a surprise when they get their next bill:
-	Monitoring is being enabled on all machines. 
-	Storage accounts were created for all machines. 
-	Very verbose data is being send. As an example one of my machine in the cluster zero application workload, is generating tens of information or lower syslog message per second.

While I understand the utility of enabling default diagnostics experiences for the customer. I believe we can have smarter defaults which end up not sending as much data (say only send severity levels 0-3 or Emergency, Alert, Critical and Error) by default.

As an example, on windows machines, windows azure diagnostics has better defaults where it only sends error level windows events to storage by default.

**Comment by amansdhanjal** [comment]
Hi Nizarq,

We will work on reducing the noise in diagnostics information. You can track the issue [here](https://github.com/anhowe/scratch/issues/7).

Thanks,
Amandeep

**Comment by ahmetalpbalkan** [comment]
Closing as not directly related to the extensions.
