### ISSUE TITLE
Linux AzureMonitorAgent uses non-existent "os.makedir()" API (should be makedirs)

### ISSUE THREAD

**Issue by MattGal** [Azure/azure-linux-extensions#1738]
At least two instances of this, found trawling through Linux AMA logs looking for other failures:

  https://github.com/Azure/azure-linux-extensions/blob/master/AzureMonitorAgent/agent.py#L1263
  https://github.com/Azure/azure-linux-extensions/blob/master/AzureMonitorAgent/agent.py#L1301

Looks like the code in question was introduced last month by https://github.com/Azure/azure-linux-extensions/pull/1688/files

**Comment by simathih** [comment]
originally introduced here https://github.com/Azure/azure-linux-extensions/pull/1688/files

**Comment by NarineM** [comment]
PR that fixes the issue: https://github.com/Azure/azure-linux-extensions/pull/1739

**Comment by NarineM** [comment]
Fix will be released with AMA versions >= 1.27.2.
