### ISSUE TITLE
Add entropy metrics to AzureEnhancedMonitor

### ISSUE THREAD

**Issue by smereczynski** [Azure/azure-linux-extensions#18]
Entropy metrics is available in /proc/sys/kernel/random/entropy_avail. It is a int number so it is very easy to implement. It is very important in some cases and monitoring software like Zabbix or Icinga is capable to monitor this parameter. I think that I'm able to implement it in https://github.com/Azure/azure-linux-extensions/blob/master/AzureEnhancedMonitor/ext/aem.py but I'm not sure if I have enough skills to implement new table for this metrics and portal related things. I can help in implementing this feature.

**Comment by yuezh** [comment]
hi, @smereczynski. We could implement this.
However, AzureEnhancedMonitor is a tool to pull azure performance counters from different sources into the VM. It will then write the perf counters into a local file. I'm not sure whether this could satisfy your requirement, Maybe you are looking for 
https://azure.microsoft.com/blog/2015/06/09/azure-linux-vm-infrastructure-monitoring-and-diagnostics-2/

**Comment by smereczynski** [comment]
You are right. Thank You very much!
