### ISSUE TITLE
[CustomScript] Include #!/usr/bin/env python26 in the installation script

### ISSUE THREAD

**Issue by jangelfdez** [Azure/azure-linux-extensions#183]
Hi!

CustomScript extension requires Python 2.6 to work. However, if you upload a custom vhd that requires Python 2.4 as default version, it would not work properly although Python 2.6 is already installed on the VM.

It is possible to change it to #!/usr/bin/env python26 ?

Regards

**Comment by ahmetalpbalkan** [comment]
@jangelfdez I'm on a centos7.1 box right now and `/usr/bin/env python26 ` does not exist. there's only `python` `python2` `python2.7` in my PATH. If we go to 2.x-level detailing and if there are mixed python2.x versions out there among all supported images, we'll have some hard time.

**Comment by jangelfdez** [comment]
True... if you don't have Python 2.6 and have a higher version it would not work. 

Do you have any idea about can it be solved?

**Comment by jangelfdez** [comment]
I just had one. Set Python 2.6 as default in the custom image and at the end of the script change it back to 2.4.

I would try it!

**Comment by ahmetalpbalkan** [comment]
@jangelfdez ideally all the extensions should be able to run in a contained environment (maybe even should ship whatever runtime they need with the extension package) however that's not the case today. Extensions such as DockerExtension ship a statically compiled Go binary and we're trying to move in that direction.

As a short-term solution I suggest you to use the CustomData field on the VM properties to run a startup script (I'm assuming that is why you need the CustomScriptExtension in the first place). If that does not solve your problem, please let us know.

**Comment by jangelfdez** [comment]
Thanks @ahmetalpbalkan , it has been solved :)
