### ISSUE TITLE
OMS Agent resets the mode of /var/log/azure

### ISSUE THREAD

**Issue by narrieta** [Azure/azure-linux-extensions#1848]
The OMS Agent is resetting the mode of /var/log/azure every time it is executed: https://github.com/Azure/azure-linux-extensions/blob/master/OmsAgent/omsagent.py#L182

This directory is shared by all VM extensions and individual extensions should not change its properties. This is affecting customers that have set a specific mode on the directory and it get reset every time extensions execute if OMS has been installed.

**Comment by NarineM** [comment]
See linked PR. The fix was checked in.
