### ISSUE TITLE
[CustomScript] determining files to +x is a bit weird

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-linux-extensions#200]
CustomScript makes downloaded files 0100/--x------ if the filename (last segment of the URL path) exists in `commandToExecute`. 

so if you have a configuration like:

```
{
  "commandToExecute": "lsb_release -a",
  "fileUris": [
    "https://gist.github.com/ahmetalpbalkan/../raw/../a",
    "https://gist.github.com/ahmetalpbalkan/../raw/../a.txt",
    "https://gist.github.com/ahmetalpbalkan/../raw/../b"
  ]
}
```

the files `a` and `b` will be 0100 because `'a' in 'lsb_release -a' == True` and `'b' in 'lsb_release -a' == True`.

This smart(❗) +x logic was added, because users can do `commandToExecute: "./script.sh"`. In that case we'd `chmod +x script.sh` but what if `script.sh` calls `./another.sh`, that wouldn't be +x.

**Proposal 1:** Let's chmod +x all files we download via `"fileUris"` .They are user-specified files and executed by the extension process (runs as `root`) only anyway.

**Proposal 2:** While we're at it maybe we can make files readable as well (0500/r-x------)?

cc: @boumenot @mbearup

**Comment by boumenot** [comment]
I do not see the harm in marking all of them as executable.  It is odd for a .txt file to be so, but we are executing **arbitrary** scripts, and people can do strange things.  Especially, if they are coming from Windows to Linux.

I don't see why they wouldn't be readable.  This seems like an oversight.  Please make them readable too.

**Comment by ahmetalpbalkan** [comment]
This is fixed in the rewrite. We u+rx everything we download now.
