### ISSUE TITLE
[LinuxAzureDiagnostic] Custom Metrics

### ISSUE THREAD

**Issue by bchobanov** [Azure/azure-linux-extensions#205]
Hello,

With previous versions of the Diagnostic, it was possible to monitor and alert for % free disk space.
I've gone through a whole bunch of blog posts and articles on the matter, and not one suggests a way to do that. Where does the mdsd service store the data it gathers from rsyslog?
In the file /var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007/xmlCfg.xml, there are several queries for cpu, memory, disk. What should OMIQuery section in the xml config file contain for PercentFreeSpace, PercentUsedSpace from SCX_FileSystemStatisticalInformation? What data store is the query made against (it's not the azure table storage)? 
My ultimate goal is to create alerts in Azure for disk space utilization on a Linux VM. And at best, create the disk space metric through an API call.

I appreciate any help/assistance/links/documentation on the matter.

Thank you!

**Comment by hosungsmsft** [comment]
@bchobanov - Thanks for your interest in LAD (Linux Azure Diagnostic) and inquiries. I'll try to answer your questions briefly here, and I'd like to ask you to contact me directly at hoson@microsoft.com for any further details.

It looks like you already checked out the [System Center Cross Platform Solutions document](https://scx.codeplex.com/wikipage?title=xplatproviders) through [our Azure Doc article](https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-classic-diagnostic-extension/), so I won't repeat them here again. I believe the OMI query to retrieve the counters you desire would be something like the following:

``SELECT Name, FreeMegabytes, PercentFreeSpace FROM SCX_FileSystemStatisticalInformation``

This query statement needs to be ultimately placed in xmlCfg.xml you mentioned, but it also all depends on how you enabled/configured LAD in the first place. In summary, it is NOT desired to directly manipulate the xmlCfg.xml for any additional counters, especially if you enable LAD from Azure Portal for Portal diagnostic. In that case, in fact, LAD currently doesn't support well adding any new metrics.

If you have enabled/configure LAD using CLI based on [our GitHub README.md](https://github.com/Azure/azure-linux-extensions/tree/master/Diagnostic), then you can easily add the above OMI query in the ``perfCfg`` section in the public configuration. You'll be specifying the name of the Azure storage table where the free disk space metrics will be stored. If it's still unclear to you, please feel free to email me directly again.

The data store the OMI queries are made against is the OMI daemon on the VM. mdsd makes those queries to the OMI daemon and stores the retrieved metrics to the specified Azure storage account table.

Hope this helps, and please do not hesitate contacting me directly at hoson@microsoft.com. Also please consider closing this issue if you think answers here or the following course of action are satisfactory to you.

Thanks,
Hosung
