### ISSUE TITLE
[VMAccess] Typo in debian sshd_config restoration file name

### ISSUE THREAD

**Issue by CraigWiand** [Azure/azure-linux-extensions#207]
[debian_dufault](https://github.com/Azure/azure-linux-extensions/blob/master/VMAccess/resources/debian_dufault) should be **debian_default**.  Right now debian_dufault appears to be identical to [default](https://github.com/Azure/azure-linux-extensions/blob/master/VMAccess/resources/default) except for comments so impact is minimal, but unexpected results will occur if they diverge in the future.

**Comment by boumenot** [comment]
Fixed by #208
