### ISSUE TITLE
[CustomScript] extension blocks deployment when using bare command line

### ISSUE THREAD

**Issue by rcarmo** [Azure/azure-linux-extensions#215]
I've been trying to get this extension to do the simplest thing that could possibly work, which is to run a single command line upon provisioning:

```json
        "settings": {
          "commandToExecute": "sudo apt-get -y update && sudo apt-get -y dist-upgrade"
        }
```

But whenever I try to do this, my deployments never finish - the extension is created, its provisioning state is set to "running", but I don't get any debug output when looking at the properties blade for the extension on the machine it's provisioned for.

Looking at the code, I believe it is blowing up at:

a) [Line 192](https://github.com/Azure/azure-linux-extensions/blob/master/CustomScript/customscript.py#L192), where blob_uris is tested for lack of content, even though the documentation states that the `fileUris`array is optional. This because [Line 179](https://github.com/Azure/azure-linux-extensions/blob/master/CustomScript/customscript.py#L179) would seem to return `None` in case the setting is missing.

b) [Line 278](https://github.com/Azure/azure-linux-extensions/blob/master/CustomScript/customscript.py#L278) and following, given that the command line might be mangled by `parse_args` - which goes against expectations for a Linux sysadmin.

In short, the extension should cover the case of running a bare command line (I would also vastly prefer to be able to inline a full script rather than having to manage access to a storage account, but I'll file issue #216 for that).

For completion, here's the relevant resource in the ARM template I'm using:

```json
    {
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "copy": {
        "name": "rancher-master-provisioning-loop",
        "count": "[parameters('masterCount')]"
      },
      "name": "[concat(parameters('virtualMachineNameMaster'), copyIndex(), '/updatePackages')]",
      "apiVersion": "2015-06-15",
      "location": "[resourceGroup().location]",
      "properties": {
        "publisher": "Microsoft.OSTCExtensions",
        "type": "CustomScriptForLinux",
        "typeHandlerVersion": "1.5",
        "autoUpgradeMinorVersion": true,
        "settings": {
          "commandToExecute": "sh sudo apt-get -y update && sudo apt-get -y dist-upgrade"
        }
      },
      "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachines/', parameters('virtualMachineNameMaster'), copyIndex())]"
      ]
    },
```

**Comment by boumenot** [comment]
We'll need logs to better understand your issue.  The ability to sudo without entering a password is not viable for all distros.  What do the logs show the command is executing?

**Comment by rcarmo** [comment]
Like I mentioned, nothing shows up on the portal logs.

**Comment by rcarmo** [comment]
I just tried it again, with `"sh whoami"` as `commandToExecute`. The ARM deployment is stuck, and clicking on the Extensions option on the VM properties blade gives me this:

```
Type Microsoft.OSTCExtensions.CustomScriptForLinux
Version 1.*
Status (unavailable)
Status level (unavailable)
Status message (unavailable)
Handler status Not Ready
Handler status level Info
```

**Comment by rcarmo** [comment]
As a little more follow-up, I went into the machine and established that it is executing the command, but that it does not honor `$PATH`. The extension is still blocking deployment for some reason, since regardless of whether or not the script actually works the ARM deployment should continue:

```bash
root@rancher-master0:~# cat /var/log/azure/Microsoft.OSTCExtensions.CustomScriptForLinux/1.5.2.0/CommandExecution.log
2016/08/04 09:18:23.537351 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0] Expected handler state: enabled
2016/08/04 09:18:23.539338 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0] Decide which version to use
2016/08/04 09:18:23.598958 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0] Use version: 1.5.2.0
2016/08/04 09:18:23.601708 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0] Current handler state is: NotInstalled
2016/08/04 09:18:23.603730 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0] Download extension package
2016/08/04 09:18:25.910002 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0] Unpack extension package
2016/08/04 09:18:25.938203 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0] Initialize extension directory
2016/08/04 09:18:25.941394 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0] Update settings file: 0.settings
2016/08/04 09:18:25.942418 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0] Install extension.
2016/08/04 09:18:25.944591 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0] Launch command:customscript.py -install
2016/08/04 09:18:26.516575 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0] Enable extension.
2016/08/04 09:18:26.517868 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0] Launch command:customscript.py -enable
root@rancher-master0:~# cat /var/log/azure/Microsoft.OSTCExtensions.CustomScriptForLinux/1.5.2.0/extension.log
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]sequence number is 0
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0/config/0.settings
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]JSON config: {"runtimeSettings": [{"handlerSettings": {"publicSettings": {"commandToExecute": "sh whoami"}, "protectedSettingsCertThumbprint": null, "protectedSettings": null}}]}
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Install,success,0,Install succeeded
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]sequence number is 0
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0/config/0.settings
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]JSON config: {"runtimeSettings": [{"handlerSettings": {"publicSettings": {"commandToExecute": "sh whoami"}, "protectedSettingsCertThumbprint": null, "protectedSettings": null}}]}
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]set most recent sequence number to 0
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Command to execute:sh whoami
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Enable,transitioning,0,Launching the script...
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]sequence number is 0
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0/config/0.settings
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]JSON config: {"runtimeSettings": [{"handlerSettings": {"publicSettings": {"commandToExecute": "sh whoami"}, "protectedSettingsCertThumbprint": null, "protectedSettings": null}}]}
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Will try to download files, number of retries = 10, wait SECONDS between retrievals = 20s
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Command to execute:sh whoami
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]fileUris value provided is empty or invalid. Continue with executing command...
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Succeeded to download files, retry count = 0
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Internal DNS is ready, retry count = 0
2016/08/04 09:18:26 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Command to execute:sh whoami
2016/08/04 09:18:27 ERROR:[Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Command returned an error.
2016/08/04 09:18:27 ERROR:---stdout---
2016/08/04 09:18:27 ERROR:
2016/08/04 09:18:27 ERROR:---errout---
2016/08/04 09:18:27 ERROR:sh: 0: Can't open whoami
2016/08/04 09:18:27 ERROR:
2016/08/04 09:18:27 ERROR:
2016/08/04 09:18:27 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Daemon,failed,127,Command returned an error.
2016/08/04 09:18:27 ---stdout---
2016/08/04 09:18:27
2016/08/04 09:18:27 ---errout---
2016/08/04 09:18:27 sh: 0: Can't open whoami
2016/08/04 09:18:27
2016/08/04 09:18:27
root@rancher-master0:~# whoami
root
root@rancher-master0:~# which whoami
/usr/bin/whoami
```

**Comment by rcarmo** [comment]
And as a result of further testing, I've established that setting `commandToExecute` to "command\ncommand" does not work, since the newline is mangled by the extension.

**Comment by boumenot** [comment]
If you want to execute multiple commands you would use && not a '\n'.

```bash
/usr/bin/whoami && /usr/bin/whoami
```

**Comment by boumenot** [comment]
When I said logs, I mean the logs from the disk, not the portal.  Sorry for not being clearer.

Based on this the extension is trying to execute whoami with sh.

```text
8/04 09:18:27 ERROR:---errout---
2016/08/04 09:18:27 ERROR:sh: 0: Can't open whoami
```

This is why PATH does not matter.  sh is trying to find the whoami script, it isn't trying to execute the command whoami.  You have a sh prefix in your original command to.  Would you please remove the sh portion, and try again.

**Comment by jasonzio** [comment]
Alternatively, change your command to ```sh -c whoami```. But there's no point in doing that, really, since the extension is already passing that entire string to a shell for execution.

**Comment by rcarmo** [comment]
@boumenot: You missed the fact that I initially tried to run `apt-get -y update && apt-get -y dost-upgrade` (I also tried it without the sudo). My point that this does not behave like expected still stands - see below as to why.
@jasonzio: I tried that (and several variants of escaping) after examining the extension source code. Since it uses `subprocess.Popen` without `shell=True`, the command line handling is not the same as a regular shell, so that's why `&&` isn't working.
Regardless, I'm still getting hung deployments even when `/usr/bin/whoami` runs successfully - the extension simply does not finish provisioning from the portal's standpoint.

**Comment by boumenot** [comment]
@rcarmo - This is not the way I read your original message.  I read it as here's a small snippet, and then here's a larger snippet.  The snippets do not agree, but I think you are saying they are two distinct examples.

$PATH does not behave that way because you're are invoking a binary with sh.  It would never work this way.

```sh
sh whoami
```

Returns _sh: 0: Can't open whoami_

Would you please share a minimal, but complete repo of the issue, and I will attempt to debug it on my end.  I will do likewise on my end.

**Comment by rcarmo** [comment]
I can’t share the complete template as it contains private information from a customer and I am using the REST API to provision and orchestrate a solution (i.e., no PowerShell, xplat cli or even C# source).  I can, however, attempt to create a minimal sample.

**Comment by boumenot** [comment]
That would be great!  I [posted][1] an example showing how to execute multiple commands.  Let me know if this helps at all.

[1]: https://gist.github.com/boumenot/5be152ed8fac3be06d126f0ad0437b27

**Comment by rcarmo** [comment]
OK, I tried a template deployment via the portal, and your example worked.

There are three different things I can see between our two templates:
1) I am instancing a small set of machines (hence the `copy` attribute)
2) I am setting the `typeHandlerVersion` to 1.5, which appeared to be the correct one (yours says 1.0, but from my understanding of extensions the `autoUpgradeTypeHandlerVersion` is supposed to make the `.0` redundant
3) My template was submitted through the REST API, because I need to generate portions of it on the fly.

I will see if tweaking mine fixes the deployment problem - right now there are two issues here, one being multiple commands (which is best left to #216) and the deployment blocking, which I am still trying to resolve.

**Comment by ahmetalpbalkan** [comment]
Just to provide input here, @rcarmo is right, the current version of CustomScriptExtension uses `shlex.split` which splits `whoami && whoami` into `exec(['whoami', '&&', 'whoami'])` which is clearly invalid.

In this case this is bug(and also by-design) and fileUris should be used for that. 

Easiest workaround is to say `"commandToExecute": "sh -c 'whoami && whoami;'"` (I realized @rcarmo missed the `-c` earlier, the failure listed a few comments above happened due to that).

The new version of the Custom Script Extension (which we have not yet published) at https://github.com/Azure/custom-script-extension-linux always uses `sh -c` to run the specified comment (like `shell=True` in Python subprocess), so this issue will be fixed in the short term.

**Comment by rcarmo** [comment]
@ahmetalpbalkan thanks for that. Saw that repo earlier (I also do Go), hope multi-line scripts as discussed in #216 make their way into the feature set.

Meanwhile, the good news is that I think we can close this as far as the deployment hangup is concerned:

I've tested my template with `typeHandlerVersion` set to `1.0` as @boumenot did in his example, and the deployment worked (with a single `whoami`command, I'm leaving the multi-command stuff to #216, which is where we should probably take the `silex.split` discussion).

Which means there's likely to be a bug in the resource provider (or the extension as currently deployed in production) where it regards checking that version number - with `1.5`, the deployment never finished, but there were also no error messages or command status sent back to the portal, as reported above.

Thanks for all your help, I'll keep hammering at the multi-line aspect in #216 because I think that will be a nice improvement for our customers.
