### ISSUE TITLE
[VMAccess] Issue with CA API Gateway 9.1

### ISSUE THREAD

**Issue by rofans** [Azure/azure-linux-extensions#217]
Hi Team,

I am unable to use the extension for CA API Gateway 9.1 (https://vmdepot.msopentech.com/Vhd/Show?vhdId=64433&version=66674). The guest OS is CentOS 6.7.

Logs are provided below (from WAAgent):

```
2016/08/04 10:16:36 Found Plugin: Microsoft.OSTCExtensions.VMAccessForLinux version: 1.4.1.0
2016/08/04 10:16:36 Found RuntimeSettings for Microsoft.OSTCExtensions.VMAccessForLinux V 1.4.1.0
2016/08/04 10:16:36 Spawned ./vmaccess.py -install PID 32178
2016/08/04 10:16:36 ERROR:Process 32178 returned non-zero exit code(126)
2016/08/04 10:16:36 SetHandlerState: Microsoft.OSTCExtensions.VMAccessForLinux-1.4.1.0, NotInstalled
2016/08/04 10:16:36 ERROR:Installation failed for Microsoft.OSTCExtensions.VMAccessForLinux-1.4.1.0
2016/08/04 10:16:36 Processing completed for Microsoft.OSTCExtensions.VMAccessForLinux-1.4.1.0
```

Observations:
1. Tried to use "Reset password" menu in Azure Portal. Both resetting existing user as well as creating new user. No impact seen on the OS.
2. Tried to use CLI, no error on the prompt but also not working.

```
C:\Users\Rofans>azure vm extension set apigwrofansvm VMAccessForLinux Microsoft.OSTCExtensions 1.* --private-config-path C:\Documents\ENTIIS\Project\SingPost-APIM\Azure\privateConfig.json
info:    Executing command vm extension set
+ Getting virtual machines
+ Updating vm extension
info:    vm extension set command OK
```

Best Regards,
Rofans Manao

**Comment by boumenot** [comment]
We do support CentOS, but we do not support custom images.  We may be able to get you up and running with minimal work though.

I have to determine why this command failed.

```text
2016/08/04 10:16:36 Spawned ./vmaccess.py -install PID 32178
```

Would you please review/attach the extension logs?  What version of Python was used to execute the extension, it should be 2.

**Comment by rofans** [comment]
Hi Chris,

Thanks for your explanation and intention to help out.

The Python is 2 instead of 3. I have checked this before raising the issue.

Anyway, I found out the issues root cause as well as solution. I would like to share it below.

Thanks & Regards,
Rofans Manao

```
Root cause: The "/var" file system is mounted as “noexec”

Resolution:
1. Modify /etc/fstab entry
Run: vi /etc/fstab
Before: rw,nosuid,nodev,noexec,auto,nouser,async,relatime,acl 1 2
After: rw,nosuid,nodev,exec,auto,nouser,async,relatime,acl 1 2

2. Mount /var as exec
mount -o remount,exec /var

3. Reboot the system
#use console menu

Additional step:
1. Modify /etc/ssh/ssh_allowed_users
Add new username below ssgconfig
Example:
ssgconfig
azureuser
2. Create new PPK using PuTTYGen

Test approach:
1. Login to portal.azure.com
2. Find VM
3. Find "Reset password" menu
4. Use "SSH public key"
5. Input username and key string taken from PuTTYGen
6. Use PuTTY to login with the new use
```r

**Comment by boumenot** [comment]
I am glad to hear that, and thank you for circling back with the solution!
