### ISSUE TITLE
[LAD] Log cleartext for keys (not values) seen in protectedSettings

### ISSUE THREAD

**Issue by LiweiPeng** [Azure/azure-linux-extensions#222]
LAD customers from mooncake reports that they have trouble uploading data to portal. It turns out they have some protectedSettings that are not expected. While we shouldn't log the full data for protectedSettings because they are secret, it is valueable to log the 'key' not the value of the settings.

Also, for values that are not secret, they should be logged. e.g. storageEndPoint.

**Comment by hosungsmsft** [comment]
Fixed in the new release.
