### ISSUE TITLE
add/restore support for account expiration in VMAccess extension

### ISSUE THREAD

**Issue by alekiv** [Azure/azure-linux-extensions#229]
For some reason account expiration support not added or removed from VMAccess extension.

vmaccess.py
```
    error_string = waagent.MyDistro.CreateAccount(
        user_name, user_pass, None, None)
```

waagent
```
    def CreateAccount(self,user, password, expiration, thumbprint):
        return CreateAccount(user, password, expiration, thumbprint)
```

Sometimes it is needed to set expiration time for account but with current version it is not possible.
Looks like it was supported before since it is mentioned in [blog about VMAccess Extension](https://azure.microsoft.com/en-us/blog/using-vmaccess-extension-to-reset-login-credentials-for-linux-vm/)

**Comment by boumenot** [comment]
Thank you for the report!  Agreed, this functionality should exist.  I will add support.

I reviewed every revision of vmaccess.py, and I cannot find a single instance where code to use expiration exists.  It appears there was a miscommunication between the implementers and the documenters.
