### ISSUE TITLE
Azure Portal Graphs Issue - Temporary?

### ISSUE THREAD

**Issue by solvingJ** [Azure/azure-linux-extensions#232]
The readme says: 

The new Azure Portal's VM Diagnostic extension status and performance graphs will not work if the Linux Azure Diagnostic extension is configured using one of the methods described in this document. 

Has anyone identified the root cause of this, or even better, is there a resolution already on the roadmap?

**Comment by boumenot** [comment]
Does this answer your question?

@jasonzio responded with an issue in this [comment][1]

[1]: https://github.com/Azure/azure-linux-extensions/issues/219#issuecomment-238396871

**Comment by solvingJ** [comment]
Yes, it does. thank you.

**Comment by jasonzio** [comment]
Dupe #219
