### ISSUE TITLE
[LAD] Check configured storage account for table support during enable processing

### ISSUE THREAD

**Issue by jasonzio** [Azure/azure-linux-extensions#234]
Azure recently added storage accounts that are "blob only", i.e. do not support tables. LAD depends on writing collected data to tables. LAD should check the storage account during enable processing to see if it can use the supplied credentials to create a table, reporting any errors via the status blob. This "fail fast" mechanism will get important error information back to the user (via portal or CLI/PowerShell/template) as quickly as possible.

**Comment by hosungsmsft** [comment]
+1

However, I'm wondering if this should be done in LAD. Trying to create a table on the provided storage account will require Azure Storage Python SDK, which will be problematic. I thought about doing this purely with Azure Storage REST API on Python, but that seems way too much complicated. If it's done in mdsd binary at the configuration validation time, I suppose we could avoid this issue.

**Comment by jasonzio** [comment]
There's very little of the Python SDK we'd need; if we hand-construct the REST API request to enumerate the tables in the storage account, that should be enough. We'd only need to borrow the code to "sign a REST API request", and that can be built by hand if necessary.

**Comment by hosungsmsft** [comment]
The latest mdsd binary will perform this storage account/key validation and return a failure if the validation fails (when run with '-v' option). And LAD already validates xmlCfg.xml using -v, so once the next version of LAD is shipped with the latest mdsd binary, this validation will always happen (and thus fail fast if the specified storage account/key are invalid).
