### ISSUE TITLE
Deprecated value being used in the syslog template

### ISSUE THREAD

**Issue by mabicca** [Azure/azure-linux-extensions#242]
The last parameter in the config file ~ is deprecated and it should be replaced with the word stop, here is an example of that the config file should look like after the change:

$ModLoad omazuremdslegacy.so
$template fmt, "\"syslog\",%syslogfacility-text:::csv%,\"%syslogseverity%\",\"%timereported:::date-rfc3339%\",\"%fromhost-ip%\",#TOJSON#%rawmsg%"
$legacymdsconnections 1
$legacymdsport 29131

$ActionQueueType LinkedList
$ActionQueueDequeueBatchSize 100
$ActionQueueSize 10000
$ActionResumeRetryCount -1
$ActionQueueSaveOnShutdown on
$ActionQueueFileName lad_mdsd_queue
$ActionQueueDiscardSeverity 8
*.*;local6.none :omazuremds:;fmt

$template fmtfile,"\"%syslogtag%\",#TOJSON#%rawmsg%"
$legacymdsconnections 1
$legacymdsport 29131

$ActionQueueType LinkedList
$ActionQueueDequeueBatchSize 100
$ActionQueueSize 10000
$ActionResumeRetryCount -1
$ActionQueueSaveOnShutdown on
$ActionQueueFileName lad_mdsd_queue
$ActionQueueDiscardSeverity 8
local6.* :omazuremds:;fmtfile
& stop

**Comment by hosungsmsft** [comment]
Thanks for letting us know about this. We'll look into this and respond soon.
