### ISSUE TITLE
Connection Issues and Unique $ActionQueueFileName

### ISSUE THREAD

**Issue by mabicca** [Azure/azure-linux-extensions#243]
It seems that we have two configuration blocks in the default file which seem to be causing connection errors at startup and if we are indeed to have two different configuration blocks, the $ActionQueueFileName should be unique, right now it seems that they use the same filename: lad_mdsd_queue.

These are the errors that are seen:
Sep 11 22:56:32 redhat72 rsyslogd-3000: omazuremds error at connect(). errno=Connection refused
Sep 11 22:56:33 redhat72 rsyslogd-3000: omazuremds error at connect(). errno=Connection refused
Sep 11 22:56:34 redhat72 rsyslogd-3000: omazuremds error at connect(). errno=Connection refused

I can reliably reproduce this error across all Linux Endorsed images in Azure.

Can we please confirm if that is the case, the related errors go away when I update the config file to something like this , changes in **bold**:

$ModLoad omazuremdslegacy.so
$template fmt, "\"syslog\",%syslogfacility-text:::csv%,\"%syslogseverity%\",\"%timereported:::date-rfc3339%\",\"%fromhost-ip%\",#TOJSON#%rawmsg%"
$legacymdsconnections 1
$legacymdsport 29131

$ActionQueueType LinkedList
$ActionQueueDequeueBatchSize 100
$ActionQueueSize 10000
$ActionResumeRetryCount -1
$ActionQueueSaveOnShutdown on
**$ActionQueueFileName lad_mdsd_q1**
$ActionQueueDiscardSeverity 8
*.*;local6.none :omazuremds:;fmt

$template fmtfile,"\"%syslogtag%\",#TOJSON#%rawmsg%"
$legacymdsconnections 1
$legacymdsport 29131

$ActionQueueType LinkedList
$ActionQueueDequeueBatchSize 100
$ActionQueueSize 10000
$ActionResumeRetryCount -1
$ActionQueueSaveOnShutdown on
**$ActionQueueFileName lad_mdsd_q2**
$ActionQueueDiscardSeverity 8
local6.* :omazuremds:;fmtfile
& ~

**Comment by hosungsmsft** [comment]
Thanks for letting us know about this. We have internally discussed about this, but we'll revisit and respond soon. FYI, the "Connection refused" errors you pasted don't seem relevant to this matter, and they could happen temporarily in a transient manner. All in all, we'll look into all of these and proceed. Thanks.

**Comment by mabicca** [comment]
Hi @hosungsmsft thanks for the reply, I can confirm that changing those config files caused the connection errors to go away and in regards of the $ActionQueueFileName, according to rsyslog documentation, they must be unique. Thank you.

**Comment by hosungsmsft** [comment]
Thanks much for your follow up. Glad to know that differentiating the queue file names fixes the issue. We've inherited this configuration from somewhere else, and the queue file names have been always identical, so that's why they are as such now. Could you point us to the rsyslog documentation mentioning that the ActionQueueFileName's should be unique? Once we confirm that, this should be a quick/small change, which anyone can make and request us to merge.

**Comment by mabicca** [comment]
http://www.rsyslog.com/doc/v8-stable/tutorials/reliable_forwarding.html

The “$ActionQueueFileName” is used to create queue files, should need arise. This value must be unique inside rsyslog.conf. No two rules must use the same queue file. Also, for obvious reasons, it must only contain those characters that can be used inside a valid file name. Rsyslog possibly adds some characters in front and/or at the end of that name when it creates files. So that name should not be at the file size name length limit (which should not be a problem these days).

**Comment by hosungsmsft** [comment]
Thanks much for the documentation! We'll be more than happy to make this change, but just wondering if you'd like us to do it, or if you'd like to change it and send a PR to us?

**Comment by mabicca** [comment]
Hi @hosungsmsft I can do that, I'm still trying to see if there are any side effects with this change, I am also going to do some research on the legacymdsport setting too to see if that should be unique as the other parameter. Can I get more details about this connection? Is this the piece that is sending information from the Linux VM to the MDS tables in Azure for diagnostics?

Thanks!

**Comment by hosungsmsft** [comment]
Fixed in the new release.
