### ISSUE TITLE
Linux Diagnostic support Application Insight

### ISSUE THREAD

**Issue by nguyenanhdao** [Azure/azure-linux-extensions#250]
Hi, 

I'm trying to log LinuxDiagnostic (CPU, Memory) to Application Insight. But It doesn't work for me.
This is my configuration
```
<WadCfg>
    <DiagnosticMonitorConfiguration overallQuotaInMB="4096" sinks="ApplicationInsights.MyTopDiagData">
        <DiagnosticInfrastructureLogs />
        <PerformanceCounters>
            <PerformanceCounterConfiguration counterSpecifier="\Processor(_Total)\% Processor Time" sampleRate="PT3M" sinks="ApplicationInsights.MyLogData/>
            <PerformanceCounterConfiguration counterSpecifier="\Memory\Available MBytes" sampleRate="PT3M" />
            <PerformanceCounterConfiguration counterSpecifier="\Web Service(_Total)\Bytes Total/Sec" sampleRate="PT3M" />
        </PerformanceCounters>
        <Logs scheduledTransferPeriod="PT1M" scheduledTransferLogLevelFilter="Verbose" sinks="ApplicationInsights.MyLogData"/>
    </DiagnosticMonitorConfiguration>

    <SinksConfig>
        <Sink name="ApplicationInsights">
            <ApplicationInsights>$appInsightInstrumentationKey</ApplicationInsights>
            <Channels>
                <Channel logLevel="Error" name="MyTopDiagData"  />
                <Channel logLevel="Verbose" name="MyLogData"  />
            </Channels>
        </Sink>
    </SinksConfig>
</WadCfg>
```

CPU and Memory usage has been stored in Storage Account Table...
Does Linux Diagnostic Extension support this feature?

Please help me with this.

Thank you so much

**Comment by hosungsmsft** [comment]
Hi @nguyenanhdao,

As far as we are aware, AppInsights on Azure Linux VMs have to be configured through a JSON config, not using an XML config. I suppose the configuration you used above was for a Windows VM. I'm trying to locate some documentation on how to configure AppInsights on Azure Linux VMs, but I'm having hard time locating it. I'll ask the component dev for an answer. Just FYI, the JSON config for AppInsights on Linux VMs is as follows:

{
    "ladCfg":{
        "diagnosticMonitorConfiguration":{
	        ...
        },
        "sinksConfig":{
            "sinks":[
                { "applicationInsights":"<my-application-insights-key>" }
            ]
        }
    }
}

Again, I'll ask the dev to answer here.

Thanks,
Hosung Song

**Comment by Skantha** [comment]
The configuration Hosung provided is correct. The key has to be provided as the value for the "applicationInsights" field in the json configuration.

**Comment by nguyenanhdao** [comment]
Hi @hosungsmsft, @Skantha,
First of all, thank you so much for helping me.

I've changed my configuration to
```
{  
    "ladCfg":{  
        "diagnosticMonitorConfiguration":{  
            "performanceCounters":{  
                "performanceCounterConfiguration":[  
                    {  
                        "counterSpecifier":"PercentProcessorTime",
                        "class":"Processor",
                        "table":"LinuxCpu1"
                    },
                    {  
                        "counterSpecifier":"PercentIOWaitTime",
                        "class":"Processor",
                        "table":"LinuxCpu2",
                        "condition":"Name=\'_TOTAL\'"
                    },
                    {  
                        "counterSpecifier":"AverageWriteTime",
                        "class":"PhysicalDisk",
                        "table":"LinuxDisk",
                        "condition":"Name=\'_TOTAL\'"
                    }
                ]
            }
        }
   },
   "sinksConfig":{  
      "sinks":[  
         {  
            "applicationInsights":"$appInsightInstrumentationKey"
         }
      ]
   }
}
```

But It gives me error `"Failed to get status file [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9009/status/1.status'".`

Would you mind taking a look?

Thank you

**Comment by jasonzio** [comment]
You can't do shell variable substitution, or environment variable substitution, in the JSON config file. The actual App Insights key must be inserted there.

We recognized that a user might be uncomfortable putting their AppInsights credentials in the public config.  A forthcoming update to the Linux Diagnostics Extension will allow you to specify the AppInsights key in the Private Config JSON for the extension and simply reference it from the public config. In the meantime, though, you have to specify it as indicated.

**Comment by nguyenanhdao** [comment]
Hi,

I created this configuration through PowerShell script. So PowerShell will inject AppInsight instrumentation key to it. After using this configuration, setup Linux Diagnostic keeps waitting forever.

Anyway, I think I should wait for this ticket: https://github.com/Azure/azure-linux-extensions/issues/219#issuecomment-238396871

I will close this.

Thank for supporting me.
