### ISSUE TITLE
set-azureRMVMextension command does not execute correctly

### ISSUE THREAD

**Issue by saimsh** [Azure/azure-linux-extensions#251]
I have a customer who is experiencing the issue while executing custom script extension via powershell. 
I tried testing it using the following cmdlets :

$timestamp = Get-Date
echo $timestamp

$rg="centos65rg"
$vm="sscentos65"
$loc="CentralUS"
$user="saimsh"
$pass="Louisiana007"
$settings = @{"fileUris" = "[]"; "commandToExecute"= " sh -c 'echo '$user':'$pass'|chpasswd\'"; "timestamp" = "$timestamp" };

#$settings = @{"fileUris" = "[]"; "commandToExecute"= " sh -c 'echo azureadmin:M1cros0ftazure|chpasswd\'"; "timestamp" = "$timestamp" };
Set-AzureRmVMExtension -ResourceGroupName $rg -VMName $vm -Name "CustomScriptForLinux" -Publisher "Microsoft.OSTCExtensions" -TypeHandlerVersion "1.5.2.1" -ExtensionType "CustomScriptForLinux" -Location $loc -Settings $settings

ERROR:
Set-AzureRmVMExtension : The value of parameter typeHandlerVersion is invalid.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : '11213a2e-27de-4096-8319-4dba88cf8cf5'
At line:12 char:1

Set-AzureRmVMExtension -ResourceGroupName $rg -VMName $vm -Name "Cust ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : CloseError: (:) [Set-AzureRmVMExtension], ComputeCloudException
FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.SetAzureVMExtensionCommand
NOte: I have already tried the following variations:
-Name CustomScriptExtension
-ExtensionType CustomScriptExtension

TypeHandlerVersion 1.5.2.1
I encounter the same errors as described above. Please let me know if i am missing something here.

The above description were related to my tests. However, My customer is using the new "customscriptextension" and is unable to execute it from powershell. In an effort to test the new extension, the following were my tests and error outputs:
PS C:\Users\saimsh> $timestamp = Get-Date
echo $timestamp

$rg="centos65rg"
$vm="sscentos65"
$loc="CentralUS"
$user="saimsh"
$pass="Louisiana007"
$settings = @{"fileUris" = "[]"; "commandToExecute"= " sh -c 'echo '$user':'$pass'|chpasswd\'"; "timestamp" = "$timestamp" };


Set-AzureRmVMCustomScriptExtension -ResourceGroupName $rg -VMName $vm -Name "CustomScriptExtension" -TypeHandlerVersion 1.* -DisableAutoUpgradeMinorVersion -Location $loc -Settings $settings


Tuesday, September 20, 2016 9:51:44 AM
Set-AzureRmVMCustomScriptExtension : A parameter cannot be found that matches parameter name 'Settings'.
At line:12 char:172
+ ...  1.* -DisableAutoUpgradeMinorVersion -Location $loc -Settings $settin ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-AzureRmVMCustomScriptExtension], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.Compute.SetAzureVMCustomScriptExtensionCommand


Please let me know the correct method to execute the new extension.

**Comment by ahmetalpbalkan** [comment]
1. the API will not you specify a version more detailed than `[major].[minor]` format
2. `1.*` syntax is not allowed in ARM mode, you can just use `1.5` and the API will pick the highest version when you use it via PowerShell.
3. `CustomScriptExtension` is for Windows; not Linux. Try `azure vm extension-image list` and you'll see it's for Windows.

Also consider using `Microsoft.Azure.Extensions` `CustomScript`  v`2.0` https://github.com/Azure/custom-script-extension-linux

**Comment by saimsh** [comment]
Thank you for all the insights ahmet. this really helps. ALso, i will go ahead and test the new extension and create a doc accordigly for our other support folks. cheers!!
