### ISSUE TITLE
[DSC For Linux] Expose configuration name with register method

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-linux-extensions#260]
When using this extension, it would be great if I could bootstrap the configuration with the Register method by specifying the configuration name (as possible with the Windows DSC VM Extension).

From the looks of it, the register.py script from DSC For Linux is already capable of handling this.
https://github.com/Microsoft/PowerShell-DSC-for-Linux/blob/master/LCM/scripts/Register.py#L144

**Comment by ericgable** [comment]
Which of the extension are you referring to?

**Comment by bgelens** [comment]
@ericgable DSC For Linux :-) 
https://github.com/Azure/azure-linux-extensions/tree/master/DSC

**Comment by bgelens** [comment]
It was addressed but PR was cancelled. Would be very useful if this PR was reconsidered
https://github.com/Azure/azure-linux-extensions/pull/324/

**Comment by 4c74356b41** [comment]
Welp, that's a hidden gem. Would be extremely usefull, else you onboard a node and what? :)

**Comment by balukambala** [comment]
Hi Ben,

Sorry for delay in this issue. I am currently working on this feature. We are planning to release this soon.

Bala subrahmanyam Kambala

**Comment by nielsweistra** [comment]
Hi Balu, we do we can expect this feature to be released?

**Comment by balukambala** [comment]
HI @nielsweistra,

We are going to roll this feature out in a safe deployment process. Probably by this month end, this feature will be released to all regions. Would you be willing to try out this in West Central US region (one of the early region that we release and test in production) and provide feed back?

Sincerely,
Bala subrahmanyam Kambala

**Comment by 4c74356b41** [comment]
Sure, if you tell us how ;) @balukambala

**Comment by balukambala** [comment]
This has been released to production. Please let us know if you find any issues. Closing this.

**Comment by 4c74356b41** [comment]
hey, is the syntax for this the same as windows dsc extension? @balukambala 
so to push configuration I should use `NodeConfigurationName` property?

**Comment by balukambala** [comment]
we need to use NodeConfigurationName property and ExtensionAction should be Register in public configuration file.

More details are here: 
https://github.com/Azure/azure-linux-extensions/tree/master/DSC#31-register-to-azure-automation-account
https://github.com/Azure/azure-linux-extensions/tree/master/DSC#11-public-configuration
