### ISSUE TITLE
[LAD] httpsport in omiserver.conf is reset to 0 whenever LinuxDiagnostic is upgraded

### ISSUE THREAD

**Issue by shinjisgogo** [Azure/azure-linux-extensions#265]
Background:
A customer reported us that the httpsport value defines at /etc/opt/omi/conf/omiserver.conf is reset to 0 whenever LinuxDiagnostic is upgreated. AutoUpgrading is set as true as default, so customer has to restore a previously-set value every time upgrading occurs. Customer want to fix this issue.

Request:
I found that this behavior is caused by current design of LinuxDiangnostics but I do not think what customer has to re-set config every time whenever upgrading is good design. So Could you check this behavior and if you confirm to change this design, please fix it.

My Investigation:
I investigated it and found that the httpsport was reset to 0 whenever diagnostic commands are operated as following order.

1. diagnostic -disable
2. diagnostic -enable

When LinuxDiagnostic upgrade, diagnostics commands are operated as following order. So I confirmed that upgrading operation causes to reset the httpsport value.

1. diagnostic.py -disable
2. diagnostic.py -update
3. diagnostic.py -uninstall
4. diagnostic.py -install
5. diagnostic.py -enable

Investigate from source code.
The httpsport value was reset at the following code in diagnostics.py.

```955:    # Check if OMI is configured to listen to any non-zero port and reconfigure if so.
956:    omi_listens_to_nonzero_port = RunGetOutput(r"grep '^\s*httpsport\s*=' /etc/opt/omi/conf/omiserver.conf | grep -v '^\s*httpsport\s*=\s*0\s*$'")[0] is 0
957:    if omi_listens_to_nonzero_port:
958:        RunGetOutput("/opt/omi/bin/omiconfigeditor httpsport -s 0 < /etc/opt/omi/conf/omiserver.conf > /etc/opt/omi/conf/omiserver.conf_temp")
959:        RunGetOutput("mv /etc/opt/omi/conf/omiserver.conf_temp /etc/opt/omi/conf/omiserver.conf")```

Above codes are called when “diagnostic.py -daemon” is operated in the code that is called by “diagnostic.py -enable” command.

And “diagnostic.py -daemon” is operated under the following conditions.

Condition1. UseSystemdServiceManager is false
 UseSystemdServiceManager is set as false whenever the version of OS is without “Ubuntu 15.10 or later”

Condition2. /var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9011/mdsd.pid is NOT existed.
 mdsd.pid is deleted whenever “diagnostic.py -disable” command is executed.


We can repro this issue anytime as executing commands.

**Comment by hosungsmsft** [comment]
Resolved with the mentioned commits, so closing. Thanks @jasonzio for your quick and valuable review!
