### ISSUE TITLE
[VMAccess]Cannot run "reset remote access" twice successively

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/azure-linux-extensions#267]
Description of problem:
The first time I run "reset remote access" it works well. But the second time it doesn't work. It seems that the mrseq number is not increased so that the current sequence number is not greater than the mrseq and then exit.

Version-Release number of selected component (if applicable):
VMAccess-1.4.6.0

How reproducible:
Always

Steps to Reproduce:
1. Prepare a VM (ASM mode) and execute "reset remote access" on it through portal.
2. Check the /etc/ssh/sshd_config file. The old file is made a backup and a new file is generated
# ll /etc/ssh/sshd_config*
-rw-------. 1 root root 3880 Oct 28 11:31 /etc/ssh/sshd_config
-rw-r--r--. 1 root root 4433 Oct 28 11:31 /etc/ssh/sshd_config_2016-10-28T03:31:41Z
3. Execute "reset remote access" again.
4. Check the /etc/ssh/sshd_config\* 
# ll /etc/ssh/sshd_config*

Actual results:
In step 4, no new sshd_config_\* is generated.

The second time I reset remote access, there's no new /var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0/config/*.settings, but the latest *.settings file is updated.(For example, if there were 0.settings and 1.settings files, after the second resetting remote access, there's no 2.settings file generated, but the 1.settings file is updated.)

Messages in /var/log/azure/Microsoft.OSTCExtensions.VMAccessForLinux/1.4.0.0/extension.log
2016/10/28 11:31:40 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Config decoded correctly.
2016/10/28 11:31:40 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Install,success,0,Install Succeeded
2016/10/28 11:31:41 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] sequence number is 0
2016/10/28 11:31:41 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0/config/0.settings
2016/10/28 11:31:41 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "MIIByAYJKoZIhvcNAQcDoIIBuTCCAbUCAQAxggFxMIIBbQIBADBVMEExPzA9BgoJkiaJk/IsZAEZFi9XaW5kb3dzIEF6dXJlIFNlcnZpY2UgTWFuYWdlbWVudCBmb3IgRXh0ZW5zaW9ucwIQHt6G/w8pPK5DLATOd61oEDANBgkqhkiG9w0BAQEFAASCAQAajNU+iRWQuFOFr0oOn5+gCjKY7+8SbfaDOqQyKT/esOFQCxMjCgNU3OVB6fKl0jnAh4oObAevKf+Hi/Yq6rS40ia8eubpkMljypfk1CvCVJO2TrHOt+HjsviHcUmH35faOF0fgY9lRwIYu3Jwu11n9rgc19YhqfTyloGDKX71Yy7+woocyCI7wxFjrEVUGntgjQypDi4Fk00yRJdpgTjnBRqDwV5uwVrswBZCGS6XF0pqgOldEoLoeZFgayJx2WRMRSZmCRfSefN3H+e0GX9KSru1cgrR3vQ3aIB97/ViSPJybfD0oFTcN2CLF5JOb9j4dls/4GZsL++AFAtUS4bgMDsGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIRxZZqzqn0hOAGL+fs5E68k69/jljSIt5g6jM3al1ujdoOA==", "publicSettings": null, "protectedSettingsCertThumbprint": "1D15CAA580A04E0CBB4E11C66B0C8322729DC701"}}]}
2016/10/28 11:31:41 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Config decoded correctly.
2016/10/28 11:31:41 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Succeeded in check and open ssh port.
2016/10/28 11:31:41 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] set most recent sequence number to 0
2016/10/28 11:31:41 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Succeeded in reset sshd_config.
2016/10/28 11:31:41 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Enable,success,0,Enable succeeded.

2016/10/28 11:34:17 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] sequence number is 0
2016/10/28 11:34:17 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0/config/0.settings
2016/10/28 11:34:17 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "MIIByAYJKoZIhvcNAQcDoIIBuTCCAbUCAQAxggFxMIIBbQIBADBVMEExPzA9BgoJkiaJk/IsZAEZFi9XaW5kb3dzIEF6dXJlIFNlcnZpY2UgTWFuYWdlbWVudCBmb3IgRXh0ZW5zaW9ucwIQHt6G/w8pPK5DLATOd61oEDANBgkqhkiG9w0BAQEFAASCAQBjupKaQdw6krFVlhgM75CgmbEFI1s/p7uuPm4HOtV9bBKjKNt8Gxh/Bt33rdP92VkfG7eo57RRx5cJmH5pJoauMBA/jfh1ImwgksYRcKXgh5uHApbKl3qaYR4gdjIFu34pwo2YiuKBr5ItABdsgPbJknU6P3enPTDxgNiiovzzzaHC40WG8Ff2Mhj4Tn562V9hWCWu5by+ABC/7FlvMP+zzztkX6TrQnfV/ZLkNUeQmxFIaNb39fl7KqtRxqYCQ+8pXUjTDzqvLbhEHzDHkmzvxLZGma2yHZCn8b8pOBKCBHsh7R2pn8Sm6IV+BvtpP1j6tO10jiiI7SkB5snqfMErMDsGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIcr7jQqK4SEiAGOOjw9BxXwgc/V0NM6N99gmU+wYDDiLx1Q==", "publicSettings": null, "protectedSettingsCertThumbprint": "1D15CAA580A04E0CBB4E11C66B0C8322729DC701"}}]}
2016/10/28 11:34:17 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Config decoded correctly.
2016/10/28 11:34:17 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Succeeded in check and open ssh port.
2016/10/28 11:34:17 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Current sequence number, 0, is not greater than the sequnce number of the most recent executed configuration. Exiting...

Expected results:
In step 4, the old sshd_config file is made a backup and a new file is generated.

Additional info:
If execute "reset remote access" several times successively, the sequence number will always the same, so that it will be quit.
If do "reset password" and then do "reset remote access", the "reset remote access" can work well.
If do "reset remote access", than do "reset password", then do "reset remote access" again, it can work well.

**Comment by boumenot** [comment]
Hi @yuxisun1217!  Thanks for reporting an issue.

If the configuration does *not* change.  Work is not sent to the extension for processing.  If you reset using the same configuration back to back I would not expect a change to be processed necessarily.  If you want the same configuration to be processed you have to add a change to the configuration document, such as a timestamp.  The timestamp should be updated before execution to ensure there's a difference.  

Most times we see this issue with CustomScript, and people wonder why their script did not execute again.  Here's a good example on how to change the [configuration][1].  Are you able to confirm if this in fact the issuue you are seeing?  Based on your **excellent** bug report, it appears to be the case.

[1]: https://github.com/Azure/azure-linux-extensions/tree/master/CustomScript#34-run-scripts-with-unchanged-configurations

**Comment by yuxisun1217** [comment]
Hi @boumenot ,
I'm sorry I think they are not the same issue. It seems that the "reset remote access" doesn't have the timestamp parameter. And even if I change the sshd_config file, this issue also exists.
I think the root cause is the sequence number is not increased, so the second "reset remote access" action is not accepted. 
I don't know why the sequence number is not increased. Is the sequence number controlled by this extension or by the WALinuxAgent? or somewhere else?

**Comment by boumenot** [comment]
It's the responsibility of the party crafting the request to set a time stamp parameter.  Let me reach out to the portal team, and discuss this issue with them.

**Comment by boumenot** [comment]
I have logged the issue with the Portal team.  They have not provided an ETA at this time.  I will share any updates as I get them.

**Comment by yuxisun1217** [comment]
OK, got it. Thank you very much @boumenot !
