### ISSUE TITLE
[VMAccess]When running "reset remote access", the backup sshd_config_* file is covered

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/azure-linux-extensions#272]
Description of problem:
When reset remote access(or reset password), the vmaccess.py do twice sshd_config backup executions:
1. Backup sshd_config then set "ChallengeResponseAuthentication no" in the sshd_config
2. Backup sshd_config then put a default sshd_config file into the VM
So there should be 2 backup files(named like sshd_config_2016-11-02T06:17:05Z) in the /etc/ssh/ folder. But there's only one backup file. Because the backup file name use the time string, and the twice backup execution are too close(in 1 second) that the time strings are the same, so the second backup file covers the first backup file.

Version-Release number of selected component (if applicable):
VMAccess-1.4.6.0

RHEL Version: RHEL-7.3

How reproducible:
100%

Steps to Reproduce:
1. Prepare a VM. Modify the value in the /etc/ssh/sshd_config, set "ChallengeResponseAuthentication yes".
2. Run "reset remote access" from Azure portal.
3. Check the "ChallengeResponseAuthentication" item inside the sshd_config_* file

Actual Result:
The "ChallengeResponseAuthentication" is "no" inside the backup sshd_config_* file

Expect Result:
The "ChallengeResponseAuthentication" is "yes" inside the backup sshd_config_* file

Additional Info:
It doesn't occurred in RHEL-6 because the sshd restart execution costs 2-3 seconds. But it only costs less than 1 second in RHEL-7.

**Comment by yuxisun1217** [comment]
Would you mind explaining why forcibly set "ChallengeResponseAuthentication" to "no" at the beginning?  It backups sshd_config file, and If my execution is "reset remote access", it will backup the sshd_config file again. So that there will be 2 backup files. I think it might be a little confused for the customers.
Thanks!

**Comment by boumenot** [comment]
Previous version of VMAccessForLinux set this value to yes under certain conditions.  We consider this to be bad.  The extension has been changed to forcibly set this value to no always to undo that old behavior.  If you need ChallengeResponseAuthentication to be yes, then you must uninstall VMAccessForLinux. 

I will document this behavior.

**Comment by yuxisun1217** [comment]
Thank you very much @boumenot ! I understand it now. 
And about the issue I mentioned in the description, the original sshd_config file is covered, which I think is not what we want. Perhaps we could change the postfix timestring of sshd_config_*(Such as use millisecond but not second as the unit) to prevent this issue.
What do you think about that? Thanks!
