### ISSUE TITLE
The Extension "VMAccessForLinux" Enable Failed

### ISSUE THREAD

**Issue by stanleyhong** [Azure/azure-linux-extensions#282]
Dear Experts:
Recently I provisioning one Linux virtual machine (Centos 7/Resource Manager) from the custom VHD file which uploaded into Azure storage blob. Everything seem fine except two issue I observed below:

Issue 1:  Manually installed the latest VM agent for linux first, but no matter I use the powershell command or through the portal to reset the user password, it always get failed with below error message found in extension log.
---------------------------------------------------------------------------------------------
2016/11/23 15:25:10 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] sequence                             number is 0
2016/11/23 15:25:10 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] setting                             file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0/c                            onfig/0.settings
2016/11/23 15:25:10 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] JSON con                            fig: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "MIIB4AYJKoZ                            IhvcNAQcDoIIB0TCCAc0CAQAxggFpMIIBZQIBADBNMDkxNzA1BgoJkiaJk/IsZAEZFidXaW5kb3dzIEF                            6dXJlIENSUCBDZXJ0aWZpY2F0ZSBHZW5lcmF0b3ICEF53i2Gow5OnR8IvFRsSasswDQYJKoZIhvcNAQE                            BBQAEggEAiGxKv6VTW5IluLGMZ26eJnXToWQxzY1oTtVnKQf1snHEV7JBaDoPJlM2NuInvDXs1rA51RD                            lAU17Og9rDLm3NTem55WyRG9ANT87mf869vdL/M5fdZhB9QbO1aJTCkBn2bpnps5t7X8lCUfGekrAeMD                            hACnrZKlaKlmkxPN7YX/ARBsD9TyVrauXz7fshVOT8PeVvxue8C+MddM58ot6N98gt3HueEH1GxTzuiH                            CSuLXSN34qeRPQ46Jbz1IiF0y08t1JFGqcNZvcn2P4UWr3bx34xiEm6M0VYKX5LXMNiemWI9K/bgcpJ8                            jpZRMPrx/tmkVHFhPe1MCqu/3BY2l8DBbBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECENgdMLZao8ugDg                            jt+RrqDVVWuCtp9DiWxm5D05974fSO9Ssv2tk5n7R1gmr3vtnBSATRD4VFdJKzrYw97ox3iGAtg==",                             "publicSettings": {}, "protectedSettingsCertThumbprint": "4546850E7C0933BE6145AE                            51035EF8D4D5DEFFB5"}}]}
2016/11/23 15:25:10 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Config d                            ecoded correctly.
2016/11/23 15:25:10 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Install,                            success,0,Install Succeeded
2016/11/23 15:25:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] sequence                             number is 0
2016/11/23 15:25:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] setting                             file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0/c                            onfig/0.settings
2016/11/23 15:25:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] JSON con                            fig: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "MIIB4AYJKoZ                            IhvcNAQcDoIIB0TCCAc0CAQAxggFpMIIBZQIBADBNMDkxNzA1BgoJkiaJk/IsZAEZFidXaW5kb3dzIEF                            6dXJlIENSUCBDZXJ0aWZpY2F0ZSBHZW5lcmF0b3ICEF53i2Gow5OnR8IvFRsSasswDQYJKoZIhvcNAQE                            BBQAEggEAiGxKv6VTW5IluLGMZ26eJnXToWQxzY1oTtVnKQf1snHEV7JBaDoPJlM2NuInvDXs1rA51RD                            lAU17Og9rDLm3NTem55WyRG9ANT87mf869vdL/M5fdZhB9QbO1aJTCkBn2bpnps5t7X8lCUfGekrAeMD                            hACnrZKlaKlmkxPN7YX/ARBsD9TyVrauXz7fshVOT8PeVvxue8C+MddM58ot6N98gt3HueEH1GxTzuiH                            CSuLXSN34qeRPQ46Jbz1IiF0y08t1JFGqcNZvcn2P4UWr3bx34xiEm6M0VYKX5LXMNiemWI9K/bgcpJ8                            jpZRMPrx/tmkVHFhPe1MCqu/3BY2l8DBbBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECENgdMLZao8ugDg                            jt+RrqDVVWuCtp9DiWxm5D05974fSO9Ssv2tk5n7R1gmr3vtnBSATRD4VFdJKzrYw97ox3iGAtg==",                             "publicSettings": {}, "protectedSettingsCertThumbprint": "4546850E7C0933BE6145AE                            51035EF8D4D5DEFFB5"}}]}
2016/11/23 15:25:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Config d                            ecoded correctly.
2016/11/23 15:25:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] set most                             recent sequence number to 0
2016/11/23 15:25:11 ERROR:[Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Fa                            iled to enable the extension with error: no element found: line 22, column 31, s                            tack trace: Traceback (most recent call last):
2016/11/23 15:25:11 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAc                            cessForLinux-1.4.6.0/./vmaccess.py", line 96, in enable
2016/11/23 15:25:11 ERROR:    _set_user_account_pub_key(protect_settings, hutil)
2016/11/23 15:25:11 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAc                            cessForLinux-1.4.6.0/./vmaccess.py", line 162, in _set_user_account_pub_key
2016/11/23 15:25:11 ERROR:    ovf_env = waagent.OvfEnv().Parse(ovf_xml)
2016/11/23 15:25:11 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAc                            cessForLinux-1.4.6.0/waagent", line 4778, in Parse
2016/11/23 15:25:11 ERROR:    dom = xml.dom.minidom.parseString(xmlText)
2016/11/23 15:25:11 ERROR:  File "/usr/lib64/python2.7/xml/dom/minidom.py", line                             1931, in parseString
2016/11/23 15:25:11 ERROR:    return expatbuilder.parseString(string)
2016/11/23 15:25:11 ERROR:  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py",                             line 940, in parseString
2016/11/23 15:25:11 ERROR:    return builder.parseString(string)
2016/11/23 15:25:11 ERROR:  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py",                             line 223, in parseString
2016/11/23 15:25:11 ERROR:    parser.Parse(string, True)
2016/11/23 15:25:11 ERROR:ExpatError: no element found: line 22, column 31
2016/11/23 15:25:11 ERROR:
2016/11/23 15:25:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Enable,e                            rror,0,Enable failed.
---------------------------------------------------------------------------------------------
Meanwhile the VM cannot restart through the portal 
I tried to remove extension then run the command again but issue persist still. Can anyone advise how can I resolved such issue? Thanks a lot!!

Issue 2: The computer name is blank on the portal,  I guess it might involves to the custom image or any agent or extension not work properly , because other VMs provision from the Azure image gallery has no such issue. Please advise.... thanks!

**Comment by stanleyhong** [comment]
The issue 1 is resolved after I manually copy ovf-env.xml from another Azure VM(Working Fine) to current one, also need to modify ovf-env.xml such like hostname and username to ensure such setting match current VM environment. After the fix, both "Restart" button and feature "Reset Password" come back to work on Azure portal! But now I'm struggling with issue 2 that "Computer Name" is empty on the portal. will keep posting if have any further update. please please if you have any good idea or expertise please write down here! Thanks!

**Comment by boumenot** [comment]
The ovf-env.xml is injected into the computer by mounting an ISO with the VM's specific ovf-env.xml.  We have seen issues where the ISO failed to mount because the VM was missing the appropriate driver.  This was due to either the customer deploying a custom image, or using 3rd party images that were misproperly configured.

Is this a custom image?  Would you please provide more details about your VM.

**Comment by stanleyhong** [comment]
Hi Christopher,

Thanks for your reply. Yes it’s custom image, please refer to below information and advise the solution. Thanks.



Could you help confirm/provide more information below:

1.      Subscription ID: b8d008f9-4c65-49db-84d3-d164cf628573 (Y/N)

YES

2.      VM Name: testcpanel01 (Y/N)

YES

3.      The vhd is from Hyper-V or VMWare or from Azure Gallery:

The vhd was converted from VMDK file which export from VMware Hypervisor.

4.      Any steps or article you followed to upload to Azure: (If it’s from Hyper-V or VMWare):

Yes I follow the Microsoft official article to upload VHD and provision VM via powershell cmdlet.  Below is basic steps for your tracing

1.      Export OVF template from VMware Vsphere

2.      Convert VMDK file(OVF template content) to VHD via MVMC

3.      Import VHD into local Hyper-V (Generation 1) to fix VM boot up issue ( the normal issue occur on Hyper-V if VHD comes from VMware and running Linux OS)

4.      Upload VHD into Azure storage blobs and create VM and many components via Powershell including resource group, network security group, network interface, public IP, virtual network…etc

5.      Manually install VM agent for Linux (Agent service running fine)

6.      Identify the issue of extension “VMAccessForLinux”



5.      Error Message and screen capture you got:
Error in waagent.log, full log uploaded with support ticket already.

----------------QUOTE--------------------

INFO Copying ovf-env.xml

2016/11/25 11:21:38.690006 ERROR [ProtocolError] Provisioning failed: (000008)(000007)Failed to get dvd device

----------------UNQUOTE--------------------
Extension log


----------------QUOTE--------------------
2016/11/23 15:25:10 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] sequence number is 0
2016/11/23 15:25:10 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0/c onfig/0.settings
2016/11/23 15:25:10 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] JSON con fig: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "MIIB4AYJKoZ IhvcNAQcDoIIB0TCCAc0CAQAxggFpMIIBZQIBADBNMDkxNzA1BgoJkiaJk/IsZAEZFidXaW5kb3dzIEF 6dXJlIENSUCBDZXJ0aWZpY2F0ZSBHZW5lcmF0b3ICEF53i2Gow5OnR8IvFRsSasswDQYJKoZIhvcNAQE BBQAEggEAiGxKv6VTW5IluLGMZ26eJnXToWQxzY1oTtVnKQf1snHEV7JBaDoPJlM2NuInvDXs1rA51RD lAU17Og9rDLm3NTem55WyRG9ANT87mf869vdL/M5fdZhB9QbO1aJTCkBn2bpnps5t7X8lCUfGekrAeMD hACnrZKlaKlmkxPN7YX/ARBsD9TyVrauXz7fshVOT8PeVvxue8C+MddM58ot6N98gt3HueEH1GxTzuiH CSuLXSN34qeRPQ46Jbz1IiF0y08t1JFGqcNZvcn2P4UWr3bx34xiEm6M0VYKX5LXMNiemWI9K/bgcpJ8 jpZRMPrx/tmkVHFhPe1MCqu/3BY2l8DBbBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECENgdMLZao8ugDg jt+RrqDVVWuCtp9DiWxm5D05974fSO9Ssv2tk5n7R1gmr3vtnBSATRD4VFdJKzrYw97ox3iGAtg==", "publicSettings": {}, "protectedSettingsCertThumbprint": "4546850E7C0933BE6145AE 51035EF8D4D5DEFFB5"}}]}
2016/11/23 15:25:10 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Config d ecoded correctly.
2016/11/23 15:25:10 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Install, success,0,Install Succeeded
2016/11/23 15:25:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] sequence number is 0
2016/11/23 15:25:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0/c onfig/0.settings
2016/11/23 15:25:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] JSON con fig: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "MIIB4AYJKoZ IhvcNAQcDoIIB0TCCAc0CAQAxggFpMIIBZQIBADBNMDkxNzA1BgoJkiaJk/IsZAEZFidXaW5kb3dzIEF 6dXJlIENSUCBDZXJ0aWZpY2F0ZSBHZW5lcmF0b3ICEF53i2Gow5OnR8IvFRsSasswDQYJKoZIhvcNAQE BBQAEggEAiGxKv6VTW5IluLGMZ26eJnXToWQxzY1oTtVnKQf1snHEV7JBaDoPJlM2NuInvDXs1rA51RD lAU17Og9rDLm3NTem55WyRG9ANT87mf869vdL/M5fdZhB9QbO1aJTCkBn2bpnps5t7X8lCUfGekrAeMD hACnrZKlaKlmkxPN7YX/ARBsD9TyVrauXz7fshVOT8PeVvxue8C+MddM58ot6N98gt3HueEH1GxTzuiH CSuLXSN34qeRPQ46Jbz1IiF0y08t1JFGqcNZvcn2P4UWr3bx34xiEm6M0VYKX5LXMNiemWI9K/bgcpJ8 jpZRMPrx/tmkVHFhPe1MCqu/3BY2l8DBbBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECENgdMLZao8ugDg jt+RrqDVVWuCtp9DiWxm5D05974fSO9Ssv2tk5n7R1gmr3vtnBSATRD4VFdJKzrYw97ox3iGAtg==", "publicSettings": {}, "protectedSettingsCertThumbprint": "4546850E7C0933BE6145AE 51035EF8D4D5DEFFB5"}}]}
2016/11/23 15:25:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Config d ecoded correctly.
2016/11/23 15:25:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] set most recent sequence number to 0
2016/11/23 15:25:11 ERROR:[Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Fa iled to enable the extension with error: no element found: line 22, column 31, s tack trace: Traceback (most recent call last):
2016/11/23 15:25:11 ERROR: File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAc cessForLinux-1.4.6.0/./vmaccess.py", line 96, in enable
2016/11/23 15:25:11 ERROR: _set_user_account_pub_key(protect_settings, hutil)
2016/11/23 15:25:11 ERROR: File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAc cessForLinux-1.4.6.0/./vmaccess.py", line 162, in _set_user_account_pub_key
2016/11/23 15:25:11 ERROR: ovf_env = waagent.OvfEnv().Parse(ovf_xml)
2016/11/23 15:25:11 ERROR: File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAc cessForLinux-1.4.6.0/waagent", line 4778, in Parse
2016/11/23 15:25:11 ERROR: dom = xml.dom.minidom.parseString(xmlText)
2016/11/23 15:25:11 ERROR: File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1931, in parseString
2016/11/23 15:25:11 ERROR: return expatbuilder.parseString(string)
2016/11/23 15:25:11 ERROR: File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
2016/11/23 15:25:11 ERROR: return builder.parseString(string)
2016/11/23 15:25:11 ERROR: File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
2016/11/23 15:25:11 ERROR: parser.Parse(string, True)
2016/11/23 15:25:11 ERROR:ExpatError: no element found: line 22, column 31
2016/11/23 15:25:11 ERROR:
2016/11/23 15:25:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Enable,e rror,0,Enable failed.

----------------UNQUOTE--------------------


Best Regards!

[ReSources Logo]

Stanley Hong, Cloud Specialist
No.688 Nanjing West Road, Shanghai, Shanghai 200041 China
T: +852 2214 7573  M: +86 18616851055  F: +862 16193 1599
stanley.hong@apac-resources.com<mailto:stanley.hong@apac-resources.com>

EXCELLENCE THROUGH PARTNERSHIP

**Comment by stanleyhong** [comment]
Hi Christopher, 
WOW, it's surprised, see your reply here! I've replied your question via mail this morning. Please advise what shall I do next. Thanks!

**Comment by boumenot** [comment]
This is the culprit.

> 2016/11/25 11:21:38.690006 ERROR [ProtocolError] Provisioning failed: (000008)(000007)Failed to get dvd device

If you cannot access the DVD, the agent cannot copy the ovf-env.xml, and if you cannot copy the file then everything downstream will fail.

We do not support custom images, but you should be able to make it work by ensuring the drivers are correctly installed on the custom image.

It looks like you already have a support case opened, and are working with a representative on this issue.  Let's continue to work through support to see if we can get you unblocked.

**Comment by stanleyhong** [comment]
Hi Christopher,

Could you please advise which kind of drivers need to be installed?  It would be great if you can provide the link for driver download. Thanks!




Best Regards!

[ReSources Logo]

Stanley Hong, Cloud Specialist
No.688 Nanjing West Road, Shanghai, Shanghai 200041 China
T: +852 2214 7573  M: +86 18616851055  F: +862 16193 1599
stanley.hong@apac-resources.com<mailto:stanley.hong@apac-resources.com>

EXCELLENCE THROUGH PARTNERSHIP

**Comment by boumenot** [comment]
Hyper-V.  You'll need to find the drivers that are particular to your distro, but they should contain the name Hyper-V in the name or description.

**Comment by boumenot** [comment]
Closed due to lack of activity. Please re-open as appropriate.
