### ISSUE TITLE
DSCForLinux : ARM template PUSH fails with some resources

### ISSUE THREAD

**Issue by allanmoller** [Azure/azure-linux-extensions#285]
Hey all, 

ps sry for markup, cant get it to work :-(

Have been fighting with DSCForLinux for some time now with no luck! seems I can do some stuff but not other :-( 
Iam currently using DSCForlinux to push MOF files in an arm template to VM in azure durring creation! for now I have been able to create users, create files and add FW rules which usually requires SU, but when I try and kill FW (see below scripts) it fails, if I then try and do it using a CIM session it works ok!

It seems strange that I can do some SU tasks but not others, I plan to deploy using an Azure runbook in an automatic way so creating CIM sessions will not work (no public endpoints). So hope someone can answer the following questions?

- Why can I only do some configurations in PUSH mode? 
- any other ways I can do this?
- Have tried looking for a BUG list for DSCForLinux but cant seem to find it, anyone got a list?

**Create users:**
`nxUser UserExample{

        UserName = "monuser"
        Description = "Monitoring user"
        Password  =    "test"
        Ensure = "Present"
        HomeDirectory = "/home/monuser"
    }`
**Create files:**
`nxFile ExampleFile {

        DestinationPath = "/tmp/example"
        Contents = "hello world `n"
        Ensure = "Present"
        Type = "File"
        Force = $True
    }`
**Add firewall rules**
nxScript AddFirewallRule {
    SetScript = @"
    #!/bin/bash
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport http -j DROP
/etc/init.d/iptables save
"@
    TestScript = @"
#!/bin/bash
iptables -L | grep ^DROP | grep "dpt:http "
exit $?
"@
    GetScript = @"
#!/bin/bash
iptables -L | grep ^DROP | grep "dpt:http "
"@
}

**But when I try to kill my firewall it fails!!**
nxScript remove_firewall {
    TestScript = @"
#!/bin/bash
service iptables status | grep "iptables: Firewall is not running." >/dev/null 2>/dev/null && exit 0;
exit 1
"@
    SetScript = @"
#!/bin/bash
service iptables stop >/dev/null 2>/dev/null
"@
    GetScript = ''
}
**even tried doing this with nxservice**

`nxService remove_firewall{

        Name = "iptables"
        Controller = "systemd"
        State = "Stopped
        Enabled = $False"  
}`

**Comment by allanmoller** [comment]
No one :-) ?

**Comment by boumenot** [comment]
The DSC extension changed ownership recently.  The owners were asked to follow up on this issue, and the other two that are outstanding.  I have re-reminded them of these pending issues, and asked them to investigate.  Sorry for the delay, and lack of activity.

**Comment by allanmoller** [comment]
no problem :-) looking forward to reply.

**Comment by ericgable** [comment]
Hi! I'm Eric - I'll be handling DSC For Linux issues.
I'll look into this - for firewall rules you might want to use the nxFirewall provider in the future.
Also try this for RHEL - 
`/etc/init.d/iptables` stop

Some questions:
What version of RHEL is this?
Can I get a copy of the dsc.log?
Tia!

**Comment by allanmoller** [comment]
Hey ericgable, thx it seems that the error was related to and empty 'Getscript' after adding an '#!bin/bash echo hey' it started working. 

I still dont understand why I was able to do it using a CIM session with root privileges, but nevertheless its working. 

one thing I was really missing was debugging when doing Push keept getting the an undefined error in OMI :-) thus really hard to determine what the error was.

**Comment by ericgable** [comment]
Great! So can we close this?

**Comment by allanmoller** [comment]
yes please close this
