### ISSUE TITLE
dpkg status database is locked by another process

### ISSUE THREAD

**Issue by wbuchwalter** [Azure/azure-linux-extensions#291]
Hi,

I am deploying an ARM template ([here](https://gist.github.com/wbuchwalter/541fa85a9cc561c5656e411dae39afb2)) with a custom linux extension ([here](https://gist.github.com/wbuchwalter/cb41e1e782fce28041a90574663726fd)).
This extension is basically doing some `apt-get install` and then manually installing a package with `dpkg`.

The VM this extension is attached to is based on a custom image (generalized from Ubuntu 16.04).

The extension will fail on `dpkg`, with error:
`dpkg: error: dpkg status database is locked by another process`

It's worth noting that while `apt-get install` seems to work fine, it also throws some similar errors:
`E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?`

This issue is somewhat related to #95, but I did not install any other extensions.

I added a `ps ax | grep dpkg` to see if something else was using dpkg, but it doesn't seems so.

Content of `/var/lib/waagent` for reference
```
884D28C1001CCA04E6DC7D86D49DDC11C806C6CB.crt  GoalState.2.xml                                         TransportPrivate.pem
884D28C1001CCA04E6DC7D86D49DDC11C806C6CB.prv  HostingEnvironmentConfig.xml                            WireServerEndpoint
Certificates.p7m                              Incarnation                                             custom-script
Certificates.pem                              Microsoft.Azure.Extensions.CustomScript-2.0.2           events
Certificates.xml                              Microsoft.Azure.Extensions.CustomScript.2.manifest.xml  handler_state
ExtensionsConfig.1.xml                        Microsoft.Azure.Extensions__CustomScript__2.0.2.zip     ovf-env.xml
ExtensionsConfig.2.xml                        SharedConfig.xml                                        provisioned
GoalState.1.xml                               TransportCert.pem
```

If I add a `sleep 10m` at the start of my script everything works fine, so it seems that my custom extension is executed before the VM is fully ready.

Thanks

**Comment by boumenot** [comment]
My *guess* is that you did not execute the command as root, so prefixing apt-get with sudo will help.

> sudo apt-get install <package ...>  

The repository you want is https://github.com/Azure/custom-script-extension-linux, not this one.  This is the repository for the *old* CustomScript extension.  Sorry for the confusion!

If the sudo guess does not work, would you please send a gist of of /var/log/waagent.log, and /var/log/azure/CustomScript/<version>/extension.log.

**Comment by wbuchwalter** [comment]
Thanks, I'll close and reopen on the other repo with the logs.
If you check the gist I linked for the extension, it's already running as sudo.
Also keep in mind that `apt-get install`, while complaining in the logs, still works fine, the problem arise with `dpkg`.
