### ISSUE TITLE
[Feature request] More granular account expiration date

### ISSUE THREAD

**Issue by pawellipiec** [Azure/azure-linux-extensions#293]
In the VMAccess extension, for the operation of creating user account with expiration date, you can only specify expiration date (no time component).  Could you add support for specifying an expiration date and time?

**Comment by boumenot** [comment]
To my knowledge, time is not supported.  The best granularity you have is date.

**Comment by boumenot** [comment]
The man page for useradd has more details

```text
      -e, --expiredate EXPIRE_DATE
           The date on which the user account will be disabled. The date is specified in the format YYYY-MM-DD.

           If not specified, useradd will use the default expiry date specified by the EXPIRE variable in /etc/default/useradd, or an empty string (no
           expiry) by default.
```

See the [code](https://github.com/Azure/azure-linux-extensions/blob/17d89554ecbcab29d5a48bb6f689fa57586ab205/Common/WALinuxAgent-2.0.16/waagent#L1394-L13960) for the relevant lines.
