### ISSUE TITLE
vm freezes during back up.

### ISSUE THREAD

**Issue by saimsh** [Azure/azure-linux-extensions#296]
wala agent : 2.2.2
os : centos 7.1 
SubscriptionId            : 85c6bb31-8a39-45f5-9450-6257e50df827
SubscriptionName      : PZI-US-N-SUB01
and VM affected is USAZU2JRADLV001
vm extension version : 1.0.9103.0
python version : 2.7.5

[extension.log.txt](https://github.com/Azure/azure-linux-extensions/files/662296/extension.log.txt)

[waagent.log.txt](https://github.com/Azure/azure-linux-extensions/files/662298/waagent.log.txt)

 the issue started after December 14th. customer performed a yum update ( updated waagent ) and installed docker in the vm.

**Comment by saimsh** [comment]
from quick investigation of the extension log: I see that the freezing of filesystem starts. however, there is no followup log about freezing and unfreezing of devices as in the working scenario.
are servers running docker/docker extensions not supported for backup

**Comment by saimsh** [comment]
this issue is in reference to the ICM filed: https://icm.ad.msft.net/imp/IncidentDetails.aspx?id=28191298 ( incase of redundancy, feel free to close this)

**Comment by soumyanishan** [comment]
@saimsh this issue has been resolved. Can you please check?

**Comment by saimsh** [comment]
yes, you can go ahead and close it :).
backup is not supported yet  for machines running docker
