### ISSUE TITLE
Is there requirements to port linux extensions to FreeBsd?

### ISSUE THREAD

**Issue by crea7or** [Azure/azure-linux-extensions#300]
I see that there is component mdsd, that is not visible in sources. Is it the main problem in porting?

**Comment by boumenot** [comment]
Hi @crea7or - what extension do you mean?  There are several extensions in this repository.

**Comment by hosungsmsft** [comment]
@crea7or : Yes. mdsd is the actual monitoring agent program that's bundled in LAD (Linux Azure Diagnostic) extension. It's native, written in C/C++, and linked with other dependencies, like OMI/SCX and Rsyslog, which are not available on FreeBSD, so that's why LAD is not available on FreeBSD.
