### ISSUE TITLE
Support and Examples for Diagnostics to Stream performance counters to Event Hubs

### ISSUE THREAD

**Issue by flopzoid** [Azure/azure-linux-extensions#301]
This is supported for Windows, but I don't believe it is supported for Linux.  This is something my current customer would leverage.

**Comment by hosungsmsft** [comment]
Hi @flopzoid , Yes, EventHub sink is not yet supported on LAD (Linux Azure Diagnostic), and we are working to implement the feature on LAD. We don't have a specific ETA yet, but we'll announce it once it (with examples) becomes available. Thanks.
