### ISSUE TITLE
Tooling to collect logs from extension logFolder as described in design-details.md?

### ISSUE THREAD

**Issue by CraigWiand** [Azure/azure-linux-extensions#307]
In the [HandlerEnvironment section](https://github.com/Azure/azure-linux-extensions/blob/master/docs/design-details.md#handlerenvironment) in design-details.md we say: 

> logFolder – contains the location where the handler should put its log files that might be needed to debug any customer issues. The advantage of putting log files under the folder directed by this location is that these files can be automatically retrieved from the customers VM by using a tool, without actually logging into the VM and copying them over manually.

It is unclear what publically available tool for collecting these logs is being referred to above.  Can we provide a pointer if such a tool is available? 

@vijaykota, @bingosummer

**Comment by hosungsmsft** [comment]
Sorry I missed this. The 'logFolder' for Linux extensions is `/var/log/azure/<extension_full_name>/<extension_version>` and it's included in the ACIS InspectIaaSDisk with Diagnostic mode. I think this answers your question? If not, please follow up with me later outside this channel. Thanks. I'm closing this issue with this response.
