### ISSUE TITLE
[LAD] - Questions - Old version directories

### ISSUE THREAD

**Issue by linuxelf001** [Azure/azure-linux-extensions#325]
1) Upon installing a newer LAD release, can customer delete older version directories?

2) Any design decisions for not cleaning the older version directories (say N-3 till oldest) automatically?

**Comment by hosungsmsft** [comment]
This question should be directed to [WALinuxAgent](https://github.com/Azure/WALinuxAgent), as it's the WALA that controls creation/deletion of extension directories. Extensions themselves cannot create/delete their own directories.
