### ISSUE TITLE
OMS Agent extension for Linux and DSC extension for Linux seems incompatable 

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-linux-extensions#328]
If I install first the OMS Agent extension for Linux on a Azure VM and than the DSC extension for Linux, the DSC extension for Linux is taking forever to install. I didn't waited after 10 minutes passed but I would assume it cannot be installed and it will fail. You should investigate this and find what is the issue. If I first install the DSC Extension for Linux and than the OMS agent extension for Linux there is no problem.

**Comment by balukambala** [comment]
@slavizh, sorry for the inconvenience. This has been fixed. Please let us know if you face any more issues.
