### ISSUE TITLE
VMAccessForLinux extension not working correctly during ARM template deployment. 

### ISSUE THREAD

**Issue by BretStateham** [Azure/azure-linux-extensions#333]
Repo:

***All of these steps are performed with the Azure CLI v0.10.8 (node.js)*** 

1. Create an Ubuntu 16.04 VM in Azure (ARM) in the "Source" subscription using the portal or azure cli.  Doesn't matter.
1. Specify the sudo user name and password during provisioning (example: `devadmin/P@ssw1rd1234`)
1. Stop and Deallocate the source VM using the portal or azure cli. 
1. Create a new Resource Group (example `dli0201group`), Storage Account (example `dli0201storage`) and Container (example `vhds`) in a second "Target" subscription
1. Copy the VHD blob from the source subscription to the target subscription's storage account and container using the method of your choice.  (Storage Explorer, azure storage blob copy start, AzCopy, etc.)

   > **Note**: The copied vhd IS NOT GENERALIZED.  It will be attached as an OSDisk on the target VM.  Think of this as "migrating an existing VM to a new subscription", or similar to "migrating an on-prem vm to Azure" type scenario.  

1. Using Storage Explorer, open the properties of the VHD copy and delete the metadata properties.
1. In the target subscription, use an arm template to create a new VM with the copied VHD as an attached OSDisk. Template includes all additional vnet, nic, publicip, network security group and rules, etc. The template also includes the VMAccessForLinux extension to attempt to reset the sudo user's password  on the vm:

   [template.json](https://github.com/Azure/azure-linux-extensions/files/748758/template.json.txt)
   [parameters.json](https://github.com/Azure/azure-linux-extensions/files/748761/parameters.json.txt)

   ```bash
   azure group deployment create --resource-group dli0201group --name DeployPreExistingVmWithPasswordReset --template-file template.json --parameters-file parameters.json
   ```

1. Template deployment succeeds (NO ERRORS)
1. Attempt to ssh into the target VM, connection is established however the password that was reset during the template deployment does NOT work. 
1. ***If you view the list of installed extension for the Target VM however, the VMAccessForLinux extension is present, it just didn't reset the password as specified in the arm template.***

1. Because the VMAccessForLinux extension has already been installed by the template, any attempt to install it from the command line will fail because it already exists.  Therefore, we must in-install it first.  You can do this via the portal, or you can use the azure cli to remove the VMAccessForLinux extension

   ```bash
   azure vm extension set dli0201group dli0201vm VMAccessForLinux Microsoft.OSTCExtensions 1.4  --uninstall
   ```

1. Create a private.json  file with the sudo user name and password (same values that were specified in the arm template)
1. Use the azure cli to re-apply the VMAccessForLinux extension using the private.json values.  

   [private.json](https://github.com/Azure/azure-linux-extensions/files/748800/private.json.txt)

   ```bash
   azure vm extension set dli0201group dli0201vm VMAccessForLinux Microsoft.OSTCExtensions 1.4  --private-config-path private.json 
   ```

1. Connect to the target VM using SSH, new password now works.

**Comment by boumenot** [comment]
Before a new VM can be brought up, you must deprovision it.  It **sounds** like you have old state laying around that is causing problems.

```sh
"/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
```

**Comment by BretStateham** [comment]
What impact would that have on other configs?  Our hope was that the existing configuration would remain intact.  My goal here IS NOT to use this as an "image" but rather just to effectively "migrate" and existing VM to a different subscription.  I would prefer that the original sudo user name and password remained intact.  I was only resetting them because they didn't appear to be.

**Comment by boumenot** [comment]
The Agent [README](https://github.com/Azure/WALinuxAgent/blob/54256269d40e8175702f720e3ba4fa943b5c0567/README.md) is the source of the following.

```text
-deprovision: Attempt to clean the system and make it suitable for re-provisioning, by deleting the following:

All SSH host keys (if Provisioning.RegenerateSshHostKeyPair is 'y' in the configuration file)
Nameserver configuration in /etc/resolv.conf
Root password from /etc/shadow (if Provisioning.DeleteRootPassword is 'y' in the configuration file)
Cached DHCP client leases
Resets host name to localhost.localdomain

WARNING! Deprovision does not guarantee that the image is cleared of all sensitive information and suitable for redistribution.

-deprovision+user: Performs everything under deprovision (above) and also deletes the last provisioned user account and associated data.
```

This is not a scenario we support.  Is it possible that -deprovision is sufficient for your needs?

Our guidance for these types of scenarios (if I understand you correctly) is to use Packer.  Stamp out images that look the way you want, and then deploy them at will.

**Comment by boumenot** [comment]
Closed due to lack of activity.  Please re-open as appropriate.
