### ISSUE TITLE
login shell is not bash ?

### ISSUE THREAD

**Issue by takekazuomi** [Azure/azure-linux-extensions#336]
In the VMAccess extension, for the operation of creating user account. Created account login shell is sh. Why not bash ?

**Comment by boumenot** [comment]
I don't have the history on this, but I assume sh was the smallest common denominator.

**Comment by takekazuomi** [comment]
The default login shell for newly created Linux VMs is bash.
After creating the VM, the login shell of the new sudo user created with VMAccessExtention is sh.

Https://github.com/takekazuomi/azure-linux-extensions/tree/master/VMAccess#34-creating-a-new-sudo-user-account-with-the-password

I think the same is better for these two.

**Comment by boumenot** [comment]
The behavior of useradd can be controlled via /etc/useradd.conf, and the skeleton file.  I think it is more appropriate to defer to those configurations than it is to add more parameters to VMAccess.  The default shell should be based on how these files are defined.  I would expect it to be Bash too, but based on your experience I am wrong.

What is the configuration of these files in your case?  Is VMAccess not respecting them?

**Comment by takekazuomi** [comment]
I executed it with the Linux VM as shown below for confirmation.
In useradd - m, the login shell was empty. However, in useradd - D, it was / bin / bash. This may be a problem with the distribution.

```
$ uname -a
Linux kinmugiubt02 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/useradd.conf
cat: /etc/useradd.conf: No such file or directory
$ sudo useradd -m omitest2
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
$ grep omitest2 /etc/passwd
omitest2:x:1004:1004::/home/omitest2:
$ useradd -D
GROUP=100
HOME=/home
INACTIVE=-1
EXPIRE=
SHELL=/bin/bash
SKEL=/etc/skel
CREATE_MAIL_SPOOL=no
$
```

**Comment by boumenot** [comment]
I do not know enough to confirm or deny that, but I believe there is a better way to manage this outside of VMAccess.  I am closing this issue because I believe the correct answer is distro configuration.
