### ISSUE TITLE
Custom script not always executes and extension status message is missing

### ISSUE THREAD

**Issue by leovms** [Azure/azure-linux-extensions#339]
**Problem:** Custom script extension for Linux no longer outputs status message.

**Sample code:** [TestAzureDtlCseLinux.zip](https://github.com/Azure/azure-linux-extensions/files/767683/TestAzureDtlCseLinux.zip)

**Steps to Reproduce:**
> 1. Using attached scripts, upload the script `script.sh` to make it accessible as a URI.
> 2. Make sure to be logged in to the Linux machine and acting as root (Redhat 7.3 or Ubuntu 16.*).
> 3. Modify the parameters in `Invoke-AzureDtlCseLinux.ps1`.
> 4. Make sure the `$AgentVersion` parameter value is set to `1` in `Invoke-AzureDtlCseLinux.ps1`.
> 5. Execute `Invoke-AzureDtlCseLinux.ps1`. After completion, verify that a directory called `share` is created under `/tmp`.
> 6. Navigate to `/var/log/azure/Microsoft.OSTCExtensions.CustomScriptForLinux/1.5.2.1`
> 7. Observe that file `extension.log` exists and its contents show the message from the script.
> 8. Remove the directory `/tmp/share'
> 9. Change the `$AgentVersion` parameter value from `1` to `2` in `Invoke-AzureDtlCseLinux.ps1` and execute again.
> 10. Observe that directory `share` is not created under `/tmp/`, as expected.
> 11. Navigate to /var/log/azure/Microsoft.Azure.Extensions.CustomScript/2.0.2`.
> 12. Observe that file `extension.log` DOES NOT exist.

In addition, there's no extension message returned when the deployment is created via API, which worked before.

We rely on this functionality to allow end users to know what happened with their extensions. Because of other issues explained in #290, we are unable to use an earlier version.

I've reviewed the other logs that I know of, trying to get a sense of what may be failing. The deployment completes successfully, but I observe that no directory is created. Any help would be greatly appreciated.

**Comment by boumenot** [comment]
Is the bug against Microsoft.OSTCExtensions.CustomScriptForLinux or Microsoft.Azure.Extensions.CustomScript?  This repository is for the former.

**Comment by leovms** [comment]
Microsoft.Azure.Extensions.CustomScript, as indicated in steps 11 & 12.

**Comment by boumenot** [comment]
Please move the issue over to https://github.com/Azure/custom-script-extension-linux/.
