### ISSUE TITLE
Whenever CentOS 7.2 VM whose OS diagnostics is enabled is rebooted, “rsyslogd-3000: omazuremds error at connect(). errno=No such file or directory” is logged in /var/log/message.

### ISSUE THREAD

**Issue by FumiakiNagano** [Azure/azure-linux-extensions#341]
Whenever CentOS 7.2 VM is rebooted, “rsyslogd-3000: omazuremds error at connect(). errno=No such file or directory” is logged in /var/log/message.
Is this error ignorable? 
If yes, is there a way to stop logging the error message?

Repro steps:
1. Create a CentOS 7.2 VM whose Guest OS diagnostics is Enabled.
 
![image](https://cloud.githubusercontent.com/assets/19259662/22977213/16ab3b5a-f3d1-11e6-82b0-255d862b2b4d.png)

2. ssh to the created VM
3. open /var/log/message
4. “Feb 15 13:44:00 cent72test1 rsyslogd-3000: omazuremds error at connect(). errno=No such file or directory” is logged
5. Reboot the VM
6. Again, “Feb 15 13:46:04 cent72test1 rsyslogd-3000: omazuremds error at connect(). errno=No such file or director” is logged

**Comment by hosungsmsft** [comment]
This error message should happen only temporarily and should be ignored in that case. To stop logging this error message, code change on our rsyslog module is required. There's no configuration that disables this logging. We'll discuss if this logging can be removed from code, as this has been asked more than once.

**Comment by hosungsmsft** [comment]
@FumiakiNagano , we released LAD 3.0, which happens to address this issue by no longer using our omazuremds rsyslog module but using the open-source Fluentd for syslog collection, so would you please try it by following instructions [here ](https://github.com/Azure/azure-linux-extensions/blob/lad-3.0.101/Diagnostic/virtual-machines-linux-diagnostic-extension-v3.md#configuring-and-enabling-the-extension-for-azure-portal-metrics-charting-experiences) and let us know? You'll need to first uninstall the existing LAD 2.3 from Azure Portal or using Azure CLI.

I'm closing this comment with the release of LAD 3.0 and this notification. Please let us know if you have any issues with LAD 3.0. Thanks for your patience.

**Comment by hosungsmsft** [comment]
@liambarnett -- It's been a really long while since I last worked on this, and I don't even know who owns this any more and the status of this extension in Azure. Your best bet would be to open a new issue here or contact Azure customer support. Sorry for not being of any help.
