### ISSUE TITLE
[DSC] Oracle Linux left out in distro validation check

### ISSUE THREAD

**Issue by michael1w** [Azure/azure-linux-extensions#355]
Docs include Oracle Linux as supported:
https://github.com/Azure/azure-linux-extensions/tree/master/DSC#4-supported-linux-distributions

But it fails when provisioning the extension on lines 101-110 as 'oracle' is not one of the valid distro names in the validation check:
https://github.com/Azure/azure-linux-extensions/blob/master/DSC/dsc.py

If I run the following
`python`
`platform.dist()`
I get
`('oracle', '7.2', '')`

If Oracle Linux is actually supported, this may be a very quick fix, but I'm not sure if it was intentional.

**Comment by balukambala** [comment]
Hi Michael,

I am sorry for inconvenience. I will fix this issue soon and update the thread.

sincerely,
Bala subrahmanyam kambala

**Comment by michael1w** [comment]
Hi balukambala, is this fix still going ahead?

Michael

**Comment by michael1w** [comment]
Any news? I see the function is now on line 108 (look for get_distro_category()).

This just needs an additional condition
`or distro_name == 'oracle':`
on line 113, so it will execute
`        return DistroCategory.redhat`

and some testing

**Comment by balukambala** [comment]
Hi, 

Sorry for the delay. We have released the fix to support Oracle distros in 2.5 version. Please let us know if you still face issues.
