### ISSUE TITLE
Azure vmaccessforlinux 

### ISSUE THREAD

**Issue by opencloudcode** [Azure/azure-linux-extensions#357]
I just deployed a redhat machine. Is there a way where I can delete VM access? So that password can not be reset on the portal?

**Comment by boumenot** [comment]
I usually use the CLI.

```text
azure extension set --uninstall <resource-group> <vm-name> <name> <publisher-name> <version>
```

HTH

**Comment by opencloudcode** [comment]
I dont have the extension on the machine.
