### ISSUE TITLE
Unable to get disk utilization details of Azure Linux and windows VMs

### ISSUE THREAD

**Issue by navya-goli** [Azure/azure-linux-extensions#378]
Hi,

I enabled the diagnostics settings of azure windows and Linux VMs.

I am able to get disk free space for only windows VM but not Linux from the storage account.

I need to extract disk used, disk available and disk total metrics of both Linux and windows VMs.

Please provide me the assistance to extract the above-mentioned metrics.

Thanks.

**Comment by hosungsmsft** [comment]
Thanks for your feedback. Unfortunately, the currently available Linux Azure Diagnostic extension version 2.3 doesn't easily allow reporting disk capacity-related metrics (only bytes/sec or total bytes metrics available). However, the new Linux Azure Diagnostic extension version 3.0 that'll be published soon (in a few weeks as a public preview) will definitely support these disk-related metrics for customers. Please check back with us on LAD 3.0 in a few weeks and give it a try at that time. The status of LAD 3.0 release will be announced through README.md in Diagnostic directory of this GitHub repo. Thanks.

**Comment by hosungsmsft** [comment]
We'll keep this issue opened until we release LAD 3.0, and close it once customer confirms that disk capacity-related metrics are available for them.

**Comment by hosungsmsft** [comment]
@navya-goli , we just released LAD 3.0 that supports disk free space on Linux VMs. Would you please try it by following instructions at [here](https://github.com/Azure/azure-linux-extensions/blob/lad-3.0.101/Diagnostic/virtual-machines-linux-diagnostic-extension-v3.md#configuring-and-enabling-the-extension-for-azure-portal-metrics-charting-experiences)? Please note that you'll need to uninstall the existing LAD 2.3 first. You can do that from the Azure Portal or using Azure CLI.

I'm closing this issue with the release of LAD 3.0 and this notification. Please reactivate this comment if you still have issues. We'd be also very grateful if you let us how it goes. Thanks for your patience.
