### ISSUE TITLE
[LAD] RunCmd /opt/omi/bin/service_control is-running Error Code 1 should not be logged as error

### ISSUE THREAD

**Issue by craiglandis** [Azure/azure-linux-extensions#395]
/opt/omi/bin/service_control is-running deliberately returns 1 if the process is running, 0 if not. This shouldn’t be logged as an error. 

2017/06/07 17:15:48 [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.107] RunCmd /opt/omi/bin/service_control is-running
2017/06/07 17:15:48 ERROR:CalledProcessError.  Error Code is 1
2017/06/07 17:15:48 ERROR:CalledProcessError.  Command string was /opt/omi/bin/service_control is-running
2017/06/07 17:15:48 ERROR:CalledProcessError.  Command result was

**Comment by RaghavendraP** [comment]
Hi,

I am getting this error while deploying azure linux diagnostic 3.* using ARM templates. Is there a workaround for this? 

Thanks,
Raghavendra.

**Comment by abhijeetgaiha** [comment]
The error doesn't show up in recent LAD releases.
