### ISSUE TITLE
Content of /etc/fstab changed after encryption, expected or not?

### ISSUE THREAD

**Issue by PatLac04** [Azure/azure-linux-extensions#402]
Created a CentOS 7.3 VM with a datadisk, partitioned and mounted the datadisk. Here is my /etc/fstab after mounting the data disk.

![image](https://user-images.githubusercontent.com/25445601/27032273-23eef384-4f42-11e7-923d-366b2bd3d400.png)

Disabled SELinux, rebooted
Encrypted ALL disks with "az vm encryption enable". Wait for 90 minutes or so...

Content of /etc/fstab after encryption : 

![image](https://user-images.githubusercontent.com/25445601/27032373-83b1e11e-4f42-11e7-97c7-5fbbafe328d3.png)

The entry I added for my datadisk is gone but data disk is still mounted on /data and seems mapped properly 
![image](https://user-images.githubusercontent.com/25445601/27032440-ca54241a-4f42-11e7-8177-ccce2dc77740.png)

Is this the expected behavior?

**Comment by jasonzio** [comment]
Are you also using the Linux Diagnostic Extension? Or is VM Encryption the only extension you're using?

**Comment by PatLac04** [comment]
Hi Jason,   I'm not using the Linux VM Extension but I think it might be appropriate to use so will take the time to add it in my template.

Will this provide diagnostic info related to Disk Encryption ?

**Comment by jasonzio** [comment]
No, it will not provide additional information about Disk Encryption.

The reason I asked: The diagnostic extension keeps an eye on /etc/fstab changes to try to keep users from making changes that render their VM unbootable. If you were using the Diagnostic Extension, I’d have suggested checking its logs to see if it was getting in your way. Since you’re not using it, it’s a moot point.

You might want to look at the logs for the Disk Encryption extension; see /var/logs/azure and descend into the directory that’s associated with your version of the Disk Encryption extension.

If you continue to have issues, you should probably raise a support incident with Microsoft Azure support.

**Comment by PatLac04** [comment]
Thanks for your help @jasonzio, I went and looked at the content of the log for the Azure Disk Encryption in /var/logs/azure and found the following:
```
2017/06/13 21:18:09 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] msg: Encrypting data volume 1/1: 100%
2017/06/13 21:18:09 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] substatus: {"os": "EncryptionInProgress", "data": "EncryptionInProgress"}
...
...
2017/06/13 21:18:09 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1147: [Info] Executing: /usr/bin/mount /dev/mapper/d8bf6e92-eb6b-4784-aff8-22ff77cd014e /data
2017/06/13 21:18:09 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1147: [Info] removing entry for unencrypted drive from fstab
2017/06/13 21:18:09 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1147: [Info] removing fstab line: UUID=99fbe708-1ba4-4c59-b9b4-6ab1ffe87f12 /data                   ext4    defaults
        0 2
2017/06/13 21:18:09 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1147: [Info] fstab updated successfully
2017/06/13 21:18:09 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1147: [Info] fstab.azure.backup updated successfully
2017/06/13 21:18:09 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1147: [Info] archive the config file: /var/lib/azure_disk_encryption_config/azure_crypt_ongoing_item.ini
```
So now, at least I have confirmation that the Encryption extension makes the change in the /etc/fstab file.

Thanks!

**Comment by jasonzio** [comment]
Does this resolve your issue, or was there more to it?

**Comment by PatLac04** [comment]
I wasn't sure it was an issue or an expected behavior.  So now, it reassures me that this is not an issue caused by encrypting the disks but an expected behavior of the extension.  I think it would be worth mentioning it in the documentation since unexpected changes to the /etc/fstab is a bit scary.
