### ISSUE TITLE
File not found exception when trying to download example from Readme.md

### ISSUE THREAD

**Issue by invisibleaxm** [Azure/azure-linux-extensions#404]
The readme file has the following text which points to a download of a sample settings file, however the file does not exist: https://github.com/Azure/azure-linux-extensions/blob/master/Diagnostic/tests/lad2_3_compatible_portal_pub_settings.json

'''Please refer to this document for more details on configuring and using LAD 3.0. tests/lad2_3_compatible_portal_pub_settings.json contains a sample JSON configuration which sets LAD 3.0 to collecting exactly the same metrics and logs as the default configuration for LAD 2.3 collected.
'''

**Comment by jasonzio** [comment]
Thanks - I'll get this fixed as quickly as I can.

**Comment by jasonzio** [comment]
Too small a change to be worth a PR and review; I just changed and committed. Done. Thanks again.
