### ISSUE TITLE
waagent 2.2 fails because extension expects waagent2.0 in /usr/sbin/waagent

### ISSUE THREAD

**Issue by reyk** [Azure/azure-linux-extensions#411]
Hello,

I ported WALinuxAgent to OpenBSD and this has been merged into version 2.2.13.

But the agent fails when it tries to run the linux diagnostics extension, when it is enabled in the VM. The reason can be found in the extension code of WAAgentUtil.py: it expects the old waagent2.0 to be in /usr/sbin/waagent and aborts with an Exception("Can't load waagent."). The VM never enters Running state because waagent (2.2.13) caught the exception.

https://github.com/Azure/azure-linux-extensions/blob/master/Utils/WAAgentUtil.py#L28
https://github.com/Azure/azure-linux-extensions/blob/master/Utils/WAAgentUtil.py#L42

Possible fixes:
- Terminate without error if /usr/sbin/waagent is not found, to ignore it in waagent
- Do NOT assume that waagent2.0 is installed in /usr/sbin/waagent, search more directories.
- Include a copy of waagent2.0 in the extension itself (eg. as Util.waagent2)

OpenBSD never puts non-base packages in /usr, the prefix for such packages is always /usr/local, so the preferred location for the old agent would be /usr/local/sbin/waagent2.0.

Our current **WORKAROUND** is to install waagent2.0 in /usr/local/lib/python2.7/site-packages/waagent and to set PYTHONPATH accordingly. This kind of makes sense because waagent is used as a module, but it is a horrible hack. This allows to run the extension to let it figure out that the OS "distro" is not supported.

Reyk

**Comment by jasonzio** [comment]
Please re-try with the latest version of LAD (2.3.9027 or 3.0.109), which both now incorporate the chunks of waagent they need. However, please note that LAD is the Linux Diagnostic Extension; that's not going to work on OpenBSD, since both versions of LAD rely on a Linux binary (mdsd).
