### ISSUE TITLE
Custom script extension issue - not everything in the script executed

### ISSUE THREAD

**Issue by yueguoguo** [Azure/azure-linux-extensions#418]
Hi all,

I used ARM template for extension installation with custom script as follows:  

```
#!/bin/bash

Rscript -e 'library(devtools);devtools::install_github("rstudio/reticulate");devtools::install_github("gaborcsardi/debugme");source("https://install-github.me/MangoTheCat/processx");devtools::install_github("rstudio/keras")'

mkdir ~/.keras

echo '{"floatx":"float32","image_data_format":"channels_last","epsilon":1e-07,"backend":"cntk"}' > ~/.keras/keras.json

echo 'Sys.setenv(KERAS_BACKEND="cntk")' > .Rprofile
echo 'Sys.setenv(KERAS_PYTHON="/anaconda/envs/py35/bin/python3.5")' >> .Rprofile

rstudio-server start
```

The installation was successful however it seems not everything in the script was executed. That is, the first part where some R libraries are installed works, but the files (i.e., ~/.keras/keras.json and .Rprofile) I wanted to create did not exist in the end...

Sys info:
* Linux distro Ubuntu 16.04.2 LTS. 
* Api_version is “2016-04-30-preview”
* Type_handler is “1.5”
* Publisher is “Microsoft.OSTCExtensions”
* Extension type is “CustomScriptForLinux”.

Appreciate any help!

**Comment by jasonzio** [comment]
The naked tilde (~) in the paths you specifies to the commands in your script means "the home directory of the logged-in user". As I recall, CSE runs as root, so those directories would have been created in /home/root (e.g. /home/root/.keras/keras.json, /home/root/.Rprofile). If you meant those to be in the home directory of some specific user other than root, you should specify that explicitly.

Also, we strongly recommend you upgrade to using CSE version 2.x, which is substantially more robust and supports more Linux distros.

**Comment by yueguoguo** [comment]
Hi Jason very much appreciate the explanation. This is very helpful! I am closing the issue and reopen if there is any follow-up question.
