### ISSUE TITLE
unable to execute CSE on ubuntu 14.04

### ISSUE THREAD

**Issue by kailashms** [Azure/azure-linux-extensions#422]
Hi All,
I am running CSE on ubuntu 14.04 with correct commands but still i the CSE is not getting executed.

Below are the errors:

2017/07/14 13:14:37.628553 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Expected handler state: enabled
2017/07/14 13:14:37.642222 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Current handler state is: NotInstalled
2017/07/14 13:14:37.656114 ERROR [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Failed to set state: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1/config/HandlerState'
2017/07/14 13:14:37.679988 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Download extension package
2017/07/14 13:14:37.730462 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Unpack extension package
2017/07/14 13:14:37.752312 INFO Event: name=Microsoft.OSTCExtensions.CustomScriptForLinux, op=Download, message=Download succeeded

The errors reported and i am able to reproduce the same in my vm.

from the extension log , we could see these errors:

2017/07/15 09:22:54 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Config decoded correctly.
2017/07/15 09:22:54 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Will try to download files, number of retries = 10, wait SECONDS between retrievals = 20s
2017/07/15 09:22:54 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] fileUris value provided is empty or invalid. Continue with executing command...
2017/07/15 09:22:54 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Succeeded to download files, retry count = 0
2017/07/15 09:22:54 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Internal DNS is ready, retry count = 0
2017/07/15 09:22:55 ERROR:[Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Command returned an error.
2017/07/15 09:22:55 ERROR:---stdout---
2017/07/15 09:22:55 ERROR:
2017/07/15 09:22:55 ERROR:---errout---
2017/07/15 09:22:55 ERROR:sh: 0: Can't open script.sh
2017/07/15 09:22:55 ERROR:
2017/07/15 09:22:55 ERROR:
2017/07/15 09:22:55 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Daemon,failed,127,Command returned an error.
2017/07/15 09:22:55 ---stdout---
2017/07/15 09:22:55
2017/07/15 09:22:55 ---errout---
2017/07/15 09:22:55 sh: 0: Can't open script.sh
2017/07/15 09:22:55
2017/07/15 09:22:55
root@ubuntu14:/var/log/azure/Microsoft.OSTCExtensions.CustomScriptForLinux/1.5.2.1#

Is there any bug in this version?
is there any other we can deploy the CSE?

Thank,

Kailash B

**Comment by boumenot** [comment]
I am not sure what your issue is, but the error message it can't open script.sh.  Does the file exist on disk?  Have you verified the command you're attempting to execute works?

Is there any reason you're not using CustomScript 2.0?  I don't think that will fix the issue, but 2.0 is the way forward.

**Comment by kailashms** [comment]
Hi Christopher,

Thanks for the update.

We are trying to install CSE to resolve Firewall issue in a VM but it was failing with those errors.

We tried with 2.0 also, in my test vm it is working fine, for the cx it is not working.
Its throwing the error. PFA the same.

    Regards,
Kailash B
Microsoft Azure Linux Support
Support Engineer

Working Hours:
Working Days:
Email:
Manager:
Office Phone:

13:00 – 22:00 IST
Tuesady-Saturday
v-kaib@microsoft.com<mailto:v-kaib@microsoft.com>
v-madka@microsoft.com
+91 40 67230000
  Ext: 32030

**Comment by kailashms** [comment]
Hi Team,

From the portal when you are installing CSE, we are getting 1.5.2.1 version and doesn’t work out.
For that we are using the Powershell with 2.0 and it works.

Why from the portal it is installing 1.5.2.1 version? And it is failing
It should come up with the latest version?

    Regards,
Kailash B
Microsoft Azure Linux Support
Support Engineer

Working Hours:
Working Days:
Email:
Manager:
Office Phone:

13:00 – 22:00 IST
Tuesady-Saturday
v-kaib@microsoft.com<mailto:v-kaib@microsoft.com>
v-madka@microsoft.com
+91 40 67230000
  Ext: 32030

**Comment by boumenot** [comment]
@kailashms please trim your message when posting to GitHub.  It seems like 3 lines out of 50 contain the issue, which makes it harder to understand the problem.

I am very confused by your response.  You mention Linux, which has Microsoft.OSTCExtensions.CustomScriptForLinux, and then you mentioned PowerShell.  PowerShell implies Windows to me, not Linux.  If you want custom script for Windows it is called Microsoft.Compute.CustomScriptExtension.

**Comment by kailashms** [comment]
Hi All,

Let me clarify all the queries.


1.       I am having a Linux virtual machine and it has ran into an issue.

2.       In order to resolve the issue, I need to pass CustomScriptExtension to the vm.

3.       When we pass the CSE, by default we could see the version:1.5.2 is being installed but it is failing to run the commands in the script.

4.       We did the testing with both working commands and non-working commands

5.       So tried with PowerShell and we used 2.0 version and it resolved issue.

By default from the portal, by still is taking the older version of 1.5.2 version of CSE, when the new versions are already available.
Can you please look into this ?


    Regards,
Kailash B
Microsoft Azure Linux Support
Support Engineer

Working Hours:
Working Days:
Email:
Manager:
Office Phone:

13:00 – 22:00 IST
Tuesady-Saturday
v-kaib@microsoft.com<mailto:v-kaib@microsoft.com>
v-madka@microsoft.com
+91 40 67230000
  Ext: 32030

**Comment by jasonzio** [comment]
The change from 1.5.x to 2.0 is a major version change, and automatic update across major versions is not supported. Your PowerShell command to install the extension must specify at least the major number. That's why you didn't get the new version "by default"; you have to explicitly request 1.x or 2.x in your command.

Version 2.0 of CSE is intended to replace 1.5.x. Since you've solved your problem by upgrading to version 2.0 of the extension, I'm going to close this issue.
