### ISSUE TITLE
[VMAccess] users created are not listed under user group sudo

### ISSUE THREAD

**Issue by z01c** [Azure/azure-linux-extensions#439]
According to the security notes - 
VMAccess Extension is designed for regaining access to a VM in the event that access is lost.
Based on this principle, **it will grant sudo permission to the account specified in the username field**.

However, users created are not listed under user group sudo.

Related log from /var/log/azure/Microsoft.OSTCExtensions.VMAccessForLinux/1.4.7.0/extension.log -

2017/08/10 22:55:13 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.0] sequence number is 1
2017/08/10 22:55:13 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.0] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.0/config/1.settings
2017/08/10 22:55:13 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.0] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettingsCertThumbprint": "92D202B54029919C6CCF3D2FA28D982802
8D33BC", "publicSettings": {"abdtest4": "abdtest4", "abdtest3": "abdtest3"}, "protectedSettings": "MIICCQYJKoZIhvcNAQcDoIIB+jCCAfYCAQAxggFpMIIBZQIBADBNMDkxNzA1BgoJkiaJk/IsZAEZFidXaW5kb3dzIEF6dXJlIE
NSUCBDZXJ0aWZpY2F0ZSBHZW5lcmF0b3ICEF5Nbcu7WHO2TteXpTszAbUwDQYJKoZIhvcNAQEBBQAEggEAkqouF/FJs9lE92G6q7Dy/Qz2gJK/ZUlks1cm3KGcVxOLd3fazDdZ3eygevN1tjr5uUAStgMI0jUcyQUxwQmnEFpDPy3o+u/p91qvx3qwmEgdUiQldA4
c89oQT8SM1C/VpyDY5J6YT3dumZD3HOsl5QhLchbOZ79dWwB2XD27+a5rmZut+Pk7HFD7BOCooOnL0rR3sNxvn+y2L3iYM3M9GL3rny4qEeAIVMItjsVdJy37lKHN2fOhBq5p18IwuT5VsBoczD8IFWaZ/OZol33R9bvF0Bv4UPUv4+4CWHqvwIBNhtNSP3faDNrZ
u/wed0iNFkhiLpyvjafGUR4pcfvRbDCBgwYJKoZIhvcNAQcBMBQGCCqGSIb3DQMHBAiW19gPnQBpRYBgL710sEcJaUS3XFIvFiVlf86E8sFABxmCytoXSX8buHhcFQ3TlXPpNqlrXo8spHcnnIl7zgEi2CSEWHIw5h0h/uMBC9RgNt0KXsIeMqJxB60s352PSk/Pn
d5cjg8cs2cp"}}]}
2017/08/10 22:55:13 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.0] Config decoded correctly.
2017/08/10 22:55:13 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.0] set most recent sequence number to 1
2017/08/10 22:55:13 ERROR:unicode argument without an encoding occured creating /var/lib/waagent/CustomData
2017/08/10 22:55:13 Change user password
2017/08/10 22:55:13 Created user account: abdtest4
2017/08/10 22:55:13 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.0] Succeeded in create the account or set the password.
2017/08/10 22:55:13 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.0] Enable,success,0,Enable succeeded.

Running _getent group sudo_ shows that _abdtest4_ is not a part of _sudo_ -
sudo:x:27:testuser,hdiuser

Target OS Version: Ubuntu 16.04

**Comment by boumenot** [comment]
Thanks for opening an issue.  

The question is does the user have sudo access or not.  Regardless if the user is added to the sudo group or not does not necessarily determine if the user can sudo.  Rights can be granted regardless of the group.  VMAccessForLinux just adds a user to /etc/sudoers.d/waagent.  Please confirm and let me know if your account has rights or not.

**Comment by z01c** [comment]
Thanks for quick response. The issue is that CSS uses the JIT process to access customer clusters when consent is true. Currently they are not able to ssh to the customer cluster (only secured HDI) by using the user credential generated by ACIS. Recently there was an additional parameter (allowedGroups) added in the sshd config and it's only restricted to sudo user group. As the user being created with ACIS (which uses VMAccess extension internally) are not under sudo user group, they are not able to use this user to access the cluster to troubleshoot. Thanks.

**Comment by boumenot** [comment]
Is there an issue with VMAccess in this case?  It sounds like you want VMAccess to add a user to a group, but that isn't the way it works.

**Comment by z01c** [comment]
My idea was to add the user to user group sudo via ACIS (VMAccess extension). But if that's not something feasible we might have to think of some other way. One last question before we close this issue, adding the user to a user specified group - can this be a possible future feature request? Thanks.

**Comment by boumenot** [comment]
I am more than happy to accept a PR that adds a user to a group.

**Comment by z01c** [comment]
Thanks a lot for the green signal. I will discuss with my team about the possible options and come back with a PR if we decide to go this route. Thanks.
