### ISSUE TITLE
Delete existing SSH key with VMAccess

### ISSUE THREAD

**Issue by vladfr** [Azure/azure-linux-extensions#468]
Hi!

I'd like to use the VMAccess extension to rotate SSH keys on a regular basis. The problem is that when running in a VMSS, I need it to delete the original ssh key added at vmss creation.

Right now, the vmaccess extension only adds a key, it doesn't remove existing keys, so I cannot use it to rotate keys.

**Comment by boumenot** [comment]
This is not a function that VMAccess was intended to serve.

If you would like to do key rotation you will need to use another tool.  Of the top of my head, I would suggest using the Custom Script extension to delete all keys, and then use VMAccess to install a new one (or use Custom Script).  It seems rather heavy weight, and there is probably a better solution.
