### ISSUE TITLE
Cant create user on FreeBSD pfsense image

### ISSUE THREAD

**Issue by idelix** [Azure/azure-linux-extensions#473]
Hello, 

I created Vm using the following image, with freeBSD as underlying OS:

$PublisherName = "netgate"
$OfferName = "pfsense-fw-vpn-router"
$Sku = "pfsense-azure-234p1"
$Version = "latest"

When I try to execute script below the command stuck and never finish also I get following in the log file

2017/10/05 11:50:23.985319 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Target handler state: enabled
2017/10/05 11:50:24.000470 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] [Enable] current handler state is: notinstalled
2017/10/05 11:50:24.144021 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Initialize extension directory
2017/10/05 11:50:24.156793 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Update settings file: 2.settings
2017/10/05 11:50:24.169127 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Install extension [./vmaccess.py -install]
2017/10/05 11:50:25.403236 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Remove extension handler directory: /var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1

Command:

$RGName = '<...>'
$VmName = '<...>'
$Location = '<...>'

$ExtensionName = 'VMAccessForLinux'
$Publisher = 'Microsoft.OSTCExtensions'
$Version = '1.4'

$PublicConf = '{}'
$PrivateConf = '{
  "username":"<...>",
  "password":"<...>",
  "expiration":"2018-01-01"
}'

Set-AzureRmVMExtension -ResourceGroupName $RGName -VMName $VmName -Location $Location `
  -Name $ExtensionName -Publisher $Publisher -ExtensionType $ExtensionName `
  -TypeHandlerVersion $Version -SettingString $PublicConf -ProtectedSettingString $PrivateConf

**Comment by boumenot** [comment]
Sorry, but we do not currently support FreeBSD.
