### ISSUE TITLE
"No CentralJson blob path field value found for field name resourceId" error

### ISSUE THREAD

**Issue by AndreyPoturaev** [Azure/azure-linux-extensions#483]
Hi, i trying LAD on Ubuntu 16.04 with this simple config
public:
`  {
    "StorageAccount": "jlogs",
    "sampleRateInSeconds": 15,
    "fileLogs": [
      {
        "file": "/home/javaadmin/app.log",
        "sinks": "myblob"
      }
    ]
  }`
private:
`{
    "storageAccountName" : "jlogs",
    "storageAccountSasToken": "XXX",
    "sinksConfig": {
      "sink": [
        {
          "name": "LinuxEH",
          "type": "EventHub",
          "sasURL": "XXXX"
        },
        {
            "name": "myblob",
            "type": "JsonBlob"
        }
      ]
    }
}`

And it doesn't work.
Error in extension.log is
> 
2017/10/31 20:04:51 [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.109] Daemon,success,0,Invalid mdsd config given. Can't enable. This extension install/enable operation is reported as successful so the VM can complete successful startup. Linux Diagnostic Extension will exit. Config validation message: 2017-10-31T20:04:51.7984980Z: OboDirectPartitionField with name='resourceId' not found. Make sure the mdsd.xml includes the corresponding Management/OboDirectPartitionField element. Returning an empty string as the result value.
2017/10/31 20:04:51 2017-10-31T20:04:51.7986420Z: No CentralJson blob path field value found for field name resourceId. Make sure that your mdsd config XML contains OboDirectPartitionField element with the corresponding field name attribute in Management/Identity section.
2017/10/31 20:04:51 2017-10-31T20:04:51.7986970Z: GetBatch([unknown]myblobVer2v0) failed to create new batch for : No CentralJson blob path field value found for field name resourceId. Make sure that your mdsd config XML contains OboDirectPartitionField element with the corresponding field name attribute in Management/Identity section.
2017/10/31 20:04:51 Parse reported these messages:
2017/10/31 20:04:51 /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.109/xmlCfg.xml(25) Error: Unable to create routing for this event
> 

SaS token for storage account is 100% correct.
What i did wrong?

P.S LAD version is 3.0.109

**Comment by hosungsmsft** [comment]
The JsonBlob sink type still requires the "resourceId" definition in the following path of the public settings: "ladCfg" - "metrics" - "resourceId". Please refer to the [relevant section](https://github.com/Azure/azure-linux-extensions/blob/master/Diagnostic/virtual-machines-linux-diagnostic-extension-v3.md#metrics) of the documentation and the [example ](https://github.com/Azure/azure-linux-extensions/blob/master/Diagnostic/virtual-machines-linux-diagnostic-extension-v3.md#an-example-lad-30-configuration)for this requirement. Please reactivate this issue if adding resourceId correctly still doesn't solve this issue. Thanks.
