### ISSUE TITLE
Update Powershell commands - Get-AzureRmVM vs Get-AzureVM

### ISSUE THREAD

**Issue by isamllr** [Azure/azure-linux-extensions#493]
Could you please update the Powershell commands to use ARM deployment model?
For example Get-AzureRmVM instead of Get-AzureVM

**Comment by boumenot** [comment]
This is not the correct repo for PowerShell cmdlets.  I think you want https://github.com/Azure/azure-powershell.

**Comment by isamllr** [comment]
I was referring to the Known Issues section in the README of this repo - but it might be the issue only occurs when using the classic model vs ARM model, so there is no need to fix this when using the ARM model.
