### ISSUE TITLE
Need for automatic injection of vmResourceId for Linux extension

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/azure-linux-extensions#495]
“vmResourceId” property is only populated through protected json configuration when deploying extension using ARM template, Azure CLI or Powershell cmdlets.

Windows extension has the ability to automatically infer the vmResourceId when it's missing and push this information into OMS.  This information is retrieved through the Metadata Service on Windows.

Having the ability to group data by resource group in OMS simplifies reporting and alerting needs.

Opening this as an issue w/ the linux extension since it's deviating from how Windows extension works today.

**Comment by jasonzio** [comment]
The VM resourceId is not yet reliably available via IMDS for Linux IaaS VMs. (I'm also not at all certain that Windows IaaS VMs can reliably obtain the VM resourceId via IMDS).

- There are challenges associated with moving VMs to a different resource group
- Reporting the right resourceId for VMs in a VMSS is hard. Some extensions need the individual VM resourceId; others need the VMSS resourceId.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of deprecation, open issues and pull requests will be closed.
