### ISSUE TITLE
Failed  to set up Linux diagnostic extension v 3.0. 

### ISSUE THREAD

**Issue by egor-moroz** [Azure/azure-linux-extensions#498]
Failed to set up mdsd dependencies: setup_omsagent(): Failed at restarting omsagent (fluentd). Exit code=1, Output=control_omsagent(restart) failed. Output: INFO: Configuring OMS agent service LAD ..

**Comment by jasonzio** [comment]
If you're also using the OMS Extension (omsagent), there appears to be an incompatibility between the two. That was definitely the case for version 1.4.1-123 of omsagent, but there may still be an issue with 1.4.2-124. We expect to correct this in the next release of LAD 3.0 so that it will install and work correctly with the latest OMS extension.

**Comment by jasonzio** [comment]
Dupe #488

**Comment by arbaiti** [comment]
I'm trying to deploy the LAD VERSION 3.0.111 and i got the same error

**Comment by carct** [comment]
i`m also getting this:
`Failed to set up mdsd dependencies: omsagent setup failed 5 times. Last exit code=3, Output=setup_omsagent_for_lad(): fluentd out_mdsd plugin install failed. Output: /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rubygems/safe_yaml (LoadError) from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems.rb:702:in `load_yaml' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run' from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/bin/fluent-gem:6:in `<top (required)>' from /opt/microsoft/omsagent/ruby/bin/fluent-gem:23:in `load' from /opt/microsoft/omsagent/ruby/bin/fluent-gem:23:in `<main>'
HANDLER STATUSReady
HANDLER STATUS LEVELInfo`

from 
TYPE Microsoft.Azure.Diagnostics.LinuxDiagnostic
VERSION 3.0.117

Other extensions present related to this:
- DependencyAgentLinux: VERSION 9.7.3.1475
- OmsAgentForLinux: VERSION 1.8.9

**Comment by Firlotte** [comment]
We're seeing the same issue here with LAD 3.0.119 (provisioning failed) and OAL 1.9.1 (provisioning succeeded)

STATUS MESSAGE Failed to set up mdsd dependencies: omsagent setup failed 5 times. Last exit code=3, Output=setup_omsagent_for_lad(): fluentd out_mdsd plugin install failed.

**Comment by pierrejeandev** [comment]
Same issue with LAD 3.0.119 (provisioning failed) and OmsAgentForLinux 1.9.1  (provisioning succeeded)
STATUS MESSAGE Failed to set up mdsd dependencies: setup_omsagent(): Failed at restarting omsagent (fluentd). Exit code=1, Output=control_omsagent(restart) failed. Output:

**Comment by wenboyang214** [comment]
any update here ? I am getting the same issue

**Comment by Kavita-2703** [comment]
Any updates here ? We are facing the same error with LAD 3.0.119 (provisioning failed) and OMSAgentforLinux 1.10.5 (provisioning succeeded) 
Failed to set up mdsd dependencies: setup_omsagent(): Failed at restarting omsagent (fluentd). Exit code=1, Output=control_omsagent(restart) failed. Output: 

Even the earlier workaround of installing LAD first and then OMS is not working. 
LAD installation fails with above error. 

Please advice
