### ISSUE TITLE
Unable to enable Linux Diagnostics Extension as part of a self-contained Azure Resource Manager deployment

### ISSUE THREAD

**Issue by lawrencegripper** [Azure/azure-linux-extensions#503]
Hi, 

I've been trying to work out a way to do this for a little bit now, hopefully this is a simple one and I've missed something. I've written up my notes and would really appreciate any advise of thoughts. 

### Expected:

Create an ARM template to create the following, in order, using the 'DependsOn' syntax 
-	Storage Account
-	Linux VM
-	Linux Diagnostics Extension for VM using the newly created Storage Account 

### Problem:

In ARM there is no way to generate or get a SAS token for a Storage account. While the RP for Azure Storage has [ListAccountSas](https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/listaccountsas) this requires a body to be passed which isn't supported in ARM [list{Value}](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#listkeys) functions (See "Remarks" section "you cannot use list operations that require values in the request body").  

### Workarounds:

- Run one ARM template to create the storage account. Then run a script to create a SAS token. Then run another ARM template to create the VM passing in SAS and storage account name. 
- Pass a Service Principal into the ARM template and use the Script Extension to execute a script which will generate the SAS token then create the VM extension on all VMs

Both of these add a degree of complexity to a deployment and neither of these work for self-service style deployments using the "Deploy to Azure" button.

In my scenario the template is designed to enable researchers to easily create a cluster, the template is one click and returns them the SSH connection details to get started on the cluster. Thought the "Deploy to Azure" button they only need a browser and SSH. 

Another workaround I ruled out is to instruct users to go into the portal and enable diagnostics on all VMs post deployment, but I don't think you can enable this through the portal for VMSS instances. 

### Potential solutions:

1. Enable a choice of SAS of AcccountKey when configuring the extension
2. Update ARM to enable request body to be passed in list functions
3. Instruct users to create storage account using cloudshell in the browser and pass the values into the ARM template as parameters. [Do-able now]

Template: https://github.com/Azure/azure-quickstart-templates/pull/4081

**Comment by jasonzio** [comment]
Sadly, you're correct; at the moment, there's no way in a single deployment template to create the storage account and then to generate the SAS token LAD needs. The appropriate team is aware of the need.

We decided to drop support for passing the storage account Shared Key as the credential for LAD. Our security team was extremely uncomfortable with requiring us to persist an unlimited storage credential in a VM; if an attacker cracked a VM they would own everything in the storage account.

You're correct that the only viable approach, today, is to create the storage account in the initial deployment, then generate (via script) the necessary SAS token, then deploy LAD via a second, separate, template.

**Comment by lawrencegripper** [comment]
@jasonzio thanks for the quick response, I can understand the requirement around security. Would you be happy for me to propose an edit to the [docs page](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/diagnostic-extension) which clarifies this for other users?


> [!NOTE]
> When deploying the extension with an Azure deployment template the storage account, and a SAS token, must created beforehand and then passed to the template. You cannot deploy a VM, Storage account and configure LAD in a single template as there currently isn't support for creating a SAS token in a template.

**Comment by jasonzio** [comment]
That would be awesome. I would think it would appear in the [protectedSettings section](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/diagnostic-extension#protected-settings), just after the "how to generate a SAS using the portal" stuff.
