### ISSUE TITLE
Is there an ARM template resource definition for LAD3.0?

### ISSUE THREAD

**Issue by chriscoveyduck** [Azure/azure-linux-extensions#504]
I'm trying to deploy LAD3 using an ARM template created in VS2017.  See attached  
[AzureDeploy-LAD3.txt](https://github.com/Azure/azure-linux-extensions/files/1563372/AzureDeploy-LAD3.txt)

No matter what when I deploy the agent installs as "succeeded" but nothing is exported.  When I deploy from powershell using the same public and protected settings copied and pasted from the attached it deploys fine.

VS2017 doesn't have the LAD3 extension so hoping you have an example I can work from.

Thanks!

**Comment by runecalico** [comment]
Not exactly what you are looking for, but does this work for you?
https://github.com/mariuszdotnet/azure-vmss-templates/tree/master/vmss-linux-diagnostics

**Comment by jasonzio** [comment]
Note that you cannot construct the required SAS token within the template; you'll need to do that out-of-band and pass it to the template as a parameter. This is a known issue.
