### ISSUE TITLE
Unable to update SSH key on VMSS

### ISSUE THREAD

**Issue by agolomoodysaada** [Azure/azure-linux-extensions#505]
After running
```sh
az vmss extension set \
  --vmss-name myvmss \
  -g myresourcegroup \
  -n VMAccessForLinux \
  --publisher Microsoft.OSTCExtensions \
  --version 1.4 \
  --protected-settings "{\"username\":\"myuser\", \"ssh_key\":\"$(cat ~/.ssh/mykey.pub)\"}"
```
The command stalls at `- Running` indefinitely without ever returning. I was able to reproduce this on several VMSSs.

P.S. I do not have access to the VMs in the vmss so I cannot retrieve contents of the files:

- /var/log/azure/custom-script/handler.log
- /var/log/waagent.log

This used to work just fine. Any idea why the extension doesn't work anymore?

**Comment by boumenot** [comment]
Thank you for including the command you ran.  You can a command to invoke VMAccessForLinux not custom script.

**Comment by agolomoodysaada** [comment]
@boumenot I don't follow?

**Comment by boumenot** [comment]
From the command you ran, you have this.
```text
  -n VMAccessForLinux \
```

This is VMAccessForLinux.

You said 

> Any idea why the **custom script** doesn't work anymore?


Does that help?

**Comment by agolomoodysaada** [comment]
@boumenot I updated it to `extension`. Thanks for catching my typo

**Comment by boumenot** [comment]
You will need to provide more information for me to be able to debug this.  We monitor the health of this extension, and we see a 99.9% install success rate.  (The failures tend to be on non-endorsed Distros.)  You will need to include logs, distro/distro version, and anything else that might be relevant.

If this issue is particular to VMSS, please contact Azure support.

**Comment by agolomoodysaada** [comment]
We're not failing. We're just not getting any feedback whatsoever. We're running an Ubuntu VMSS supported distro. I can't get logs from a blackbox. Isn't this project owned by Azure? Why go through a different channel of communication if the extension isn't working? Does this extension for anything other than VMSSs?

**Comment by boumenot** [comment]
The request hanging is a failure.  If you cannot capture logs then I am sorry, but I cannot help you based on the information you have provided.  Please reactivate if you are able to get logs.
