### ISSUE TITLE
LAD 3.x:  How to update the SAS Token

### ISSUE THREAD

**Issue by runecalico** [Azure/azure-linux-extensions#511]
So I'm looking at a situation where we will be routinely (say once a year) be resetting the primary SA keys, this will of course invalidate the SAS token being used by LAD 3.x.  After my primary SA key has been changed, I can generate a new SAS token, but how am I supposed to update the LAD config?

Do I remove/redeploy the extension? (yuck), or is there something I can do via CLI?

Please Advise.

**Comment by abhijeetgaiha** [comment]
You can update the config by calling the "az vm extension set" command again with the new config as a parameter, as described in the docs. There is no need to remove the extension. The updated config is supplied to the extension and is picked up automatically.

**Comment by jasonzio** [comment]
Effectively, you "redeploy" the extension; the only thing you change is the SAS token. There's no other way to update any of the security credentials in the configuration other than redeploying the extension. You don't need to uninstall; just run "az vm extension set" as Abhijeet suggested.
