### ISSUE TITLE
Unable to download custom script from github: connection refused

### ISSUE THREAD

**Issue by PoisonousJohn** [Azure/azure-linux-extensions#513]
I'm trying to launch custom script from github but it's failing to download. Here's the vm template I'm using:

https://github.com/PoisonousJohn/AzureGameRoomsScaler/blob/2cd0bc7c1abbb43fb8a83feb8a0a617187324412/AzureGameRoomsScaler/vmDeploy.json#L126

File can't be downloaded using wget as well:

```
jp@nodeh34fmxpjab2wi:/var/log/azure/custom-script$ wget https://raw.githubusercontent.com/PoisonousJohn/AzureGameRoomsScaler/master/registerEnvVar.sh
--2018-01-19 17:26:17--  https://raw.githubusercontent.com/PoisonousJohn/AzureGameRoomsScaler/master/registerEnvVar.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Name or service not known.
wget: unable to resolve host address ‘raw.githubusercontent.com’
```
Here's the log:

time=2018-01-19T15:04:10Z version=v2.0.6/git@1008306-clean operation=enable seq=0 event="creating output directory" path=/var/lib/waagent/custom-script/download/0
time=2018-01-19T15:04:10Z version=v2.0.6/git@1008306-clean operation=enable seq=0 event="created output directory"
time=2018-01-19T15:04:10Z version=v2.0.6/git@1008306-clean operation=enable seq=0 files=1
time=2018-01-19T15:04:10Z version=v2.0.6/git@1008306-clean operation=enable seq=0 file=0 event="download start"
time=2018-01-19T15:04:10Z version=v2.0.6/git@1008306-clean operation=enable seq=0 file=0 retry=0 error="http request failed: Get https://raw.githubusercontent.com/PoisonousJohn/AzureGameRoomsScaler/master/registerEnvVar.sh: dial tcp: lookup raw.githubusercontent.com on [::1]:53: read udp [::1]:40255->[::1]:53: read: connection refused"

Previous versions without custom script extension didn't have any network problems.

**Comment by boumenot** [comment]
Wrong repo, you want Azure/custom-script-extension-linux.

CustomScript does not do anything special.  It makes an HTTP get request.  Based on the error message it appears that CustomScript cannot complete a DNS request.  Have you verified external connectivity?  Have you considered using the [script](https://github.com/Azure/custom-script-extension-linux#14-script) functionality, and bypassing the whole download in the first place?

If you still have issues please re-open in the correct repo.

**Comment by PoisonousJohn** [comment]
@boumenot sorry for misposting, and thank you for the suggestions.

**Comment by boumenot** [comment]
No worries, it is rather confusing. 😄
