### ISSUE TITLE
LinuxDiagnostic misidentifies itself in Guest Agent logs

### ISSUE THREAD

**Issue by jasonzio** [Azure/azure-linux-extensions#519]
When LAD starts up, it logs a message with the guest agent that it is handling the request. In diagnostic.py for 3.0, the line is
```
waagent.Log("LinuxAzureDiagnostic started to handle.")
```
The name of the extension, though is either Microsoft.OSTCExtensions.LinuxDiagnostic or Microsoft.Azure.Diagnostics.LinuxDiagnostic. For either case, the logged message should name the extension correctly:
```
waagent.Log("LinuxDiagnostic started to handle.")
```

**Comment by nikita-rastogi** [comment]
hey @jasonzio , please confirm following:
1. what is the expected correct log message:
a. waagent.Log("[_replace this bracket with either of the extension name_,
**Microsoft.OSTCExtensions.LinuxDiagnostic** or **Microsoft.Azure.Diagnostics.LinuxDiagnostic**.  ] started to handle.")
OR
b. waagent.Log("**LinuxDiagnostic** started to handle.")

**Comment by abhijeetgaiha** [comment]
It’s the second one, which is what we use when installing the extension.

**Comment by nikita-rastogi** [comment]
thanks @abhijeetgaiha.

**Comment by nikita-rastogi** [comment]
PR: https://github.com/Azure/azure-linux-extensions/pull/586

**Comment by jasonzio** [comment]
I'd suggest doing a survey of the other open-sourced extensions to see what they do. I'm pretty sure @boumenot once told me "there's no contract for that"; it's whatever the extension author wants it to be. If you want to be able to quickly distinguish between LAD 2.3 and LAD 3.x, you should make the name different between those two extensions.

**Comment by nikita-rastogi** [comment]
Checked the log message which other extensions log with waagent on their respective startup. They are using short extension names. eg.,
1. OSPatching logs "DSCForLinux started to handle"
2. OMSAgent logs "OmsAgentForLinux started to handle"
3. VMAccess logs "VMAccess started to handle"
4. DSC logs "DSCForLinux started to handle"

Hence, for LinuxDiagnostic, the message "LinuxDiagnostic started to handle." seems consistent.
