### ISSUE TITLE
mdsd.warn file growing exponentially

### ISSUE THREAD

**Issue by jdemchuk** [Azure/azure-linux-extensions#521]
Many of my Red Hat servers are running out of disk space, at it appears that the OMS agent is logging a tremendous amount of data to:
/var/log/azure/Microsoft.Azure.Diagnostics.LinuxDiagnostic/3.0.109/mdsd.warn

This file appear not to be a text file, and looks like an unreadable pile of XML and special escape characters.

How can I get to the bottom of what is causing this file to grow, so I can prevent it from using up all my disk space.  On one production server, the file was over 23 GB in size!  Here is a listing from a development server:

```[root@l0005u0d04ederm000000 3.0.109]# pwd
/var/log/azure/Microsoft.Azure.Diagnostics.LinuxDiagnostic/3.0.109
[root@l0005u0d04ederm000000 3.0.109]# ll
total 10076
-rw-r--r--. 1 root root      742 Feb  6 09:32 CommandExecution.log
-rw-r--r--. 1 root root   172425 Feb  9 07:49 extension.log
-rwxr-xr-x. 1 root root     9828 Feb  9 07:48 mdsd.err
-rwxr-xr-x. 1 root root    14842 Feb  9 07:49 mdsd.info
-rwxr-xr-x. 1 root root 10103115 Feb  8 17:58 mdsd.warn
[root@l0005u0d04ederm000000 3.0.109]#
```

**Comment by abhijeetgaiha** [comment]
Have you updated OMS recently? If you have, you might to restart the mdsd service: 
service mdsd-lde stop; service mdsd-lde start

**Comment by jdemchuk** [comment]
```
[root@l0005u0d04ederm000000 3.0.109]# service mdsd-lde stop
Redirecting to /bin/systemctl stop  mdsd-lde.service
Failed to stop mdsd-lde.service: Unit mdsd-lde.service not loaded.
```

**Comment by abhijeetgaiha** [comment]
Could you paste the contents of your mdsd.err file?
What version of omsagent are you running?

**Comment by jdemchuk** [comment]
This appears repeatedly in the mdsd.err file:
```
2018-01-10T15:49:25.6170590Z: ProtocolHandlerJSON: Unexpected exception while processing messages on 19: Invalid message size
```

Not sure which version of omsagent I have, where can I check?

**Comment by abhijeetgaiha** [comment]
Please try reinstalling LAD. This can be achieved by removing and adding the extension from the CLI as specified in the docs.
