### ISSUE TITLE
VMExtensionProvisioningError for VMSS

### ISSUE THREAD

**Issue by kasunsjc** [Azure/azure-linux-extensions#530]
Following error prompt we when I try to add a custom Script to my VMSS 

`New-AzureRmResourceGroupDeployment : 1:04:56 PM - Resource Microsoft.Compute/virtualMachineScaleSets 'ual-dat' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'ual-dat-LinuxCustomScriptExtension'. Error message: \"Malformed status file 
[ExtensionError] Invalid status/status: failed\"."
      }
    ]
  }`

Following is the Code Snippet I used 
`                    "extensionProfile": {
                        "extensions": [
                            {
                                "type": "Microsoft.Compute/virtualMachines/extensions",
                                "name": "[concat(parameters('vmssName'),'-LinuxCustomScriptExtension')]",
                                "properties": {
                                    "publisher": "Microsoft.OSTCExtensions",
                                    "type": "CustomScriptForLinux",
                                    "typeHandlerVersion": "1.5",
                                    "autoUpgradeMinorVersion": true,
                                    "settings": {
                                        "fileUris":[
                                            "https://<SA Name>.blob.core.windows.net/scripts/installapache.sh"
                                        ],
                                        "commandToExecute":"sh installapache.sh" 
                                    }
                                }
                            }
                        ]
                    }
`

**Comment by boumenot** [comment]
Malformed status generally indicates the script failed to execute.  There isn't a sufficient amount of evidence though to determine if this is the failure or not.  Please raise a case with Azure support, or post the /var/log/waagent.log and the status file for this extension, which is under /var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux/status.
