### ISSUE TITLE
The bash script results in Provisioning failed on version 3.0.111 - Root cause is docker provider in omsagent.

### ISSUE THREAD

**Issue by abhijeetgaiha** [Azure/azure-linux-extensions#536]
This is the Status Message shown on the portal:
Extension operation Daemon failed:'ascii' codec can't encode characters in position 272-274: ordinal not in range(128)

Initially the script looks like it completed fine and status is "Provision Succeeded" (Message: Enable succeeded, extension daemon started), however after about 15-20 mins the status changes to "Error" and the above message is shown.

Filed by https://github.com/pappavic

**Comment by pappavic** [comment]
I used the bash script according to the docs so I believe the config is here:
https://raw.githubusercontent.com/Azure/azure-linux-extensions/master/Diagnostic/tests/lad_2_3_compatible_portal_pub_settings.json

**Comment by pappavic** [comment]
Is there any update on this?

**Comment by pappavic** [comment]
I also came across another error: 
Failed to set up mdsd dependencies: setup_omsagent(): Failed at restarting omsagent (fluentd). Exit code=1, Output=control_omsagent(restart) failed

We managed to get around this by manually adding the folder it was trying to access and giving it access:
`sudo mkdir -p /var/opt/microsoft/omsagent/log/
sudo chmod 777 /var/opt/microsoft/omsagent/log/`

**Comment by nikita-rastogi** [comment]
Hi @pappavic , please provide following info for further investigation:
1. log files located at /var/log/azure/Microsoft.Azure.Diagnostics.LinuxDiagnostic/3.0.111/*    on the machine
2. Run omsagent log collector as explained in following link and provide the archived log file thus obtained under /tmp/omslogs/*
https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/tools/LogCollector/OMS_Linux_Agent_Log_Collector.md

**Comment by jasonzio** [comment]
@yobyot - the [Installing the Extension ](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/diagnostic-extension#installing-the-extension-in-your-vm)section of the LAD 3.0 doc points directly to a sample LAD 3.0 configuration file that will make it behave exactly as LAD 2.3 did. I suppose the doc could also say "Upgrade by first uninstalling LAD 2.3 extension, then installing LAD 3.0 using a suitably-modified copy of the [downloadable sample config](https://raw.githubusercontent.com/Azure/azure-linux-extensions/master/Diagnostic/tests/lad_2_3_compatible_portal_pub_settings.json)"
