### ISSUE TITLE
LAD crashes if control_omsagent fails with a non-ASCII error message

### ISSUE THREAD

**Issue by jasonzio** [Azure/azure-linux-extensions#542]
Stack trace:
```
File "/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/diagnostic.py", line 301, in main
    start_mdsd(configurator)
File "/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/diagnostic.py", line 357, in start_mdsd
    dependencies_err, dependencies_msg = setup_dependencies_and_mdsd(configurator)
File "/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/diagnostic.py", line 155, in setup_dependencies_and_mdsd
    hutil.log, hutil.error)
File ["/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/Utils/omsagent_util.py", line 454](https://github.com/Azure/azure-linux-extensions/blob/master/Diagnostic/Utils/omsagent_util.py#L454), in setup_omsagent
    cmd_exit_code, cmd_output = control_omsagent('restart', run_command)
File ["/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/Utils/omsagent_util.py", line 84](https://github.com/Azure/azure-linux-extensions/blob/master/Diagnostic/Utils/omsagent_util.py#L84), in control_omsagent
    return 1, 'control_omsagent({0}) failed. Output: {1}'.format(op, cmd_output)

ERROR:UnicodeEncodeError: 'ascii' codec can't encode characters in position 227-229: ordinal not in range(128)
ERROR: [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111] Daemon,error,0,Extension operation Daemon failed:'ascii' codec can't encode characters in position 227-229: ordinal not in range(128)
```
I don't know what the unencodable character is, but a general solution for "make the string that came back from run_command() into something that can safely be logged" would solve the problem.

**Comment by nikita-rastogi** [comment]
The system locale for the language of error messages is LC_MESSAGES="en_US.UTF-8" on azure Vms.
can be checked by using command "locale" on the commandline. Whereas, the python 2.7 version uses ascii codec by default. Hence, the situation here isas follows,
the error messages of the bash scripts executed by diagnostic.py are using "utf-8" encoding and these error mesages are then have to be parsed by python using "ascii" encoding. Thus, we get this unicodedecodeerror when the characters in the error message are not present in "ascii".

**Comment by nikita-rastogi** [comment]
the workaround will be to change the codec used by python scripts to utf-8.

**Comment by nikita-rastogi** [comment]
PR: https://github.com/Azure/azure-linux-extensions/pull/589

**Comment by nikita-rastogi** [comment]
PR: https://github.com/Azure/azure-linux-extensions/pull/593
