### ISSUE TITLE
VM Disk Encryption error

### ISSUE THREAD

**Issue by psinger** [Azure/azure-linux-extensions#546]
Hello,

I am trying to encrypt my OS and data disks on a fresh vanilla Ubuntu 16 LTS. The data disk is also empty and fresh, but is 4TB. RAM of the VM is 7GB. 

This is the error I receive:

`VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Failed to enable the extension with error: 'NoneType' object has no attribute 'getheader', stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999309/main/handle.py", line 689, in enable_encryption
    DiskEncryptionKeyFileName=extension_parameter.DiskEncryptionKeyFileName)
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999309/main/KeyVaultUtil.py", line 63, in create_kek_secret
    bearerHeader = result.getheader("www-authenticate")
AttributeError: 'NoneType' object has no attribute 'getheader'`

Any ideas?

**Comment by aku-p** [comment]
Hi psinger,
If the above issue had resolved, could you please share the solution.
Thanks in advance

**Comment by psinger** [comment]
@aku-p I think this error was happening due to firewall issues. See: https://docs.microsoft.com/en-us/azure/key-vault/key-vault-access-behind-firewall

I solved it by temporarily allowing all outgoing connections.
