### ISSUE TITLE
Error message=[ExtensionError] Downgrade not allowed when running ARM template on VM

### ISSUE THREAD

**Issue by alexandreweiss** [Azure/azure-linux-extensions#552]
Hi team,

I'm facing an issue when playing my ARM template to trigger Custom Script Extension without updating my template if the extension version has been upgrade.

My template was set to autoupgrade = false and even changing to true, i'm not able to trigger the extension because of the error in the /var/log/waagent.log : 

**2018/04/03 14:26:30.922232 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.5] Target handler state: enabled
2018/04/03 14:26:30.950484 ERROR [Microsoft.Azure.Extensions.CustomScript-2.0.5] Failed to save handler status: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.5/config/HandlerStatus'
2018/04/03 14:26:31.027202 ERROR Event: name=Microsoft.Azure.Extensions.CustomScript, op=None, message=[ExtensionError] Downgrade not allowed, duration=0**

This message is displayed but the current extension version is 2.0.6.
I also received this error with version 2.0.3 while current extension version was 2.0.6

To be able to proceed my template, i need to do : 
./custom-script-extension disable
./custom-script-extension uninstall

If it doesn't help, deleting the extension from portal (which is in status "unavailable") can help. Portal seems to send command : 
./custom-script-shim disable
./custom-script-shim uninstall

and run again my template using VSTS release management.

Help would be appreciated ! Thanks BR

INFO : 
WALinux agent : WALinuxAgent-2.2.14-1.el7.noarch upgraded to WALinuxAgent-2.2.18-1.el7.noarch seems to solve the problem.
WALinuxAgent upgrade (yum upgrade) seems to be unsupported through custom script extension as it restart the network stack : what is the best option to upgrade the Linux agent if we have 10's of environment ?

**Comment by alexandreweiss** [comment]
Any link perhaps with https://github.com/Azure/WALinuxAgent/issues/1059

**Comment by boumenot** [comment]
Wrong repo, you want https://github.com/Azure/custom-script-extension-linux.  

We published a KB for the downgrade issue, see https://github.com/Azure/WALinuxAgent/wiki/Known-Issues#2221-22-23---extensionerror-downgrade-not-allowed-or-downgrade-is-not-allowed-skipping-install-and-enable.

You do not have the version of the agent that was affected, so I don't think this is the same issue.  Please verify the agent using

```sh
/usr/sbin/waagent --version
```

See the mitigation in the KB for information on how to correct the VMs that are affected.

**Comment by alexandreweiss** [comment]
Thanks Christophe for pointing this resource. Any solution that i could apply widely as we have 10's of env concerned and only manager through VSTS release management ?

**Comment by boumenot** [comment]
1. Yes. 
 2. If auto upgrade is enabled, the mitigation will cause the agent to upgrade within an hour or so.
