### ISSUE TITLE
LinuxDiagnostics error in portal

### ISSUE THREAD

**Issue by anwather** [Azure/azure-linux-extensions#571]
Deployed version 3.0 - in the portal the diagnostics settings blade contains the error -> 

Error encountered: TypeError: Object doesn't support property or method 'sampleRateInSeconds'

The extension is working and I can view the metrics generated.

**Comment by abhijeetgaiha** [comment]
Could you provide logs from /var/logs/azure ?

**Comment by anwather** [comment]
Resolved issue for now - will try to replicate and reopen if it occurs again
