### ISSUE TITLE
High CPU usage of mdsd in SuSE

### ISSUE THREAD

**Issue by Lickkylee** [Azure/azure-linux-extensions#576]
OS: SuSE 12
LAD: Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9021

We have some SuSE 12 systems that have LAD enabled. These systems also have OMSAgent configured. Every now and then, we noticed that mdsd process would comsume a lot of cpu, almost up to 100%.  The problem could be mitigated by reboot. 

We noticed that there was a lot of errors in extension.log to tell that mdsd was unable to connect OMI service like below.  But when this error disappeared, high cpu of mdsd continued until a reboot. 

### 2018/05/04 02:05:11 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9021] Error in MDSD:. (Is OMI installed and started?)
2018/05/04 02:05:11 2017-10-25T05:57:40.7118960Z: Error: Unable to connect to OMI service. (Is OMI installed and started?)
2018/05/04 02:05:11 2017-10-25T05:57:42.0376420Z: Error: Unable to connect to OMI service. (Is OMI installed and started?)
2018/05/04 02:05:11 2017-10-25T05:57:42.7940880Z: Error: Unable to connect to OMI service. (Is OMI installed and started?)
2018/05/04 02:05:11 2017-10-25T05:57:42.9329330Z: Error: Unable to connect to OMI service. (Is OMI installed and started?)
2018/05/04 02:05:11 2018-05-04T02:04:48.4406530Z: 2018-05-04T02:04:48.4406420Z: closing connection due to JSON parse error: Event sender closed connection: writev() failed.: Broken pipe
2018/05/04 02:07:12 2018-05-04T02:05:13.2842430Z: Error: Unable to connect to OMI service. (Is OMI installed and started?)
2018/05/04 02:07:12 2018-05-04T02:06:44.6251370Z: Error: OMI EnumerateInstances failed
2018/05/04 02:07:12 2018-05-04T02:06:45.9343980Z: Error: OMI EnumerateInstances failed
2018/05/04 02:07:12 2018-05-04T02:06:46.4325390Z: Error: OMI EnumerateInstances failed
2018/05/04 02:07:12 2018-05-04T02:06:46.4759360Z: Error: OMI EnumerateInstances failed
2018/05/04 02:07:12 2018-05-04T02:06:47.2836980Z: Error: OMI EnumerateInstances failed
2018/05/04 02:07:12 2018-05-04T02:06:47.7680470Z: Error: OMI EnumerateInstances failed
2018/05/04 02:07:12 2018-05-04T02:06:58.2881930Z: Error: OMI EnumerateInstances failed

1. Can anyone tell if there is any relationship of these errors and high cpu of mdsd? 
2. any advise how to troubleshoot this issue? like what log to collect, which steps to debug? 

We noticed there is also a thread under OMS of this mdsd issue, but no answer yet and redirect people to ask LAD. Hope you can help on this. 
https://github.com/Microsoft/OMS-Agent-for-Linux/issues/632

**Comment by abhijeetgaiha** [comment]
If you have installed or updated omsagent recently, then you might see this issue. We released an update 2.3-9029 that fixes the issue. 

Meanwhile, you can try the following steps to restart mdsd, which should mitigate the issue: 

sudo -s
cd /var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic*/Utils
./diagnostic.py -disable
./diagnostic.py -enable

**Comment by Lickkylee** [comment]
hi Abhijeet
1. May I know why this will cause high cpu? 
2. the env is mooncake, when the update 2.3-9029 will push to  Mooncake Linux? 
3. we had this issue several times, but not every time the OMS agent are updated. Any suggestion?

**Comment by abhijeetgaiha** [comment]
Omsagent January release updated OMI to a version incompatible with previous OMI versions. Restarting mdsd allows mdsd to pick up updated OMI client library that works with the updated OMI server. Till that point, mdsd keeps trying to unsuccessfully connect to the updated OMI server causing high CPU usage.

**Comment by Lickkylee** [comment]
Hi Abhijeet, 

If this is the only cause that mdsd comsumed high cpu ? In our environment, this high cpu would happen intermittently, seemd not always the OMS reason. Any steps to narrow down the possible cuase? 

By the way, if it is supported to run OMS and LAD in parallel?

**Comment by nikita-rastogi** [comment]
Yes oms and LAD can run together on a machine. it is supported.
