### ISSUE TITLE
Update the LAD 3.0 docs to fix issue in date format

### ISSUE THREAD

**Issue by abhijeetgaiha** [Azure/azure-linux-extensions#579]

**Comment by shpimpal** [comment]
Verified on Ubuntu 16.04 and RHEL 6.7, working fine.

**Comment by shpimpal** [comment]
Correct date format should be "-expiry 2019-12-31T23:59:00Z" and not  "--expiry 9999-12-31T23:59Z" as suggested here - https://github.com/MicrosoftDocs/azure-docs/issues/8212

**Comment by abhijeetgaiha** [comment]
Fixed with https://github.com/MicrosoftDocs/azure-docs-pr/pull/42384
