### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-linux-extensions#58]
https://github.com/Azure/azure-linux-extensions/tree/master/VMAccess

the [Learn more: Azure Virtual Machine Extensions](https://msdn.microsoft.com/en-us/library/azure/dn606311.aspx) link is broken.

**Comment by bingosummer** [comment]
Thanks @ahmetalpbalkan .

We were not aware of that. Will fix it shortly.
