### ISSUE TITLE
[VMAccessForLinux] extension being executed against during upgrade from 1.4.7.1 to 1.5.1

### ISSUE THREAD

**Issue by axelgMS** [Azure/azure-linux-extensions#689]
VMAccessForLinux extension was executed again - causing changes to his SSH login.
Looks like this happened because VMAccessForLinux upgraded from 1.4.7.1 to 1.5.1.

**From Norberto:**
This is a bug in the extension: the extension keeps track of the last operation it performed using a file in the extension’s directory (mrseq). This state is used to prevent the extension from executing the same operation more than once (since enable can be called multiple times). During the upgrade to 1.5.1, the extension lost this file and when enable of 1.5.1 was executed the operation already completed by 1.4.7 was executed again, resetting the passwd.

**Comment by pgombar** [comment]
Further investigation showed that the current version of the agent implements the logic to migrate all necessary files to the newer version of the extension. We couldn't repro, so I'm closing this issue.
