### ISSUE TITLE
AzureLinuxdiagnostic issues mdsd and xmlCfg credentials 

### ISSUE THREAD

**Issue by EstebanLopezF** [Azure/azure-linux-extensions#765]
I have enabled the Linuxdiagnostic settings in an Ubuntu 16.04 generalized marketplace image to use the Azure classic alerts for file system free space but the metric is not available and we can observe the below error messages in the extension log.
Waagent version 3.3.37 running healthy, any suggestions about how to fix this?

2019/03/06 16:05:05 [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119] RunCmd SSL_CERT_FILE=/usr/lib/ssl/cert.pem SSL_CERT_DIR=/usr/lib/ssl/certs /usr/local/lad/bin/mdsd -v -c /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml
2019/03/06 16:05:05 ERROR:CalledProcessError.  Error Code is 1
2019/03/06 16:05:05 ERROR:CalledProcessError.  Command string was SSL_CERT_FILE=/usr/lib/ssl/cert.pem SSL_CERT_DIR=/usr/lib/ssl/certs /usr/local/lad/bin/mdsd -v -c /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml
2019/03/06 16:05:05 ERROR:CalledProcessError.  Command result was 2019-03-06T16:05:05.0664740Z: Not all GCS env vars are defined. Missing 6: MONITORING_GCS_ENVIRONMENT MONITORING_GCS_ACCOUNT MONITORING_GCS_REGION MONITORING_GCS_CERT_CERTFILE MONITORING_GCS_CERT_KEYFILE MONITORING_GCS_STORAGE_RESOURCE_TAG_TYPE. GCS won't be used.
2019/03/06 16:05:05 ERROR:Parse reported these messages:
2019/03/06 16:05:05 ERROR:/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml(3) Error: Storage credential validation for table storage failed: Not Implemented
2019/03/06 16:05:05 ERROR:/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml(18) Fatal: AddMonikerEventInfo() failed: No default credential is found.
2019/03/06 16:05:05 ERROR:/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml(25) Error: No default credentials were defined
2019/03/06 16:05:05 ERROR:/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml(31) Fatal: AddMonikerEventInfo() failed: No default credential is found.
2019/03/06 16:05:05 ERROR:/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml(46) Fatal: AddMonikerEventInfo() failed: No default credential is found.
2019/03/06 16:05:05 ERROR:/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml(56) Fatal: AddMonikerEventInfo() failed: No default credential is found.
2019/03/06 16:05:05 ERROR:/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml(69) Fatal: AddMonikerEventInfo() failed: No default credential is found.
2019/03/06 16:05:05 ERROR:/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml(83) Fatal: AddMonikerEventInfo() failed: No default credential is found.
2019/03/06 16:05:05 ERROR:/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml(97) Error: No default credentials were defined
2019/03/06 16:05:05 ERROR:/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery>
2019/03/06 16:05:05 ERROR:/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml(97) Error: No default credentials were defined
2019/03/06 16:05:05 ERROR:/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.119/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery>

Many Thanks!

**Comment by canfikret** [comment]
Please check the type of the storage account. Could it be blob-only?
LAD needs a general storage account with blob and table services.

Thanks,
Fikret.

**Comment by EstebanLopezF** [comment]
Fikret thanks for your help.
That was exactly the problem, we assigned a blob only storage account, after create a general purpose storage the classic alerts worked properly.
