### ISSUE TITLE
VmAccessForLinux shows "is not a supported distribution." when running on SLES15 

### ISSUE THREAD

**Issue by marinnedea** [Azure/azure-linux-extensions#813]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionHandlerNonTransientError\",\r\n \"message\": \"Handler 'Microsoft.OSTCExtensions.VMAccessForLinux' has reported failure for VM Extension 'enablevmaccess' with terminal error code '1007' and error message: '[ExtensionError] Non-zero exit code: 1, extension_shim.sh -c ./vmaccess.py -i\\n[stdout]\\n2019/05/24 07:19:33.505604 INFO ExtHandler Move process 2838 into cgroups for extension Microsoft.OSTCExtensions.VMAccessForLinux\\n2019/05/24 07:19:33.513258 INFO ExtHandler Creating cgroup directory /sys/fs/cgroup/cpu/WALinuxAgent/Microsoft.OSTCExtensions.VMAccessForLinux\\n2019/05/24 07:19:33.522408 INFO ExtHandler Creating cgroup directory /sys/fs/cgroup/memory/WALinuxAgent/Microsoft.OSTCExtensions.VMAccessForLinux\\n\\n **is not a supported distribution.**\\n\\n\\n[stderr]\\nPython 2.7.14\\nTraceback (most recent call last):\\n File \\\"./vmaccess.py\\\", line 31, in <module>\\n waagent = load_waagent()\\n File \\\"/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.5.2/waagentloader.py\\\", line 30, in load_waagent\\n waagent.Config = waagent.ConfigurationProvider(None)\\n File \\\"/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.5.2/waagent\\\", line 3462, in __init__\\n walaConfigFile = MyDistro.getConfigurationPath()\\nAttributeError: 'NoneType' object has no attribute 'getConfigurationPath'\\n'\"\r\n }\r\n ]\r\n }\r\n}"}]}

Please update the extension to support al endorsed Linux Distributions in Azure.

**Comment by ahorvath2019** [comment]
Hi , any updates regarding this Suse 15 and VM agent ?I am unable to install Access extension getting the same   is not a supported distribution.
