### ISSUE TITLE
Cannot install AADLoginForLinux via Azure Resource Manager Template

### ISSUE THREAD

**Issue by jleonelion** [Azure/azure-linux-extensions#846]
The AAD Login for Linux is a great improvement for identity and access management of Linux servers in Azure.  My team relies on Azure Resource Manager template to deploy applications and infrastructure.  I would like to have these server deployments include adding the AAD Login for Linux extension.  Unfortunately, I am encountering errors and cannot figure out how to resolve.

This the error returned from deployment
`{ "id": "/subscriptions/.../resourceGroups/jenkins-devapps-rg/providers/Microsoft.Resources/deployments/initTemplate/operations/DE946D2D62CFD93C", "operationId": "DE946D2D62CFD93C", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-07-04T00:53:35.3932443Z", "duration": "PT2M53.1727507S", "trackingId": "cdbefe00-8b87-4af4-a4e9-ca0cbaa96cce", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'AADLoginForLinux'. Error message: \"Failed to get status file [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001/status/0.status'\"." } ] } }, "targetResource": { "id": "/subscriptions/.../resourceGroups/jenkins-devapps-rg/providers/Microsoft.Compute/virtualMachines/jenkins-vm/extensions/AADLoginForLinux", "resourceType": "Microsoft.Compute/virtualMachines/extensions", "resourceName": "jenkins-vm/AADLoginForLinux" } }}`

This snippet is taken from the template file being used in the deployment that results in the above posted error.
`        {
            "apiVersion": "2019-03-01",
            "location": "[parameters('location')]",
            "name": "[concat(parameters('vmName'), '/AADLoginForLinux')]",
            "properties": {
              "autoUpgradeMinorVersion": true,
              "publisher": "Microsoft.Azure.ActiveDirectory.LinuxSSH",
              "protectedSettings": {},
              "settings": {},
              "type": "AADLoginForLinux",
              "typeHandlerVersion": "1.0"
            },
            "type": "Microsoft.Compute/virtualMachines/extensions"
          }
`

**Comment by davidwneary** [comment]
Same issue here - did you find a solution?

**Comment by davidwneary** [comment]
Actually to provide some more information, I'm getting this error when trying to add the extension using terraform with the following config:

```
resource "azurerm_virtual_machine_extension" "ad_login_extension" {
  name                 = "AADLoginForLinux"
  location             = "${azurerm_virtual_machine.vm.location}"
  resource_group_name  = "${azurerm_virtual_machine.vm.resource_group_name}"
  virtual_machine_name = "${azurerm_virtual_machine.vm.name}"
  publisher            = "Microsoft.Azure.ActiveDirectory.LinuxSSH"
  type                 = "AADLoginForLinux"
  type_handler_version = "1.0"
  auto_upgrade_minor_version = true
}
```

However if I install through the azure command line, it's successful:
```
az vm extension set \
    --publisher Microsoft.Azure.ActiveDirectory.LinuxSSH \
    --name AADLoginForLinux \
    --resource-group rg_name \
    --vm-name vm_name
```

**Comment by bloeys** [comment]
I think the issue is that you are trying to use templates. If I go to a VM which already has ADD installed (through the CLI for example) I get the following message:

> {"code":"ExportTemplateCompletedWithErrors","message":"Export template operation completed with errors. Some resources were not exported. Please see details for more information.","details":[{"code":"ExportVirtualMachineExtensionNotSupported","target":"Microsoft:2EAzure:2EActiveDirectory:2ELinuxSSH-AADLoginForLinux","message":"Virtual machine extension 'Microsoft:2EAzure:2EActiveDirectory:2ELinuxSSH-AADLoginForLinux' is not supported for template export."}]}

That it can not be exported I assume means that template support is not here yet, and you are forced to use the CLI.

**Comment by LukeCarrier** [comment]
I'm not sure there's a difference between template deployment and using the
CLI, Omar. All both do is provision an extension on the VM via ARM.

I've started seeing this working on Ubuntu 18.04 systems as of yesterday,
but I'm not sure what's changed yet; maybe the extension was updated?

I'll try to dig into this over the next couple of days and post back. We
also have a workaround to manually complete the installation and fudge the
status file the agent needs to report that the extension installation was
successful.

**Comment by bloeys** [comment]
It will be interesting if you can pinpoint a specific reason this was happening, it could apply to other extensions (now or in the future), although it could be that something was changed just like you said.

**Comment by jleonelion** [comment]
Through some trial and error, I figured out how to specify the AADLinux extension for a VM defined in an ARM Template.  It really came down to getting the right values for "publisher", "type" and "typeHandlerVersion" right. For future reference, see below example:

```
    {
      "apiVersion": "2019-03-01",
      "dependsOn": [
        "[variables('vmName')]"
      ],
      "location": "[parameters('location')]",
      "name": "[concat(variables('vmName'), '/AADLoginForLinux')]",
      "properties": {
        "autoUpgradeMinorVersion": true,
        "publisher": "Microsoft.Azure.ActiveDirectory.LinuxSSH",
        "type": "AADLoginForLinux",
        "typeHandlerVersion": "1.0"
      },
      "type": "Microsoft.Compute/virtualMachines/extensions"
    },   
```

**Comment by py-wy** [comment]
Hello,
the last comment let understand that an ARM template has to be used but I managed to do it with terraform.

I run into the same issue 

By using a wrong configuration I have had the same error   `No such file or directory: '/var/lib/waagent/Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001/status/0.status'`

To avoid this error you should:

- NOT use"settings" section as for the windows join domain extension
- SET the name to "AADLogingForLinux"

**If the extension fails to be added be sure to delete the extension before adding it again or it will fail even with a valid configuration.**


here is a working terraform resource creation:

`resource "azurerm_virtual_machine_extension" "join_domain" {
 name                 = "AADLoginForLinux"
  location             = var.location
  resource_group_name  = my_ressource_group
  virtual_machine_name = "myVmName"
  publisher            = "Microsoft.Azure.ActiveDirectory.LinuxSSH"
  type                 = "AADLoginForLinux"
  type_handler_version = "1.0"
  auto_upgrade_minor_version = true`

after `terraform apply` the az cli then indicates that the extension is correctly installed

`> az vm extension show -g my_ressource_group --vm-name myVmName --name AADLoginForLinux
{
  "autoUpgradeMinorVersion": true,
  "forceUpdateTag": null,
  "id": "/subscriptions/xxxx-xxx-xxxxx/resourceGroups/my_ressource_group/providers/Microsoft.Compute/virtualMachines/myVmName/extensions/AADLoginForLinux",
  "instanceView": null,
  "location": "francecentral",
  "name": "AADLoginForLinux",
  "protectedSettings": null,
  "provisioningState": "Succeeded",
  "publisher": "Microsoft.Azure.ActiveDirectory.LinuxSSH",
  "resourceGroup": "my_ressource_group",
  "settings": null,
  "tags": {},
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "typeHandlerVersion": "1.0",
  "virtualMachineExtensionType": "AADLoginForLinux"
}`

**Comment by varshhub** [comment]
I am seeing the same issue, below is what I am using in the template for VMSS, does it work with ARM template? 
              {
                "name": "AADLoginForLinux",
                "properties": {
                  "autoUpgradeMinorVersion": true,
                  "publisher": "Microsoft.Azure.ActiveDirectory.LinuxSSH",
                  "type": "AADLoginForLinux",
                  "typeHandlerVersion": "1.0"
                }
              },

No issues when I run it using cli (az vmss extension set --publisher Microsoft.Azure.ActiveDirectory.LinuxSSH --name AADLoginForLinux --resource-group rgname --vmss-name vmssname)

**Comment by gmichels** [comment]
I see a similar issue with scale sets and terraform, where the error is slightly different:

```
2020-10-02T01:39:41.062851Z INFO ExtHandler [Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001] Enable extension [./installer.sh enable]
2020-10-02T01:39:53.090107Z WARNING ExtHandler ExtHandler [PERIODIC] We couldn't read any status for Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001 extension, for the sequence number 1. It failed due to [ExtensionStatusError] [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001/status/1.status'
Inner error: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001/status/1.status'
```

The extension is installed just fine via `az vmss extension set`, the problem only happens when doing via terraform.

I noticed a discrepancy in the output when writing the settings file via terraform:

```
2020-10-02T01:39:09.014743Z INFO ExtHandler [Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001] Initializing extension Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001
2020-10-02T01:39:09.015959Z INFO ExtHandler [Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001] Update settings file: 1.settings
2020-10-02T01:39:09.016229Z INFO ExtHandler [Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001] Install extension [./installer.sh install]
```

And via Azure CLI:
```
2020-10-02T01:45:52.574789Z INFO ExtHandler [Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001] Initializing extension Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001
2020-10-02T01:45:52.586165Z INFO ExtHandler [Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001] Extension has no settings, write empty 0.settings
2020-10-02T01:45:52.595566Z INFO ExtHandler [Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001] Install extension [./installer.sh install]
```

**Comment by stephentyers1975** [comment]
I found the fix to this by first manually installing a VM, enabling system identity and then the extension after. I noticed in the Azure portal the extension had a slightly different name to what I was using in Terraform. I then checked the extension detail via the cli and noticed the name and type were in fact different to the documentation I found online. Please see the AZ CLI CMD and my working terraform block below:

`vm extension show -g <rg_name> --vm-name <vm-name> --name AADSSHLogin`
```
# Create virtual machine extension
resource "azurerm_virtual_machine_extension" "azrm_vm_extension" {
  name                 = "AADSSHLogin"
  virtual_machine_id   = azurerm_linux_virtual_machine.my_terraform_vm.id
  publisher            = "Microsoft.Azure.ActiveDirectory"
  type                 = "AADSSHLoginForLinux"
  type_handler_version = "1.0"
  auto_upgrade_minor_version = true
}

# Create virtual machine
resource "azurerm_linux_virtual_machine" "my_terraform_vm" {
  name                  = "myVM"
  location              = azurerm_resource_group.rg.location
  resource_group_name   = azurerm_resource_group.rg.name
  network_interface_ids = [azurerm_network_interface.my_terraform_nic.id]
  size                  = "Standard_DS1_v2"

  os_disk {
    name                 = "myOsDisk"
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2"
    version   = "latest"
  }

  computer_name  = "hostname"
  admin_username = var.username

  admin_ssh_key {
    username   = var.username
    public_key = azapi_resource_action.ssh_public_key_gen.output.publicKey
  }

  identity {
    type = "SystemAssigned"
  }

  boot_diagnostics {
    storage_account_uri = azurerm_storage_account.my_storage_account.primary_blob_endpoint
  }

}
```

I hope this late comment helps
Steve
