### ISSUE TITLE
Unterminated quoted string

### ISSUE THREAD

**Issue by jeffpatton1971** [Azure/azure-linux-extensions#85]
Going off the example found here https://github.com/Azure/azure-linux-extensions/tree/master/CustomScript, I copied that into a script and added the storage account and key. I uploaded my script that adds the fqdn, updates dns servers, adds the saltstack repo and installs salt-minion. The idea being this would bootstrap all my systems, sadly what I wind up getting is the following:

Status              : Failed
StatusCode          : OK
RequestId           : 09b95e19-c888-42e9-b922-0afda56f3330
Output              :
Error               : {
                        "Details": [],
                        "InnerError": null,
                        "Code": "VMExtensionProvisioningError",
                        "Message": "VM has reported a failure when processing extension 'CustomScriptForLinux'. Error message: \"Script returned an error.\n---stdout---\n\n---errout---\nsetup-script.sh: 17: setup-script.sh: Syntax error: Unterminated quoted
                      string\n\n\".",
                        "Target": null
                      }
StartTime           : 1/6/2016 12:56:14 PM -06:00
EndTime             : 1/6/2016 12:56:38 PM -06:00
TrackingOperationId : 920f6590-a769-4312-bc5e-e46b7d631e9c

Additionally I never see the folders listed in the troubleshooting section show up, there is a customlinuxscript folder for v 1.3.whatever, not the 1.4 that I pass in, based on what the doc says I should see that I think.

this bash script that this should download and run does in fact run locally just fine, additionally we can wget it and run it just fine, so i'm inclined to think there is a different problem. One of the fun things I've noticed as I've been working with azure/powershell is the errors returned are not always the actual errors that are occurring.

**Comment by bingosummer** [comment]
@jeffpatton1971 
`Syntax error: Unterminated quoted string` usually has two possible causes:
1. There is an unmatched quotation mark in the script.
2. A shebang line is missing.

For the v1.4 foler does not show up, it's weird. Could you check whether v1.4 is enabled from `/var/log/waagent.log`?

**Comment by jeffpatton1971** [comment]
I think this may have been a VM issue, when I ran the same against other vm's in azure I didn't really see this problem. Sorry for the late reply, I agree it is odd that the folder never showed up, if you're still interested I can gzip the waagent logs and send them.

**Comment by bingosummer** [comment]
Please send me waagent logs, `/var/log/azure/` and `/var/lib/waagent/<extension>/` if you want.
binxi@microsoft.com

**Comment by bingosummer** [comment]
No response for a long time.
Closing it for now.
Feel free to reopen it.

**Comment by sabretus** [comment]
In my case (I used AKS engine) servicePrincipalProfile.secret was with `'` symbol, which I think failed `Microsoft.Azure.Extensions.CustomScript` run. Recreated secret fixed the problem
