### ISSUE TITLE
VMAccessForLinux - No such file or directory: '/var/lib/waagent/ovf-env.xml'

### ISSUE THREAD

**Issue by axelgMS** [Azure/azure-linux-extensions#870]
Trying to enable the VMAccessForLinux extension on a VM, and it's failing with "**_expected string or buffer_**".
Call stack shows that it's because the ovf-env.xml file is missing.

> 2019/07/30 18:12:50 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Config decoded correctly.
2019/07/30 18:12:50 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] set most recent sequence number to 0
2019/07/30 18:12:50 ERROR:Reading from file /var/lib/waagent/ovf-env.xml Exception is [Errno 2] No such file or directory: '/var/lib/waagent/ovf-env.xml'
2019/07/30 18:12:50 ERROR:[Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Failed to enable the extension with error: expected string or buffer, stack trace: Traceback (most recent call last):
2019/07/30 18:12:50 ERROR:  File "./vmaccess.py", line 104, in enable
2019/07/30 18:12:50 ERROR:    _set_user_account_pub_key(protect_settings, hutil)
2019/07/30 18:12:50 ERROR:  File "./vmaccess.py", line 177, in _set_user_account_pub_key
2019/07/30 18:12:50 ERROR:    ovf_env = waagent.OvfEnv().Parse(ovf_xml)
2019/07/30 18:12:50 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3/waagent", line 4968, in Parse
2019/07/30 18:12:50 ERROR:    LogIfVerbose(re.sub("<UserPassword>.*?<", "<UserPassword>*<", xmlText))
2019/07/30 18:12:50 ERROR:  File "/usr/lib64/python2.7/re.py", line 151, in sub
2019/07/30 18:12:50 ERROR:    return _compile(pattern, flags).sub(repl, string, count)
2019/07/30 18:12:50 ERROR:TypeError: expected string or buffer
2019/07/30 18:12:50 ERROR:
2019/07/30 18:12:50 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Enable,error,0,Enable failed: expected string or buffer

Looking back in history and we can see that the initial provisioning failed:

> 2019/07/24 20:29:00.299099 INFO Daemon Azure Linux Agent Version:2.2.32.2
2019/07/24 20:29:00.300199 INFO Daemon OS: redhat 7.6
2019/07/24 20:29:00.300357 INFO Daemon Python: 2.7.5
...
2019/07/24 20:29:00.328092 INFO Daemon Copying ovf-env.xml
2019/07/24 20:29:00.485076 WARNING Daemon Mounting dvd failed [retry 1/5, sleeping 5 sec]
2019/07/24 20:29:05.589949 WARNING Daemon Mounting dvd failed [retry 2/5, sleeping 5 sec]
2019/07/24 20:29:10.696181 WARNING Daemon Mounting dvd failed [retry 3/5, sleeping 5 sec]
2019/07/24 20:29:15.801207 WARNING Daemon Mounting dvd failed [retry 4/5, sleeping 5 sec]
2019/07/24 20:29:20.905895 WARNING Daemon Mounting dvd failed [retry 5/5, sleeping 5 sec]
2019/07/24 20:29:25.912597 ERROR Daemon Provisioning failed: [ProtocolError] [CopyOvfEnv] Error mounting dvd: [OSUtilError] Failed to mount dvd device
Inner error: [mount -o ro -t udf,iso9660 /dev/sr0 /mnt/cdrom/secure] returned 32: mount: no medium found on /dev/sr0
 (1567094.33s)

so we couldn't copy the ovf-env.xml file on the VM since the DVD mount failed.

Note that if I create a VM from the existing specialized VHD (CreateOption = Attach), then the ovf-env.xml won't exist - and VMAccessForLinux will also fail.

ASK:
- Please confirm if VMAccessForLinux is supposed to work against specialized disks?
- Please improve the VMAccessForLinux so it better handles that scenario where the ovf-env.xml is missing

**Comment by ccrownhart** [comment]
I'm experiencing this same error on a RedHat 7.6.  Does anyone have a workaround for this?

2019/10/02 13:19:49 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] sequence number is 0
2019/10/02 13:19:49 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3/config/0.settings
2019/10/02 13:19:49 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "MIIB6AYJKoZIhvcNAQcDoIIB2TCCAdUCAQAxggFpMIIBZQIBADBNMDkxNzA1BgoJkiaJk/IsZAEZFidXaW5kb3dzIEF6dXJlIENSUCBDZXJ0aWZpY2F0ZSBHZW5lcmF0b3ICEBskMmp2cL2jTuJ30xcdLzIwDQYJKoZIhvcNAQEBBQAEggEAdkFTN4k+ewlw8yShq4/CLwB3Et4/1xIWC7ILZZU5PmLSTPZ1YBbx9SlL50XY39thcE3y/FqPyYsGyRNB4iMkeYSq7lynOUQpTig2XyKzPtKDfYAK0WlnN+/uxc7lma4MRjlIcsM85ERWyUkhb/LeTWNqO2PpuyHH2HTzVDEcq18kwo958gBPWn8T59tdKkvo1JTCe3s74tX7PqJESlGz+35h7mRiAwulWUeNssB7dfxmxzZFh60O3wetlPkSk0ylT19UnGfw+Y78w/Yo5ONRBGK0/2XcGEK7u0y9fOJVRJx89KsPJfT+fJk9jX4w1YUOoi98KLP4HAaMfsVHgtpH9TBjBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECEMQvNIxqXDqgEB1IB9B9NLTmKRXMsxyESyePjiNAP3765erxFO1ilkGr+AHva7mAlGdgwwqkqopDJBxNcCQwDqeVRwH/rLntjxZ", "publicSettings": {}, "protectedSettingsCertThumbprint": "*** REDACTED ***"}}]}
2019/10/02 13:19:49 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Config decoded correctly.
2019/10/02 13:19:49 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Install,success,0,Install Succeeded
2019/10/02 13:19:51 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] sequence number is 0
2019/10/02 13:19:51 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3/config/0.settings
2019/10/02 13:19:51 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "REDACTED", "publicSettings": {}, "protectedSettingsCertThumbprint": "*** REDACTED ***"}}]}
2019/10/02 13:19:51 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Config decoded correctly.
2019/10/02 13:19:51 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] set most recent sequence number to 0
2019/10/02 13:19:51 ERROR:Reading from file /var/lib/waagent/ovf-env.xml Exception is [Errno 2] No such file or directory: '/var/lib/waagent/ovf-env.xml'
2019/10/02 13:19:51 ERROR:[Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Failed to enable the extension with error: expected string or buffer, stack trace: Traceback (most recent call last):
2019/10/02 13:19:51 ERROR:  File "./vmaccess.py", line 104, in enable
2019/10/02 13:19:51 ERROR:    _set_user_account_pub_key(protect_settings, hutil)
2019/10/02 13:19:51 ERROR:  File "./vmaccess.py", line 177, in _set_user_account_pub_key
2019/10/02 13:19:51 ERROR:    ovf_env = waagent.OvfEnv().Parse(ovf_xml)
2019/10/02 13:19:51 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3/waagent", line 4968, in Parse
2019/10/02 13:19:51 ERROR:    LogIfVerbose(re.sub("<UserPassword>.*?<", "<UserPassword>*<", xmlText))
2019/10/02 13:19:51 ERROR:  File "/usr/lib64/python2.7/re.py", line 151, in sub
2019/10/02 13:19:51 ERROR:    return _compile(pattern, flags).sub(repl, string, count)
2019/10/02 13:19:51 ERROR:TypeError: expected string or buffer
2019/10/02 13:19:51 ERROR:
2019/10/02 13:19:51 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Enable,error,0,Enable failed: expected stringor buffer

**Comment by ccrownhart** [comment]
I'm experiencing this same error on a RedHat 7.6. Does anyone have a workaround for this?

2019/10/02 13:19:49 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] sequence number is 0
2019/10/02 13:19:49 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3/config/0.settings
2019/10/02 13:19:49 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "REDACTED", "publicSettings": {}, "protectedSettingsCertThumbprint": "*** REDACTED "}}]}
2019/10/02 13:19:49 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Config decoded correctly.
2019/10/02 13:19:49 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Install,success,0,Install Succeeded
2019/10/02 13:19:51 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] sequence number is 0
2019/10/02 13:19:51 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3/config/0.settings
2019/10/02 13:19:51 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "REDACTED", "publicSettings": {}, "protectedSettingsCertThumbprint": " REDACTED *"}}]}
2019/10/02 13:19:51 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Config decoded correctly.
2019/10/02 13:19:51 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] set most recent sequence number to 0
2019/10/02 13:19:51 ERROR:Reading from file /var/lib/waagent/ovf-env.xml Exception is [Errno 2] No such file or directory: '/var/lib/waagent/ovf-env.xml'
2019/10/02 13:19:51 ERROR:[Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Failed to enable the extension with error: expected string or buffer, stack trace: Traceback (most recent call last):
2019/10/02 13:19:51 ERROR: File "./vmaccess.py", line 104, in enable
2019/10/02 13:19:51 ERROR: _set_user_account_pub_key(protect_settings, hutil)
2019/10/02 13:19:51 ERROR: File "./vmaccess.py", line 177, in _set_user_account_pub_key
2019/10/02 13:19:51 ERROR: ovf_env = waagent.OvfEnv().Parse(ovf_xml)
2019/10/02 13:19:51 ERROR: File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3/waagent", line 4968, in Parse
2019/10/02 13:19:51 ERROR: LogIfVerbose(re.sub(".?<", "<", xmlText))
2019/10/02 13:19:51 ERROR: File "/usr/lib64/python2.7/re.py", line 151, in sub
2019/10/02 13:19:51 ERROR: return _compile(pattern, flags).sub(repl, string, count)
2019/10/02 13:19:51 ERROR:TypeError: expected string or buffer
2019/10/02 13:19:51 ERROR:
2019/10/02 13:19:51 [Microsoft.OSTCExtensions.VMAccessForLinux-1.5.3] Enable,error,0,Enable failed: expected stringor buffer

**Comment by axelgMS** [comment]
@ccrownhart only workaround would be to create a new VM with the same SSH user/password, and copy the ovf-env.xml to the "failed" VM.
VMAccessForLinux needs that file to work and that file doesn't exist on VMs created from specialized disk (CreateOption = Attach)

**Comment by axelgMS** [comment]
Enigneering Team is looking at this issue and it should be fixed in a future release of the VMAccessForLinux extension.

**Comment by axelgMS** [comment]
Should be fixed with recent release 1.5.5 of VMAccessForLinux - see code change below
https://github.com/Azure/azure-linux-extensions/commit/5e076e470d7aa04fb491dc7b8a385e63686cddbb#diff-ab86dfd9337160d056c96354639aef32

**Comment by sebansal** [comment]
Running into the same issue
