### ISSUE TITLE
Add NS-BSD compatibility for VMBackup Extension

### ISSUE THREAD

**Issue by remip2** [Azure/azure-linux-extensions#896]
I'm trying to add compatibility with NS-BSD OS for the VMBackup extension. The current extension  (9151) fails during the installation and the backup fails as well.

I prepared the patch in a fork: https://github.com/remip2/azure-linux-extensions/tree/nsbsd-os-support

Before submitting a pull-request I want to test the code and verify the extension install correctly and allows backups. How can I manually install my patched extension ?

**Comment by soumyapattnaik** [comment]
i have added the code review comments.

**Comment by vrdmr** [comment]
#966 Merged. Closing the issue.
