### ISSUE TITLE
vmaccess: new user question

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-linux-extensions#94]
Docs say I should username/password to create a new sudo user. Can't I use username/ssh_key?

![image](https://cloud.githubusercontent.com/assets/159209/12964336/672da7bc-d004-11e5-8804-3f013259c69e.png)

**Comment by bingosummer** [comment]
@ahmetalpbalkan 
yes. You can use username/ssh_key
```
{
  "username":"azureuser1",
  "ssh_key":"ssh-rsa ..."
}
```
I will add this scenario in the doc later, and then close this issue.
