### ISSUE TITLE
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)

### ISSUE THREAD

**Issue by rboorgapally** [Azure/azure-linux-extensions#95]
I am executing a simple script on Ubuntu 14.04.2-LTS using the Custom Script extension. The first command is:

sudo apt-get update -y

Then I just install git and pip and run a python script. But I run into an error where the update fails with the following error:

E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

If some other process is using it, who is it? I run into this error most of the time but not always. That makes me suspect that the extension is calling the script before it is done initializing.

**Comment by bingosummer** [comment]
@rboorgapally 
Thanks for your report.

Several questions to narrow down the issue:

1. Do you install other extensions (e.g. Diagnostic extension, Docker extension)?
  You can look at `/var/lib/waagent` to check whether there are other extensions.
  If so, maybe other extensions are using `apt-get`.

2. How do you enable CustomScript extension? ARM templates, Azure CLI/Powershell?

3. Check if there are some errors in `/var/log/waagent.log` and `/var/log/azure/`.

**Comment by rboorgapally** [comment]
1. Yes, docker extension
2. ARM Templates
3. Will check next time I deploy.

**Comment by bingosummer** [comment]
@rboorgapally 
Docker Extension use `apt-get` too.

I suggest that you can add a `dependsOn` to make two extensions enable in serial.
https://github.com/Azure/azure-quickstart-templates/blob/master/201-dependency-between-scripts-using-extensions/azuredeploy.json#L205

**Comment by rboorgapally** [comment]
Yes I added _dependsOn_ to make the operations serialized.
