### ISSUE TITLE
"waagent_ext_event_type' is not defined" on Debian 10

### ISSUE THREAD

**Issue by rossifumax** [Azure/azure-linux-extensions#977]
Hello, 

I encounter this error when trying to install the VM Linux extension Diagnostic on Debian 10 with Terraform :
```
Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'LinuxDiagnostic'. Error message: \"Extension operation Enable failed:global name 'waagent_ext_event_type' is not defined\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionLinuxDiagnosticsTroubleshoot "
```

This is the details of the extension that i try to install : 
```
Name : LinuxDiagnostic
Publisher : Microsoft.Azure.Diagnostics
```

After a long research, it happens on Debian 10 and 11-daily, and not on UbuntuServer 18.04-LTS, it's because on Debian's distros, the package `gpg` is not installed. 

After a test where i created my vm, install `gpg` package on it, and i launched the install of the VM extension Diagnostic, all was ok.

The error log message on the VM : 
```
2020/01/13 10:09:42 [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.125] Begin omsagent setup.
2020/01/13 10:09:42 [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.125] RunCmd sh omsagent-*.universal.x64.sh --upgrade
2020/01/13 10:09:42 ERROR:CalledProcessError.  Error Code is 65
2020/01/13 10:09:42 ERROR:CalledProcessError.  Command string was sh omsagent-*.universal.x64.sh --upgrade
2020/01/13 10:09:42 ERROR:CalledProcessError.  Command result was Checking host architecture ...
2020/01/13 10:09:42 ERROR:gpg is not installed, installation cannot continue.
2020/01/13 10:09:42 ERROR:Shell bundle exiting with code 65
2020/01/13 10:09:42 [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.125] Return 65:Checking host architecture ...
2020/01/13 10:09:42 gpg is not installed, installation cannot continue.
2020/01/13 10:09:42 Shell bundle exiting with code 65
```

Can you please add the installation of `gpg` package when installing the VM extension ?
Thanks in advance

**Comment by axelgMS** [comment]
https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/Troubleshooting.md

65 | Missing gpg program; Install gpg

**Comment by rossifumax** [comment]
> https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/Troubleshooting.md
> 
> 65 | Missing gpg program; Install gpg

Oh, i haven't seen this .. 

So, the user need to install manually the package "gpg" before to install the extension ? 
Hm .. not really convenient !
