### ISSUE TITLE
LAD is limited to upload 2 events per second to EventHubs

### ISSUE THREAD

**Issue by zhusulai** [Azure/azure-linux-extensions#978]
https://github.com/Azure/azure-linux-extensions/blob/d78cd87e469e8643a95449ada69d7b6900dec5ae/Diagnostic/mdsd/mdscommands/EventHubUploader.cc#L210

EH is capable of handling 1000 events per second per TU. The hardcoded delay (0.5s) limits LAD to upload a maximum of 2 events per second, which is ridiculously low. For high volume logs, events could be queued up for hours before being uploaded. The long queue also leads to loss of logs if the VM is shutdown before events are upload.

**Comment by AaronRM** [comment]
@zhusulai Thank you for opening this issue. We are hoping to have the fix rolled out in the next release of the Diagnostics VM extension.
