### ISSUE TITLE
Where has Microsoft.OSTCExtensions.LinuxDiagnostic-2.1.5 come from?

### ISSUE THREAD

**Issue by jstangroome** [Azure/azure-linux-extensions#99]
The most recent tag and release for the Linux diagnostic extension in this repository is v1.0.0 from April 2015.

**Comment by karataliu** [comment]
You can access the latest Diagnostic extension code here:

https://github.com/Azure/azure-linux-extensions/tree/master/Diagnostic

**Comment by jstangroome** [comment]
Thanks @karataliu. That did seem to be the latest code but I was looking for the commits corresponding to the specific version running in my Azure VMs. 

Is tagging not being used when releasing versions?

Is there some other way that released versions can be traced back to their commits?

**Comment by karataliu** [comment]
Diagnostic extension's open source with new License begins with v2.2, basically we'll use single pull request to update source code. 

2.2 : https://github.com/Azure/azure-linux-extensions/pull/87
2.3 : https://github.com/Azure/azure-linux-extensions/pull/96

Thanks for the reminder about tags, we plan to keep using that for upcoming updates.

**Comment by jstangroome** [comment]
Thank you.
