### ISSUE TITLE
[OmsAgentForLinux] Unsupported operating system: RHEL/CentOS  8

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-linux-extensions#992]
**RHEL/Centos 8** is still not supported by **OmsAgentForLinux** (hard coded)

### Version
```
# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.0 (Ootpa)
```
### Error
```
[ExtensionOperationError] Non-zero exit code: 51, /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/omsagent.py -install
[stdout]
2020/01/23 05:53:24 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17] Install,failed,51,Unsupported operating system: Red Hat Enterprise Linux 8.0
```

### Version
```
# cat /etc/redhat-release
CentOS Linux release 8.0.1905 (Core)
```
### Error
```
[ExtensionOperationError] Non-zero exit code: 51, /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/omsagent.py -install
[stdout]
2020/01/23 05:42:35 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17] Install,failed,51,Unsupported operating system: CentOS Linux 8.0.1905
```

**Comment by johanburati** [comment]
Same issue with *Oracle Linux 8*

## Oracle Linux 8
### Version
```
# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.0 (Ootpa)
```
## Error
```
[ExtensionOperationError] Non-zero exit code: 51, /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/omsagent.py -install
[stdout]
2020/01/23 06:14:24 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17] Install,failed,51,Unsupported operating system: Oracle Linux Server 8.0
```

**Comment by johanburati** [comment]
I have submitted  PR https://github.com/Azure/azure-linux-extensions/pull/993 to allow the **OmsAgentForLinux** extension to install on **RHEL/CentOS/Oracle Linux 8**

**Comment by hestolz** [comment]
By design. These distributions are not yet supported by the agent. We will verify them in the future; RHEL8 is targeted for this February. Others will follow TBD.

**Comment by nikgoodley-ibboost** [comment]
Is there any update on this? Per the comments here and on the pull request it was due to be Feb for RHEL and then CentOS soon after, but it's been a couple of months now.

**Comment by Lowmach1ne** [comment]
Any update ?

**Comment by Faeon4** [comment]
according to my ticket, they said in May rhel8.x may be delayed due to covid

**Comment by Faeon4** [comment]
RHEL8.2 is out, please make sure it is updated and working on the minor release. whenever this thing comes out.

**Comment by Klaas-** [comment]
Funny side effect: I get Azure Advisor recommendation for my RHEL8 machines: `Monitoring agent health issues should be resolved on your machines` -- but I can't remediate it because the extension can't install :)

**Comment by Faeon4** [comment]
is it is a mess at the moment this was addressed in 2019 about rhel8.x and centos8.x I think sles as well, there is also a ruby vulnerability which needs to be patched if I recall anything older than 2.6.5 I thing, our PCI scanners are finding these too. All we can do is wait for the release of the agents for newer versions including lad and the rest. I suspect maybe November as the last update came out November

**Comment by johanburati** [comment]
Any update on this ? 
It was supposed to be supported by Feb, it is now July and still no update.
Will try to get this moving...

**Comment by ranieuwe** [comment]
Ubuntu 20.04 LTS also affected, similar issue. Linking https://github.com/microsoft/OMS-Agent-for-Linux/issues/1216 and https://github.com/microsoft/OMS-Agent-for-Linux/issues/1217

**Comment by ross-worth** [comment]
Please progress this, it's nearly a year since OS release...

**Comment by Klaas-** [comment]
It is actually supported in RHEL8 -- https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/README.md#64-bit
but it still needs manual work because it uses python2 and the extension can't install that on it's own

**Comment by Faeon4** [comment]
Does not work correctly on rhel8.2, you can try with the python2.x but still issues. I do not foresee this getting fixed anytime soon, as there is no incentive for MS to correct this. I have given up on this long time ago already. Our IVS also picks up ruby vulnerabilities too, as our environment needs to be PCI certified under a few certifications. LAD is also broken, regular updates come out for RHEL8.2, and soon we will be on RHEL8.3 etc. and it will be broken again even if they tried to correct it for RHEL8.1 / RHEL8.2.

Best bet is if you got any python and ruby developers, get them to fix it yourself.

**Comment by rdtechie** [comment]
These steps work for me on a freshly deployed RHEL8.2 Azure VM:

```
sudo  yum install -y python2
sudo alternatives --set python `which python2` 
sudo wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w <workspaceid> -s <workspacekey>
```

However I would like to see that the oms agent is not dependent on python 2 anymore. Any timeline on this? @hestolz

**Comment by ross-worth** [comment]
> It is actually supported in RHEL8 -- https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/README.md#64-bit
> but it still needs manual work because it uses python2 and the extension can't install that on it's own

I should have specified CentOS. Which shows as 6 and 7.

**Comment by hestolz** [comment]
Hello! OMS 1.13.27 is now released (extension and shell bundle both) which offers support for RHEL 8.X, CentOS 8.X, SLES15.X, Ubuntu 20.04. The requirement for python2 and python aliasing has been eliminated, so you can now use this on a python3-only system if you choose. Note that if both python 2 and 3 are present, the agent will always default to python2.

Also the ctypes module is still a requirement; python3 should have this by default, but if you have python2 you may need to install the python-ctypes package.

Thanks for your patience, there were a number of complications with the development of this release.

**Comment by Klaas-** [comment]
@hestolz the docs still need updating :) https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/README.md#64-bit https://docs.microsoft.com/en-us/azure/azure-monitor/platform/agents-overview#supported-operating-systems https://docs.microsoft.com/en-us/azure/azure-monitor/platform/agent-linux

And I am guessing this issue can finally be closed.

**Comment by ScottSorrentino** [comment]
I hate to add on to a closed issue, but there seems to still be a requirement for a `/usr/bin/python` alias to complete installation in 1.13.27, at least in Azure.  I ran an install on a CentOS 8.2.2004 instance in Azure, by activating the OMS extension on an Azure VM, and `waagent` launched `omsagent-1.13.27-0.universal.x64.sh`.  While that script itself does a good job of detecting the `python2` executable in `get_python_command()`, and carries that through to verifying whether ctypes is present, the bundled omsconfig-1.1.1-930.x64.rpm package does not.  It contains a pre-install script, with this logic:


```
# pythonVersion check must be repeated for each section
if  [ ! "$(python2 --version 2>&1 | grep 'not found')" ]; then
  echo "Using python2"
  pythonVersion="python2"
elif [ ! "$(python3 --version 2>&1 | grep 'not found')" ]; then
  echo "Using python3"
  pythonVersion="python3"
else
  echo "Python not found."
fi
# Only check for ctypes if python2 is installed
if [ "$pythonVersion" = "python2" ]; then
   echo "Checking for ctypes python module..."
   python -c "import ctypes" 1> /dev/null 2> /dev/null
   cmdline_ctypes=$?
   if [ $cmdline_ctypes -ne 0 ]; then
      echo "Error: Python does not support ctypes on this system.  Please install the ctypes module for Python or upgrade to a newer version of python that comes with the ctypes module."
      echo "Please remove the omi package and try again after installing the ctypes module or upgrading Python.  You can check if the ctypes module is installed by starting python and running the command: 'import ctypes'"
      exit 1
   fi
fi

```

Basically, it checks for and notes you're using python2, stores it in $pythonVersion, but still executes `python` to check for the ctypes module.  When that fails, the installation fails.  In my case, `python2` does have ctypes installed.

This matches what I see in the logs:

```
2020/10/19 22:19:22 ----- Upgrading package: omsagent (omsagent-1.13.27-0.universal.x64) -----
2020/10/19 22:19:22 Skipping package since existing version >= version available
2020/10/19 22:19:22 Applying Syslog conf hotfix...
2020/10/19 22:19:22 Syslog conf (/etc/opt/microsoft/omsagent/conf/omsagent.d/syslog.conf) not found, hotfix skipped.
2020/10/19 22:19:22 ----- Upgrading package: omsconfig (omsconfig-1.1.1-930.x64) -----
2020/10/19 22:19:22 Using python2
2020/10/19 22:19:22 Checking for ctypes python module...
2020/10/19 22:19:22 Error: Python does not support ctypes on this system.  Please install the ctypes module for Python or upgrade to a newer version of python that comes with the ctypes module.
2020/10/19 22:19:22 Please remove the omi package and try again after installing the ctypes module or upgrading Python.  You can check if the ctypes module is installed by starting python and running the command: 'import ctypes'
2020/10/19 22:19:22 error: %prein(omsconfig-1.1.1-930.x86_64) scriptlet failed, exit status 1
2020/10/19 22:19:22 error: omsconfig-1.1.1-930.x86_64: install failed
2020/10/19 22:19:22 omsconfig-1.1.1-930.x64 package failed to upgrade and exited with status 1
2020/10/19 22:19:22 OMS Troubleshooter is installed.
2020/10/19 22:19:22 You can run the Troubleshooter with the following command:
2020/10/19 22:19:22
2020/10/19 22:19:22   $ sudo /opt/microsoft/omsagent/bin/troubleshooter
2020/10/19 22:19:22
2020/10/19 22:19:22 Shell bundle exiting with code 18
2020/10/19 22:19:22 ERROR:Install failed with exit code 18 Checking host architecture ...
```

**Comment by hestolz** [comment]
@ScottSorrentino since that is an issue in omsconfig (== DSC), this issue can be raised in the [appropriate repository](https://github.com/microsoft/PowerShell-DSC-for-Linux). Thanks!
